### ISSUE TITLE
A program using references to arrays but nothing else produces invalid typedefs

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#102]
This is a tracking issue for a known bug in Carp: when a function uses Arrays, but does not generate them, no typedef is emitted. This leads to errors in the C compiler. For an example see the following function:

```
(defn accumulate [arr]
   (let [acc 0]
     (do
       (for [i 0 (count arr)]
          (set! &acc (+ acc @(Array.nth arr i))))
       arr)))
```

It can be fixed currently by defining a bogus function that generates an array, for instance:

```
(defn bogus []
  [0.0])
```

Cheers

**Comment by eriksvedang** [comment]
Solved now.

**Comment by hellerve** [comment]
Confirmed in my test cases, thank you!
