### ISSUE TITLE
Symbol (name) given to `register` should be enforced to be unqualified

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#1031]
Might be a problem for other primitives that define things too...

**Comment by hellerve** [comment]
The definition doesn’t make it quite clear: is this intended behavior that we should check for, or should we extend the functionality to have qualified symbols as well? I’m gravitating towards the former.

**Comment by eriksvedang** [comment]
Sorry, I wrote it quickly. Yeah we should rule this out and define things inside modules if we want them qualified.

**Comment by eriksvedang** [comment]
(Was what I meant)
