### ISSUE TITLE
Proposal: Using something like Conventional Commits

### ISSUE THREAD

**Issue by TimDeve** [carp-lang/Carp#1037]
I was wondering if people would be interested in trying [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) (at least for merge commits).
To summarise the concept, commits are tagged to signify what they do (`feat:`, `fix:`, `docs:`, etc...), the point is for the `git log` to be machine readable and would help us generate changelogs.
It would probably make the life of people not following HEAD much easier as they would be able to check the changelog for breaking changes and update their code accordingly without us having to manually write changelogs.

**Comment by eriksvedang** [comment]
I'm trying to use this, but sometimes forget...
I'll try to make a changelog for the next release, and we'll see how it goes!
Should I start renaming PR:s (adding the prefix) that doesn't follow this pattern?

**Comment by TimDeve** [comment]
Sure, have you had a look at any scripts to generate the changelog (I've never tried myself)?

**Comment by eriksvedang** [comment]
I have not, but I think that ` git log --oneline ` and cleaning it up a bit manually could be fine..?

**Comment by TimDeve** [comment]
Yeah I would sort them by category (breaking change, feature, fix, etc...) in the changelog but that should be simple enough.

**Comment by jacereda** [comment]
I wouldn't mind using this if it was enforced in commit hooks via something like https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional

Otherwise I'm quite confident I'll forget. Too bad it's JS, it'll probably download the whole world and a piece of the universe  when installing.

**Comment by TimDeve** [comment]
I actually thought you might object to most of the tools being made with node. I'm assuming there are shell scripts alternatives.

**Comment by jacereda** [comment]
https://github.com/jorisroovers/gitlint

**Comment by jacereda** [comment]
https://gist.github.com/lucianmachado/459e3cbd39658406ecf530f35b00884f

**Comment by TimDeve** [comment]
I prefer that, this way we can put it in the repo.

**Comment by eriksvedang** [comment]
Thanks!
