### ISSUE TITLE
Release scripts broken

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#1039]
Seems like the release scripts broke (I noticed this when trying to add one for Windows... now none of them work). 

Seems to be a mixture of Stack problems and some changes to Github actions?

**Comment by TimDeve** [comment]
Ah yeah, we had the same problem with the other CI, `v1.1` of the haskell action still uses `add-path`, if you switch to just `v1` it should pull the latest `v1.x.y`.

**Comment by eriksvedang** [comment]
Fixed!
