### ISSUE TITLE
no member named 'val' in 'Bucket__Lambda_set_MINUS_idx__int_void_26_env'

### ISSUE THREAD

**Issue by charlesetc** [carp-lang/Carp#1044]
I have a file "main.carp": 
```clojure
(defn main []
  (let-do
    [lines (Array.allocate 0)
     numbers (Array.copy-map &(fn [x] (Maybe.unsafe-from (Int.from-string x))) &lines)
     numbers-with-units (Array.copy-map &(fn [x] (Pair.init @x ())) &numbers)
     numbers-map (Map.from-array &numbers-with-units) 
     ]   
    (IO.println &(Array.str &numbers-with-units))))
```
Here's what I'm seeing when I try to compile it:

```bash
$ carp -x main.carp 
out/main.c:6433:14: error: no member named 'val' in 'Bucket__Lambda_set_MINUS_idx__int_void_26_env'
    _26_env->val = val;
    ~~~~~~~  ^
out/main.c:6433:20: error: use of undeclared identifier 'val'
    _26_env->val = val;
                   ^
out/main.c:7828:31: error: expected expression
                    void* v = ;
                              ^
out/main.c:7867:18: error: no member named 'v' in 'Map__Lambda_put__int_void_48_env'
        _48_env->v = v;
        ~~~~~~~  ^
out/main.c:7867:22: error: use of undeclared identifier 'v'
        _48_env->v = v;
                     ^
5 errors generated.
carp: callCommand: clang  -o out/Untitled -I /home/charles/build/Carp/core/  -fPIC -g -std=c99 -D_DEFAULT_SOURCE -Wall -Werror -Wno-unused-variable -Wno-self-assign -lm out/main.c (exit 1): failed

```

This seems like a bug? Thanks for looking!

**Comment by charlesetc** [comment]
This seems to happen whenever I try to use `Map.put`, `Map.put!` or `Map.from-list`

**Comment by charlesetc** [comment]
Actually I think it has to do with the `()` construct I'm trying to use as a unit... are there units in Carp?

**Comment by eriksvedang** [comment]
Hi! Are you building the compiler from source or using the latest release? This is fixed in `master`, I'll try to make a new release asap.

**Comment by eriksvedang** [comment]
> are there units in Carp?

Yup!

**Comment by scolsen** [comment]
Ah, looks like a legit bug--I think I know how to fix this.

**Comment by charlesetc** [comment]
Hmm yeah I'm running `stack build && stack install` on master, f89a3f130e74004d38814ac7054f64d4296a3227.

**Comment by eriksvedang** [comment]
> Hmm yeah I'm running `stack build && stack install` on master, [f89a3f1](https://github.com/carp-lang/Carp/commit/f89a3f130e74004d38814ac7054f64d4296a3227).

OK, sorry about that!

**Comment by scolsen** [comment]
@charlesetc thanks for reporting! PR https://github.com/carp-lang/Carp/pull/1046 has a fix!
