### ISSUE TITLE
Compiler error for explicit typing?

### ISSUE THREAD

**Issue by NOP0** [carp-lang/Carp#105]
The following code

```
;; Test

(use IO)
(use Int)
(use String)

(def myvariable (the Int 5))

(defn main []
    (println ( ref(Int.str myvariable))))
```
gives
> ./out/main.c:196:18: error: initializer element is not a compile-time constant
int myvariable = _5;

**Comment by hellerve** [comment]
This particular snippet seems to work now. I guess this is resolved?

**Comment by eriksvedang** [comment]
OK!
