### ISSUE TITLE
`break` keyword not handled by memory management system

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#1052]
We use `break` for important optimizations in Core (where it's correct, by inspection). 

Ideally we would be able to rule out misuses like the following:

```clojure
(defn f []
  (for [n 0 5]
    (let-do [leak @"LEAK"]
      (break))))
```

**Comment by hellerve** [comment]
Wouldn’t it be appropriate for `break` to “just” insert the appropriate deleters for the enclosing loop?

**Comment by eriksvedang** [comment]
> Wouldn’t it be appropriate for `break` to “just” insert the appropriate deleters for the enclosing loop?

Perhaps, yes! (fingers crossed...)

**Comment by hellerve** [comment]
I investigated this a bit, and found a potential fix. This fix descends from any `while` or `let` expression (until it finds another `while` expression, which is when its scope ends) and fixes up any `break` statement inside with  the deleter info that it captures. I’m not sure this is 100% sound, but it sounds reasonable to me. It might  be worth pointing out that it took me three tries to get it “right”, which is a bad sign.

It seems to work on the example, and I have a feature branch for this [here](https://github.com/carp-lang/Carp/compare/master...hellerve:veit/fix-1052), if you want to test this out.

What do y’all think?

**Comment by eriksvedang** [comment]
Looks good, though there is something a little strange about the whole thing. But maybe that is to be expected for such a "procedural" feature.

**Comment by hellerve** [comment]
Yeah, I think the  problem is that `break` needs “outside council”; it needs to know about context outside of its control. Usually we would just descend into `break` and handle things there, but it doesn’t have the context necessary at hand once we reach it.
