### ISSUE TITLE
Symbol.prefix performs lookup on its arguments

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#1057]
The following code won't work as expected:

```clojure
(defndynamic foo [car]                                                                                                                          
  (Symbol.prefix car 'foo)
```

```
鲤 (foo 'x)
Can’t call `prefix` with (command Dynamic.car [x]) at dummy-file:0:0.

Traceback:
(Symbol.prefix car (quote foo)) at /Users/scottolsen/dyna.carp:2:3.
(foo (quote x)) at REPL:1:1.
```

The issue here is that the global dynamic function `Dynamic.car` winds up shadowing the function's argument of the same name. Symbol.prefix seems to evaluate its first argument as dynamic functions do, performing a lookup (thus we get `command....`) when it probably shouldn't evaluate its arguments?

**Comment by scolsen** [comment]
Or, perhaps it should still perform a lookup, but in any case the argument should take priority. If an symbol of the same name exists in the context's internal env's current argument list, we should be using that, not the result of the global/dynamic lookup.

**Comment by hellerve** [comment]
This seems to be an old bug rearing its ugly head again: #659.
