### ISSUE TITLE
RFC: Explicit commands for documentation

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#1076]
As convenient as it is, I don't like the fact that typing `Int.+` in the REPL ends up printing the documentation. I would expect that to yield the evaluation of that form. ghci and several other REPLs would handle this via something like `:i Int.+`. We could try to replicate that or have a primitive. What do you think?

**Comment by scolsen** [comment]
We do have `:i` in fact, that's what you see when you type `Int.+` by itself. I'm fine with either behavior.

**Comment by eriksvedang** [comment]
I'd prefer evaluation too, to be able to inspect the value of global variables (`def`).

**Comment by hellerve** [comment]
Since this is just a special case, “fixing” this is as simple as removing a special case from `executeCommand` in `Eval`. This would yield:

```
> Int.+
=> (external Int.+ (λ [Int Int] Int))
> (defdynamic x 1)
> x
=> 1
> (def y 2)
> y
=> (def y 2)
```

I suppose we should then replace that with a special case for static values?

**Comment by eriksvedang** [comment]
Shouldn't it just compile `def`:s and run those just like functions?

**Comment by hellerve** [comment]
That would be a special case, since we don’t automatically build and run unless it’s a call expression. We can make it so that not just call expressions get run, but that would potentially lead to very weird behaviors, especially if it’s not just `def`s, but also functions like `Int.+` we include. Either way it wouldn’t be hard implementation-wise, but I’m not sure what the right approach would be.

**Comment by eriksvedang** [comment]
We can print functions though (as "λ"). So they would evaluate just fine.

**Comment by eriksvedang** [comment]
The idea would be to completely rely on `HasStaticCall` to figure out whether to build-and-run or not.

**Comment by hellerve** [comment]
We already do that, but `HasStaticCall` is not emitted on symbol lookup in `eval`.

**Comment by eriksvedang** [comment]
> We already do that, but `HasStaticCall` is not emitted on symbol lookup in `eval`.

I see. But maybe it could?

**Comment by hellerve** [comment]
I’m experimenting with this approach as we speak, and will report back on my findings!

**Comment by hellerve** [comment]
This approach seems to work, although it is a little clunky (I’m sure it can be made prettier, though). This is the output now:

```
> Int.+
Compiled to '/Users/veitheller/.carp/out/Untitled' (executable)
λ
=> 0
> +
=> (command Dynamic.+ [[x] [y]])
> (def x 1)
> x
Compiled to '/Users/veitheller/.carp/out/Untitled' (executable)
1
=> 0
> (defn y [] 1)
> y
Compiled to '/Users/veitheller/.carp/out/Untitled' (executable)
λ
=> 0
```

The special cases in symbol lookup are limited to `def`, `defn`, and `external` for now. Does that seem reasonable?

**Comment by scolsen** [comment]
This seems like the right approach to me, but it also breaks `s-expr` which I believe relied on the fact that we returned each form on eval--we'll have to update the definition of `s-expr` to explicitly call `info` now instead.

**Comment by hellerve** [comment]
The behavior of `eval` is now controllable by an additional parameter that tells us whether to emit `HasStaticCall` or not (on the top-level it should, everywhere else it shouldn’t). I think that resolves this issue.
