### ISSUE TITLE
Closures cache all environments

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#1101]
When closures are created, they save the state of the environments around them so they can lookup values later. This works fine in most cases, but since the environment is persistent, updates to the global environment etc will not be saved. Even types and interface implementations will not be present.

Consider this use case:

```clojure
(defdynamic t-member-names ; could be a defndynamic here, but bear with me
  (fn [] (map car (members T))))
  
(deftype T [x Int])

(t-member-names) ; will not be able to find T, because it wasn’t defined when the fn was
```

This is a problem that cropped up during the implementation of a generic `derive`, which heavily relies on dynamic `fn`s.

Cheers

**Comment by scolsen** [comment]
Ahhh so that’s the cause of “fixed definition order” I’ve seen this before too.

Could we solve this by just setting the parent of the parent env of the closure to the current context env structure art call time?

**Comment by hellerve** [comment]
> Could we solve this by just setting the parent of the parent env of the closure to the current context env structure at call time?

This would only work if we didn’t want to support arbitrary nesting of `fn`, I think? But it might be worth trying out!

**Comment by eriksvedang** [comment]
I've been trying to come up with some ideas for how to fix this but it's quite hard. How important is it for implementing your code? (Quite important I assume...) 

We could capture global variables as paths rather than envs but that doesn't work for local vars. Maybe we need mutable cells of some sort when capturing dynamic local vars. They could be referred to via a unique ID or something (and stored in the Context). 

Ideally we can just solve this with the existing envs but I dont quite see how...

**Comment by hellerve** [comment]
Well, the problem is that you won’t be able to read from or modify global variables from within a closure, which is a pretty big problem IMO.

I think we might have to go with `IORef`s to environments in the mid-to-long term to rectify these issues. That’s pretty annoying, but I think necessary?

**Comment by eriksvedang** [comment]
Yeah that's probably the most complete solution.

**Comment by eriksvedang** [comment]
> Ahhh so that’s the cause of “fixed definition order” I’ve seen this before too.
> 
> 
> 
> Could we solve this by just setting the parent of the parent env of the closure to the current context env structure at call time?

I've pondered this some more and I think this approach can work too. We just need to be careful with nested lambdas and such. I think the algorithm should be something like traversing upwards and replacing each named env with the latest one?

**Comment by scolsen** [comment]
> > Ahhh so that’s the cause of “fixed definition order” I’ve seen this before too.
> > Could we solve this by just setting the parent of the parent env of the closure to the current context env structure at call time?
> 
> I've pondered this some more and I think this approach can work too. We just need to be careful with nested lambdas and such. I think the algorithm should be something like traversing upwards and replacing each named env with the latest one?

That sounds right to me. If we are disciplined about maintaining the env stack well, it should work. The nested lambda case is a bit trickier, but there's probably a clean solution. I think for the general, unnested case we should only store an env that contains a lambda's local defs w/ the lambda, then at call time, lookup first in this lambda env, then in the current context's innerEnv, then in the inner env's parentEnv and so forth. The only env we'd actually store w/ lambdas at creation time is the env containing local bindings in the lambda `let` binds, arguments, etc.

**Comment by eriksvedang** [comment]
@scolsen Do you want to take a stab at this? (or perhas you already have..?) If not, I can do it of course.

**Comment by scolsen** [comment]
Sure thing!--I can probably give it a try this weekend

**Comment by scolsen** [comment]
I need to run tests, but I think I found a simple fix--we define a semigroup instance for `Env` and one for `Ctx` and use this to combine the context enclosed by the closure and the evaluation context during closure evaluation--the semigroup instance is left-biased, so in the case of conflicts between local lambda bindings and global bindings local bindings are preferred.

**Comment by scolsen** [comment]
So, that would be a simple fix, but it seems to cause a hang on `macros.carp`--this hang doesn't occur when firing up the REPL, so I will need to check what precisely is going on.

**Comment by scolsen** [comment]
> So, that would be a simple fix, but it seems to cause a hang on `tests/macros.carp`--this hang doesn't occur when firing up the REPL, so I will need to check what precisely is going on.

fixed!
