### ISSUE TITLE
bug in Array.reduce

### ISSUE THREAD

**Issue by Efimero** [carp-lang/Carp#1105]
Attempting to use the same array that is being reduced from within the lambda in the reduce will copmile and cause a segfault instead of not compiling.

**Comment by TimDeve** [comment]
If you're borrowing/consuming your array in the lambda rather than using a reference to it it's probably #1040

**Comment by Efimero** [comment]
sounds about right

**Comment by TimDeve** [comment]
@eriksvedang Should we close in favor of the other issue then?
