### ISSUE TITLE
Literals inside `match` crash the compiler

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#1113]
When using literals in `match`, the compiler crashes. Consider this program:

```clojure
(defn test [m]
  (match m
     (Maybe.Just 0) (println* "hi")
     _ (println* "bye")))
```

This generates the following error:

```
carp: Can't create binder for non-symbol in 'case' variable match:XObj {xobjObj = Num Int 0, xobjInfo = Just (Info {infoLine = 3, infoColumn = 18, infoFile = "REPL", infoDelete = Set {unSet = fromList []}, infoIdentifier = 7}), xobjTy = Nothing}
CallStack (from HasCallStack):
  error, called at src/InitialTypes.hs:488:42 in CarpHask-0.4.2.0-In3bsPt14LZHMVFTWVtUXQ:InitialTypes
  ```
  
 Ideally, the expander should catch this error before it gets passed to `initialTypes`.
 
 Cheers

**Comment by scolsen** [comment]
Agreed, I think we should also eventually support matching on literals. It shouldn't be too complicated to achieve, and this would give us parity with most other languages that support pattern matching.

**Comment by jacereda** [comment]
Matching on literals could also simplify the AST, no need for `If` since it could just be implemented via matching on `true`/`false`.
