### ISSUE TITLE
Refactor: Make `envUseModules` a Set instead of a list

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#1128]
`envUseModules` is a list of sympaths, but it doesn't make sense to have any duplicates--once one declares a module as `used` a second use does nothing.

It'd be convenient if this invariant was baked into the data structure we used for tracking used modules, as it would simplify our management of them, e.g. 25344e4 resolves a teeny bug that would not have even been possible if we used a data structure like `Set` instead of list

**Comment by eriksvedang** [comment]
Sounds like a great idea!
