### ISSUE TITLE
Carp in Docker

### ISSUE THREAD

**Issue by tedneward** [carp-lang/Carp#113]
Struggled through a LOT of setup/config issues when putting Carp into a Docker image. (I have the Dockerfiles--both the carp image and the haskell one I build that it depends on--in a public Git repo if anyone wants to tell me if/how my config is borked--I'm not really a Haskeller so I'm very ready to admit that what I'm doing here is borked. https://bitbucket.org/TedNeward/Docker.git/carp and https://bitbucket.org/TedNeward/Docker.git/haskell, respectively.)

When I got everything to build, though, and try to run Carp against one of the examples ("basics.carp"), I get an error: hGetContents: invalid argument (invalid byte sequence). No idea how to fix this.

All I *really* want to do is play with Carp for a while, not build it from source--if there's a working binaries image I can grab, I'd do that in a heartbeat, but I don't see one anywhere....?

**Comment by eriksvedang** [comment]
How annoying! I’m not experienced with Docker so no idea what’s going wrong. What kind of system are you? I can put up some macOS binaries for sure.

**Comment by eriksvedang** [comment]
Here's a release, hopefully we can get Linux binaries in there too:
[](https://github.com/carp-lang/Carp/releases/tag/0.0.2)

**Comment by tneward** [comment]
Personally I'd rather figure out how to get it working inside of Docker--much better for experimentation and demos. :-)

**Comment by tneward** [comment]
So, as a start... My base Haskell image does an "apt-get install haskell-platform" (among some other things) to get Haskell into it. I also run the gethaskellstack.org shell install script. But when I git clone this repo, and run "stack build", I get "No compiler found, expected minor version match with ghc-8.0.2 (x86_64) ...". This makes me wonder if I've gotten the right GHC or if it's in the right place, or.... Thoughts?

(If you can help me from the Haskell side, I'll adjust it for Docker as we go, at least as best I can, anyway.)

**Comment by tneward** [comment]
Looks like ubuntu still has GHC 7.10.3 for the haskell-platform. That would explain that. Time to use the generic installer....

**Comment by ephetic** [comment]
Have you try starting with the Haskell base image to avoid that part of the setup mess?
https://hub.docker.com/_/haskell/

**Comment by tneward** [comment]
That's a good idea. :-) I didn't realize there was one.

**Comment by ephetic** [comment]
It's got a somewhat gnarly [Dockerfile](https://github.com/freebroccolo/docker-haskell/blob/ea501abb24273d6dab3121bb6373f6903f1a3c71/8.2/Dockerfile) that sounds like exactly what you were about to embark upon.

**Comment by tneward** [comment]
Yup. And really, the only part that I want different is that I want to drop into a /bin/bash, not a running Haskell REPL, but a small Dockerfile based on that gnarly one should do the trick.

Except... when I use the gnarly Haskell one, I still get a GHC mismatch (8.2.1 vs 8.0.2); it looks/sounds like the Carp build wants that *exact* version of GHC, and isn't happy with a later one. Is that necessary, or can the Carp build work with a later GHC?

**Comment by ephetic** [comment]
while not listed, `docker pull haskell:8.0.2` appears to work.  Not sure how to get info on the image to make sure it's from the same source.

**Comment by tneward** [comment]
Yeah, that'll work, but I'm more curious as to whether Carp requires 8.0.2 exactly--it would seem to me (non-Haskeller, tbh) that it would be less fragile long-term if it wasn't pegged specifically against a particular version of GHC. Yes? No? (This is the part where I'm hoping to learn things. :-) )

**Comment by ephetic** [comment]
@tedneward I got 8.2.1 working.  It's a hack, but perhaps something to work with: 

```Dockerfile
FROM haskell:8.2.1

RUN apt-get update \
  && apt-get install -y clang \
  && apt-get purge -y \
  && rm -rf /var/lib/apt/lists/* 

RUN git clone https://github.com/carp-lang/Carp.git \
  && cd Carp \
  && git checkout ffe9da5482a19df21aac72c6cdbb5e5416611805 \
  # find nightly matching ghc version here: https://www.stackage.org/snapshots
  && sed -i 's/resolver: lts-8.12/resolver: nightly-2017-11-24/g' stack.yaml \
  && stack build \
  && stack install \
  && export PATH=~/.local/bin:$PATH \
  && export CARP_DIR=/Carp/

WORKDIR Carp
CMD for f in test/*.carp ; do carp -b -x $f ; done
```

**Comment by jiegec** [comment]
Perhaps use GHC 8.0.2 with Stackage LTS 9.14 instead?

**Comment by ephetic** [comment]
@jiegec That's what I was getting at -- that `ghc 8.0.2` is fine for now (it builds as-is (`lts-8.12`) for the `haskell:8.0.2` docker image).  Perhaps it's enough to have demonstrated that Carp builds/tests with `ghc 8.2.1` to assuage @tedneward's concern about Carp being pegged to a specific GHC version.

**Comment by eriksvedang** [comment]
Oops, hit the wrong button :)

**Comment by eriksvedang** [comment]
Is there something we can add to the repo to make it easy to use Carp with Docker? I don't use Docker myself so I don't really know what's needed. If nothing more needs to be done and Carp works fine as is, I'll close this issue.

**Comment by tneward** [comment]
I haven't really had much of a chance to pursue this, so unless somebody else is breathing hard to take ownership of Carp-inside-Docker, I'd close the issue.
