### ISSUE TITLE
Dynamic set! cannot reset arguments

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#1144]
Dynamic `set` is unable to reset a variable received as an argument to, for instance, a dynamic function.

Example:

```clojure
(defndynamic x [i]
  (while (/= i 10)
    (set! i (inc i))))
```

Calling `(x 0)` will loop forever. Putting `i` in a `let` instead of using an argument resolves the issue.

Cheers

**Comment by scolsen** [comment]
Oh wow, interesting. Taking a glance at the current code, it's not obvious to me when the arguments for a dynamic function are added to the internal env. An indefinite hang indicates there's likely some kind of conflict w/ env bindings happening somewhere.

**Comment by hellerve** [comment]
Are they added to an internal env at all? Isn’t it rather an explicit env in the chain?

**Comment by scolsen** [comment]
> Are they added to an internal env at all? Isn’t it rather an explicit env in the chain?

That's a definite possibility and would also be the reason it doesn't currently work--but that also wouldn't/shouldn't cause a loop. 

The arglist should eventually be in the internal env at application time (if I'm reading it right, that is, see `apply` in `Eval.hs`). So I'm not sure what precisely is happening here, but something causes a binding lookup loop.

**Comment by hellerve** [comment]
I’m not sure I communicated this very well, so let me be  clear here: `set!` itself doesn’t loop, the code loops because it depends on `set!` working (because it checks the value).

**Comment by scolsen** [comment]
> I’m not sure I communicated this very well, so let me be clear here: `set!` itself doesn’t loop, the code loops because it depends on `set!` working (because it checks the value).

Oh, I see, thanks for the clarification!

**Comment by scolsen** [comment]
When I attempt to run this in the REPL at HEAD I get the following:

```
Expression ((defn /= [a b] (not (= a b))) i 10) has unexpected static call at line 1, column 28 in 'REPL'.
```

**Comment by hellerve** [comment]
Oh, I’m sure, this is based on dynamic `/=`, which I added in a PR. I’m currently working on this, the example I use is:

```clojure
(defndynamic x [y]
  (do (macro-log y) (set! y (+ y 2)) (macro-log y)))
```

which will print `2` twice.

**Comment by scolsen** [comment]
> Oh, I’m sure, this is based on dynamic `/=`, which I added in a PR. I’m currently working on this, the example I use is:
> 
> ```clojure
> (defndynamic x [y]
>   (do (macro-log y) (set! y (+ y 2)) (macro-log y)))
> ```
> 
> which will print `2` twice.

gotcha, thanks!

**Comment by scolsen** [comment]
Oh, this is the same problem we used to have w/ let bindings. The issue is that we add bindings for args as literal values, like we used to do for `let` as well; that is the binding is stored in the env as: `i: XOBJ Int 2 ...` instead of something like `i: ARGBINDING`--and set! doesn't currently match against all the obj literals.
