### ISSUE TITLE
defmodule behaves inconsistently

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#1159]
As discussed on the chat, `defmodule` behaves inconsistently to the rest of the `def` forms. It always gets expanded in macros, whereas others do not. The root of this problem is inconsistencies of how environments are handled.

@scolsen and I agreed to refactor environment handling together, as it seems like an important improvement for the long time maintenance of the project.

We agreed on the following points:
- [ ] Start by refactoring environment handling into a few known-to-be-correct functions.
- [ ] Refactor lookups to be more consistent and to rely on context information only.
- [ ] Eventually and gradually add better, more fine-grained types into the mix to make environments and lookups in general more safe by construction.

Cheers

**Comment by eriksvedang** [comment]
Maybe this can be closed now?

**Comment by hellerve** [comment]
It seems like this works now! For reference, I tested it like this:

```
> (defmacro x [] '(defmodule X (defn y [] 1)))
> X
Can't find symbol 'X' at REPL:1:1.
> (x)
=> (defmodule X (defn y [] 1))
> X
Can't find symbol 'X' at REPL:1:1.
> (eval (x))
> X
=> X
```
