### ISSUE TITLE
Wrap regex library

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#118]
As mentioned in #94, we need to wrap a regex library. I personally would like to wrap something that is as portable as possible. I’ve used `regex.h` in the past, but that isn’t available on Windows (I believe).

Things to consider:
* PCRE would be great
* If we add a library dependency, how should we ship it?

Any preferences/ideas are appreciated.

Cheers

**Comment by eriksvedang** [comment]
Yes, portable is good. Preferably something in C89 in just one or two files that we can plop straight into the `core` directory... I'll look around, but perhaps someone has some suggestions?

**Comment by hellerve** [comment]
For posteriority: we talked about it in the Gitter channel, and settled for Lua-esque regular expressions. I’ll be implementing a simple version ASAP.
