### ISSUE TITLE
Dynamic `set!` when called inside a closure only mutate state inside the closure

### ISSUE THREAD

**Issue by TimDeve** [carp-lang/Carp#1181]
When calling `set!` on a Dynamic global variable defined using `defdynamic` from inside a closure the variable seems mutated only within the scope of closure.
Example:
```clojure
(defdynamic counter 0)

(defndynamic inc-counter [x]
  (do (set! counter (inc counter))
      (macro-log (str "x: " x " counter: " counter))))

(defndynamic return-fn []
 (fn [x] (inc-counter x)))

(defmacro my-macro []
  (do
    (inc-counter 0)
    (map (return-fn) '(1 2 3))))

(my-macro)
```
```
carp -b main.carp
```

Expected output:
```
x: 0 counter: 1
x: 1 counter: 2
x: 2 counter: 3
x: 3 counter: 4
```
Actual output:
```
x: 0 counter: 1
x: 1 counter: 2
x: 2 counter: 2
x: 3 counter: 2
```

**Comment by scolsen** [comment]
This issue is definitely a cousin of #1101

**Comment by scolsen** [comment]
The problem here is the way we combine global environments in closures. Presently, in the case of conflicts, the closure prefers the environment captured at time of definition.

**Comment by scolsen** [comment]
Actually, the mistake was bigger than that. For some reason we weren't returning the newly computed context after evaluating the closure, only its result, meaning any side effects performed within the closure do not happen.

**Comment by scolsen** [comment]
...but of course doing that breaks a bunch of stuff.

**Comment by scolsen** [comment]
Solved it. The problem was actually quite simple. We discarded the context after evaluating the arguments of commands (this probably happened in the recent command refactor) which meant `set!` wasn't getting the latest value of `counter`.

```
x: 0 counter: 1
foo in newCtx in FN(defdynamic foo 1)
(defdynamic foo 1)
x: 1 counter: 2
foo in ctx' in FN(defdynamic foo 2)
foo in newCtx in FN(defdynamic foo 2)
(defdynamic foo 2)
x: 2 counter: 3
foo in ctx' in FN(defdynamic foo 3)
foo in newCtx in FN(defdynamic foo 3)
(defdynamic foo 3)
x: 3 counter: 4
foo in ctx' in FN(defdynamic foo 4)
```

**Comment by TimDeve** [comment]
Thanks Scott that was super quick ❤️
