### ISSUE TITLE
Suggestion: Use Pascal-strings instead of only C-strings

### ISSUE THREAD

**Issue by philix** [carp-lang/Carp#119]
Pascal strings are length-prefixed strings in contrast to Zero-terminated C strings.

https://en.wikipedia.org/wiki/String_(computer_science)#Length-prefixed

They have many advantages over C strings and no drawbacks [1] when you have something like [std::string_view](http://en.cppreference.com/w/cpp/string/basic_string_view) or [Rust's slices](https://doc.rust-lang.org/book/second-edition/ch04-03-slices.html).

[1] One might still say the extra memory overhead for the length field is a problem.

**Comment by eriksvedang** [comment]
(this means static arrays also, they are just not implemented yet)

**Comment by eriksvedang** [comment]
But maybe it can be solved with having a statically allocated struct (with both length and data) for representing string literals?

**Comment by eriksvedang** [comment]
I reverted your patch for now, but will revert my revert when we find a solution.

**Comment by philix** [comment]
I agree with the goal. But for that to work you need more string types in
addition to this one.

**Comment by mkfifo** [comment]
The downside this comment misses is C-interop, currently Carp strings can be passed to C functions (even to be modified) without an issue.

Switching to Pascal style would require every Carp->C->Carp to 'fixup' any lengths, and missing a length fixup could result in very subtle bugs.

**Comment by philix** [comment]
The downside exists only if you consider the ability to mutate the buffer
as if it was a C string an advantage. :)

**Comment by mkfifo** [comment]
@philix one of the goals of Carp is "Straightforward integration with existing C code".

**Comment by hellerve** [comment]
Somewhat relatedly, I started working on a [module for UTF8 strings](https://github.com/hellerve/utf8.carp). It is written in pure Carp and uses an array of runes under the hood, and as such has a length property associated with it. It also is easily convertable to and from regular old Carp strings.

Once there are more functions implemented in it, this might be close to what @philix wants—with some added UTF8 goodness—, albeit as a third-party library.

**Comment by BitPuffin** [comment]
You could easily achieve easy integration with C code by using something like a fat pointer. So you would have memory that looks like this:

```
|--------+------------------------|
| size_t | null terminated string |
|--------+------------------------|
|        ^                        |
```

The `^` referring to what the string pointer value actually points to. And to fetch the size data you just use pointer arithmetic to move a size_t length "back" from the start of the pointer. So you'd initialize this by allocating a struct (size_t, char*) either with malloc or some static memory meme and then just set the pointer offset.

**Comment by hellerve** [comment]
@BitPuffin Unless I’m missing something, this means that we’d have to emit special code to interface with C functions, i.e. code that moves the pointer past that offset, right? I’m asking this because “glue code”, even compiler-generated, is an explicit anti-goal of Carp. Calling C functions should “just work”. Of course I might misunderstand you, though?

**Comment by BitPuffin** [comment]
@hellerve No when calling a C function the emitted code would simply pass the string as is. It would be when doing operations from within Carp like getting string length that there would be some code for pointer arithmetic to dereference the length.

**Comment by hellerve** [comment]
Ah, that makes sense! Very clever! (Also thanks for clarifying!)

**Comment by chrisosaurus** [comment]
@BitPuffin If you allow the C code to mutate the length of the string then you would need to make sure to maintain the carp length after the call to the C code, see my earlier comment [1].

[1] https://github.com/carp-lang/Carp/issues/119#issuecomment-390453994

**Comment by BitPuffin** [comment]
@chrisosaurus Yeah you're right, didn't really consider that :«

**Comment by eriksvedang** [comment]
I think that we're kind of commited to using C strings for now. Perhaps we will add a more advanced string type later on but I'll close this for now.
