### ISSUE TITLE
Auto completion in modules are broken

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#1224]
To reproduce, in the REPL, type:

`Array.` and then tab. You should get the functions in the Array module but instead you get nothing.

**Comment by scolsen** [comment]
Likely some lookup call just needs to change. While trying this out, I also ran into this which is kind of funny:

```clojure
鲤 + <press-tab>
+  +  +  +  +  +  +  +  +  +  +  +  +  +
鲤 +
```

**Comment by scolsen** [comment]
#1225 has a fix.
