### ISSUE TITLE
Calling functions in the REPL is broken

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#1237]
```
鲤 (defn f [] 123)
鲤 (f)
I did not understand the form `((defn f [] 123))` at REPL:1:2.

Traceback:
  (f) at REPL:1:1.

```

**Comment by eriksvedang** [comment]
Idea: we could add a test (for output) that does some REPL interaction like this

**Comment by scolsen** [comment]
oops, sorry about that! #1238 has a fix--this stemmed from a small but important difference between the way we resolve lists and symbols in the head of application `(x args)` forms. Additionally, the evaluator was missing a general pattern case we needed to support this. Should be good now.
