### ISSUE TITLE
returning generic (?) function from main causes linker errors

### ISSUE THREAD

**Issue by guberathome** [carp-lang/Carp#1246]
Use this to reproduce the problem:
```
(defmodule NewSystem
  (deftemplate exit (Fn [Int] a) "$a $NAME(int code)" "$DECL { exit(code); }"))

(defn abort [error-code message]
  (do
    (IO.errorln message)
  error-code ))
(defn finish [message]
  (do
    (IO.println message)
  0 ))

(defn process [s1 s2]
  (if (String.= s1 s2)
    (abort 2 "come on, those parameters should not match!")
    (finish  "After lenghty computation we have reached a verdict...") ))

(defn main []
 ; (ignore (the Int
   (NewSystem.exit
    (let [ args (Int.- (StaticArray.length &System.args) 1) ]    ; 1st argument is executable!
    (if (not (Int.= 2 args))
      (abort 1 &(fmt "expecting exactly 2 arguments (got %d)." args))
      (process (StaticArray.unsafe-nth &System.args 1) (StaticArray.unsafe-nth &System.args 2)) ))))
  ; ))
 ```
 Here's the error output on Windows using gcc:
 ```
D:/.../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x2e): undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
carp: callCommand: gcc  -o out\Untitled -I D:\Tools\p\carp/core/  -D_CRT_SECURE_NO_WARNINGS out\main.c (exit 1): failed
 ```

**Comment by TimDeve** [comment]
For context the linker error comes from the fact we don't emit `main` at all if its return type is generic (woops 🙂). It happens on all platform.

**Comment by guberathome** [comment]
I'm fine with solving this problem "by documentation". :-)

**Comment by scolsen** [comment]
> For context the linker error comes from the fact we don't emit main at all if its return type is generic (woops 🙂). It happens on all platforms.

Ah, sounds like a bug. I think we should (and I thought we used to?) throw an error if main does not return `Int`.

**Comment by hellerve** [comment]
> > For context the linker error comes from the fact we don't emit main at all if its return type is generic (woops 🙂). It happens on all platforms.
> 
> Ah, sounds like a bug. I think we should (and I thought we used to?) throw an error if main does not return `Int`.

The error you’re looking for is `MainCanOnlyReturnUnitOrInt`—very descriptive name. The problem is that we check for this error during concretization—if the function is generic until the very end, noone will check for it.

**Comment by hellerve** [comment]
I’m guessing `commandBuild` should check for this, since it also checks whether it should build an executable or shared library based on whether `main` is bound.

**Comment by scolsen** [comment]
> I’m guessing `commandBuild` should check for this, since it also checks whether it should build an executable or shared library based on whether `main` is bound.

Sounds good to me!
