### ISSUE TITLE
Rewrite more of the template functions using plain Carp.

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#125]
Now when we have interfaces it should be possible to rewrite some (most) of the Array functions using plain carp. This will clean up the compiler and make it less likely that a memory error slips in through the template generated C code.

**Comment by hellerve** [comment]
Which functions are left to be done? I guess `filter` (but it does a `realloc`)  and `sort` (but it uses `sizeof`). Thus I think we can close this for now?

**Comment by eriksvedang** [comment]
Yes!
