### ISSUE TITLE
Can't recognize CARP_DIR under fish

### ISSUE THREAD

**Issue by glyh** [carp-lang/Carp#1250]
I'm trying the fish command: 

```fish
set -g CARP_DIR ~/.carp/
```

which doesn't work, and the REPL warns me that it can't find envrionment variable. 

However the bash command works fine, and the env command here, also works fine: 
```fish
env CARP_DIR=/home/xxx/.carp carp
```

This might be a bug in Carp

**Comment by eriksvedang** [comment]
Huh, strange!

We get the CARP_DIR variable from `SystemEnvironment.getEnvironment` (in Haskell, see /app/Main.hs)

If you try getting the variable in the Carp repl, using `(get-env "CARP_DIR")`, does it work then? It uses a slightly different method (see /src/Command.hs).

**Comment by guberathome** [comment]
Could you please start Carp with the ```---no-core``` flag and try some environment variables, that should be there?
E.g. on Windows:
```
(get-env "TEMP")
(get-env "CARP_DIR")
```

or in Linux
```
(get-env "USER")
(get-env "CARP_DIR")
```
Of course these values are read slightly differently, as Eric explained, but even so...

**Comment by hellerve** [comment]
If you want to export and set an environment variable in Fish, AFAIK you need to use `-x` in the `set` command, no? Or, more succinctly, does `set -gx CARP_DIR ~/.carp/` work? (Note: Not a fish user)

**Comment by glyh** [comment]
That's seems to be my bad that I didn't add flags to let it export to child processes, and  @hellerve 's solution works for me.  Sorry for borthering...

**Comment by hellerve** [comment]
@glyh No worries, it happens!
