### ISSUE TITLE
Deleters get half emitted in some generic cases

### ISSUE THREAD

**Issue by TimDeve** [carp-lang/Carp#1261]
It seems if you use a generic function in a function and then never actually call that function some of the deleter function might not get emitted properly, in my case it's linked to the generic functions related to `Map`.

Example:
```clojure
(deftype AType [s String])

(defn weird [m]
   (the (Map String AType) m))

(defn main []
 (println* "Doesn't use any of the above"))
 ``` 
 Results in this error at C compilation:
 ```
 out/main.c:4457:9: error: implicit declaration of function 'Bucket_delete__String_AType' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        Bucket_delete__String_AType(((Bucket__String_AType*)a.data)[i]);
```

Looking at `main.c` `Bucket_delete__String_AType` never get emitted but is called by `Bucket_delete__String_AType`.

Maybe something to do with how we emit Array deleters?

**Comment by eriksvedang** [comment]
Is this a new bug? (did the code work before?) There might have been a regression in some recent stuff I added, though I'm not sure.

**Comment by eriksvedang** [comment]
The simplest theory why this happens would be that there's a missing call to concretizeType in the `the` case in concretize. But maybe it happened related to some other form too?

**Comment by TimDeve** [comment]
Yes that's a recent break I believe.

**Comment by eriksvedang** [comment]
OK, this commit is the one that ruined it... https://github.com/carp-lang/Carp/commit/861ba26f52c01332491686c330d9c55ef66226fd 

Sorry about that...

@hellerve had suspicions about it and was right :)

I'll think about if I can fix this in a better way or if we just need to revert my changes. This test case is great, so I'll be sure to add it to the regression tests at the same time!
