### ISSUE TITLE
Feedback wanted – Docs and type signatures

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#131]
I've been pondering a good way to annotate top level forms with documentation and (optional) type signatures.

Here are some suggestion:

## Style A
A `doc` and `sig` command.

```text
(doc average "Calculates the average value of an Array of double:s.")
(sig average (λ [(Array Double)] Double))
(defn average [nums]
  <implementation>)
```

## Style B
Reader macros.

```text
^doc "Calculates the average value of an Array of double:s."
^sig (λ [(Array Double)] Double)
(defn average [nums]
  <implementation>)
```

They would probably expand to something like this:
```text
(doc "Calculates the average value of an Array of double:s."
     (sig (λ [(Array Double)] Double)
          (defn average [nums]
            <implementation>)))
```

## Style C
More flexible versions of `def`/`defn`.

```text
(defn average [nums]
  (λ [(Array Double)] Double)
  "Calculates the average value of an Array of double:s."
  <implementation>)
```

## Any better ideas?
I think all the versions above are passable but not immediately attractive. Does anyone have other suggestions to take into account?

**Comment by Nananas** [comment]
What about separating documentation and type signatures?

## Style D
Slightly modified **style c**.
```
;;; "Calculates the average value of an Array of double:s."
(defn average [nums]
  (:: [(Array Double)] Double)
  <implementation>)
```

Or any variation of doc/sig syntax.

**Comment by porky11** [comment]
I prefer Style A, because then it should be easy to implement style B and C oneself

**Comment by hellerve** [comment]
I have strong opinions against both C and D, because they clutter up my definitions. I don’t like style B all that much, because style A looks the most consistent with a nice Lisp syntax.

How would one retrieve docstrings? I’d love to autogenerate some docs for my packages...

**Comment by evuez** [comment]
Style C and D are harder to read imho, style A and B are both easier to read but as pointed out by @hellerve A looks Lispier. 

A and B make me think of Elixir's @doc and @spec annotations, and I know I have a better time reading these rather than reading say Python doc where it's in the body of the functions. Not sure if it makes sense to compare these two with any Lisp-like language though.

**Comment by eriksvedang** [comment]
Thanks for the feedback everyone! I'll mull this over a bit. It will definitely be possible to access this information via dynamic functions. The compiler will also have a built-in doc exporter that can be invoked with a simple command to make it very easy to generate docs for libraries, both your own and others.

**Comment by devn** [comment]
Style C.

**Comment by yawaramin** [comment]
I'd say we can borrow some ideas from Common Lisp, which has type declarations. I like the idea of separating out declarations from the implementation in the general case. This keeps the implementations succinct. But we also need a way to annotate an expression with a given type, to enforce our idea of what the type should be.

For declarations we can borrow from CL's `declare`, `type`, and `ftype`: http://clhs.lisp.se/Body/d_ftype.htm#ftype

```clojure
(declare
  (type (function [(Array Double)] Double) average
    "Calculates the average.")
  (type (function [(Array Double)] Double) min
    "Calculates the minimum.")
  (type (function [(Array Double)] Double) max
    "Calculates the maximum."))
```

For type annotations we can simply reuse the above `(type ...)` form). Without `declare`, `type` can annotate a given expression with the given type, with an optional docstring.

The benefit of type declaration is that it also enables forward lookup (if it is present). Although I don't know Carp's design in that respect, i.e. does it do forward lookups already like Haskell, or does it require all names to be declared before use like OCaml.

**Comment by eriksvedang** [comment]
@yawaramin That looks pretty cool, I admit. It would be very similar to Style A though, just a bit more principled that you put everything at the top of the file. The fact that you can add both a type signature and a comment at the same time is pretty neat since it saves some noise.

What you're saying about forward lookup is true, it's a single pass compiler so it needs declarations for mutually recursive functions and the like.

Thanks for the input!

**Comment by Gozala** [comment]
I would suggest update of `the` form and swapping it's arguments around with an option to add docstring:

```lisp
;; Without comment string
(the average (λ [(Array Double)] Double))

(defn average [nums]
  <implementation>)

;; With comment string
(the avarage
  "Calculates the average value of an Array of double:s."
  (λ [(Array Double)] Double))

(defn average [nums]
  <implementation>)
```

**Comment by Gozala** [comment]
If overloading `the` (or introduction of it with different name say `type`) does not seem like good option my vote would be with **Style A** as I very much value ability to separate type annotations from implementation.

**Comment by warlord500** [comment]
my preferences would be style A then B then D then C.
A because not extra nesting, (can write signature at top level)
B for same reason.(less lispy)
D goes before C because in many languages that is more common!
and i really dont like C because that the general style other languages go with

**Comment by eriksvedang** [comment]
Style A it is, coming up soon!

**Comment by Gozala** [comment]
@eriksvedang how is it going to look for inner functions (lambad & closures) ?

**Comment by eriksvedang** [comment]
They will use the current `(the <type> <expr>)` syntax that's already implemented.

**Comment by eriksvedang** [comment]
This is in now! There are still bugs and features missing but the general idea works so I’ll close this.
