### ISSUE TITLE
Unknown warning option '-Wno-unused-but-set-variable'

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#1357]
The recently added `-Wno-unused-but-set-variable` option isn't recognized by my `clang` compiler. When I attempt to build carp code, I get the following:

```
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
```

I'm running `Apple clang version 11.0.0 (clang-1100.0.33.16)`

Perhaps this option was added in a later version of clang?

**Comment by eriksvedang** [comment]
Oh, sorry about that. I had to add it to compile on a machine with a recent clang version and didn't think it through. Let's reverse the commit and come up with a better solution.

**Comment by eriksvedang** [comment]
Should be fixed now. Sorry again.

**Comment by scolsen** [comment]
No problem, thanks!
