### ISSUE TITLE
Problem calling (nanotime)

### ISSUE THREAD

**Issue by Tyruiop** [carp-lang/Carp#1363]
Hi,

apologies if it's a silly question, but when I run

```
> (use System)
> (nanotime)
1639149525140771584
> (time)
1639149528
> (let [a (nanotime)] a)
```
I get

```I did not understand the form `(external System.nanotime (Fn [] Long))` at ~/.local/bin/carp-v0.5.3-x86_64-linux/core/System.carp:12:22.```

am I doing something wrong or is it a bug?

**Comment by scolsen** [comment]
hmmm seems like a bug, but I can't reproduce it--when I run exactly that code in the repl I don't get the error:

```
鲤 (use System)
鲤 (nanotime)
1639152484817188096
鲤 (time)
1639152487
鲤 (let [a (nanotime)] a)
1639152495376421888
```

**Comment by eriksvedang** [comment]
I can confirm this works for me too (on MacOS).

**Comment by Tyruiop** [comment]
I am using the release 0.5.3 on Archlinux, I'll try with a fresh build. The call works when I use `carp ex.carp -x`

```(use System)

(defn main []

(do
(let [a (nanotime)
      ar (Result.unsafe-from-success (Array.range 0 30000000 1))
      b (nanotime)
      total (Array.sum &ar)
      c (nanotime)]
  (IO.println &(String.join " " &[(Long.prn (- c a)) (Long.prn (- c b))])))
  0))```

**Comment by eriksvedang** [comment]
Ok might be an issue they was fixed after the release. Can you build the latest version yourself? Or I can cut a new release.

**Comment by Tyruiop** [comment]
I'll try to build the latest version, I'll let you know how it goes / if the issue is still there

**Comment by Tyruiop** [comment]
It works with the current `master` branch :+1:
