### ISSUE TITLE
Compiling without core library - modularization of core library?

### ISSUE THREAD

**Issue by NOP0** [carp-lang/Carp#144]
All the core registered c functions of carp are defined in core.h. That means it is not possible to compile a program which only uses parts of core.h by using the --no-core compiler flag and then loading individual carp modules.

A possible solution could be to split core.h into different modules, i.e. int_core.h for functions registered in Int.carp and so on. (Somehow the necessary stdlib headers would need to be included also) What are some good ways achieve a modular system?

**Comment by eriksvedang** [comment]
I think this is a good idea, it will probably be easier to get an overview of all the functions if they're split up a bit. Hopefully it will help when porting to other platforms too, like Windows.

**Comment by eriksvedang** [comment]
You'd still need some IFDEF:s though, right? For the special int functions etc.

**Comment by NOP0** [comment]
I would think so for the compiler builtin functions, or else these needs to be collected into a separate module. I'm not 100% sure whats the best practical solution is...

**Comment by eriksvedang** [comment]
A few ifdefs are OK I think, as long as we can limit the use of them as much as possible via modules.

**Comment by hellerve** [comment]
What’s the status on this? Have we settled on a strategy yet?

**Comment by eriksvedang** [comment]
The idea is to split it up, just no one have taken the time to do so.

**Comment by hellerve** [comment]
Dropped the ball on this. I worked on it for a while, but then got sidetracked. Sorry about that!

**Comment by hellerve** [comment]
[This is the branch](https://github.com/hellerve/carp/tree/split-core), for the nosy.

**Comment by eriksvedang** [comment]
Oh great, I'm currently playing around with a 6502 assembly compiler and could really use it, is it ready for PR?

**Comment by hellerve** [comment]
Sadly not, but I can continue work to work on it!

**Comment by eriksvedang** [comment]
If you have the time, that'd be rad!
