### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [carp-lang/Carp#17]
The functions "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html)" and "[printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html)" do not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).
I guess that a different program design will be needed for your function "[signal_handler](https://github.com/eriksvedang/Carp/blob/27e38fe037adbb0f329c74ebeda24714b8944d64/src/main.c#L10/scanmem.c#L64)".

**Comment by eriksvedang** [comment]
Yeah, it's a pretty big hack that whole thing I guess... Do you have any idea of how to do it in a safer way? The basic idea is that simple errors in the compiled C code shouldn't have to crash the REPL (which the current solution manages to solve, at least on my machine).

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "Wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")

**Comment by eriksvedang** [comment]
Yes, I'll read up on this so that I can design a better solution. Thanks for the links!
