### ISSUE TITLE
May be something You'll be interesting in researching

### ISSUE THREAD

**Issue by JAremko** [carp-lang/Carp#178]
## unikernel
Have you considered Carp as a first unikernel friendly LISP? Unikernel applications have to be fast to restart, have low memory profile and usually they are "single threade". It seems like Carp can provide it all.

Links for research
https://github.com/rumpkernel/rumprun/
https://github.com/solo-io/unik

## WebAssembly
LISPs like Clojure can't target WebAssembly because they need GC and WebAssembly still lacks it.
Carp can use LLVM to compile into WebAssembly.

## Scala's dependent types paper [1](http://lampwww.epfl.ch/~amin/dot/fool.pdf) [2](https://www.researchgate.net/publication/309328662_Type_soundness_for_dependent_object_types_DOT)

Not sure about that one but You might be interested since Carp also has type inference

**Comment by bjorn3** [comment]
+1 for WebAssembly

**Comment by eriksvedang** [comment]
These are all neat ideas. Unikernels seem really cool but it's not my expertise, so someone else will have to play around with that. The language should be a good fit for it though! If you want to experiment with Carp+WASM I can assist in the Gitter channel. Writing another emitter shouldn't be too hard, the current one is fairly small and straight forward (Emit.hs). Or you could use the emitted C code and pipe it into the web assembly compiler. Regarding dependent types I have some ideas for adding a little bit of support for it (think fixed size arrays), but the design of Carp is meant to be simple, so it definitely won't be another Idris / Agda.

**Comment by hellerve** [comment]
Having played around a bit with compiling Carp to Webassembly today, I can say that we are able to compile it just fine. We’ll have to change the emitter some to be able to achieve JS interoperability (which requires some assistance to emscripten through annotations), but that should be fairly simple to do. I’ll keep y’all posted.

**Comment by hellerve** [comment]
A quick note here: I haven’t worked on this since my initial explorations, so don’t expect me to come up with anything quickly. What I can say is that emcc works perfectly as a C compiler for our emitted code.

As I said earlier, it’s missing the annotations, though, and I need to read up on that and then find a good way to optionally make the emitter spit those out, too. I’m not sure how to do that gracefully yet.

I do not see any major roadblocks coming up, though, which is either very good or very bad!

**Comment by hellerve** [comment]
Another note on WASM: @JAremko has been so kind to provide us with an Emscripten-ready Dockerfile that you can look at on [Github](https://github.com/carp-lang/carp-docker) or [Dockerhub](https://hub.docker.com/r/carplang/carp).
