### ISSUE TITLE
are you guys planning to support enums?

### ISSUE THREAD

**Issue by warlord500** [carp-lang/Carp#193]
in rust and other languages, have support for enumerations. which allows for creating types that 
must match some planned types. 

some syntax suggestions 
no extra data -- nil  or unit value
not sure what might be used other wise.
``
(defenum months [ january nil 
                               febuary  nil
                               march    nil
                                april     nil ]

;dont know what you guys use for generics
(defenum option [ Some T 
                               None  nil ]
``

**Comment by eriksvedang** [comment]
Hello, yes enums / sum types are coming. The syntax isn’t finished but thanks for your input!
