### ISSUE TITLE
Can't read /proc/*

### ISSUE THREAD

**Issue by goodmind** [carp-lang/Carp#202]
`IO.read-file` can't read files in `procfs` filesystem on Linux

```clojure
(use IO)
(defn main []
  (println &(read-file "/proc/cpuinfo")))
```

**Comment by eriksvedang** [comment]
IO.read-file uses the C function `fopen` from stdio.h, so it seems strange that this wouldn't work? Have you opened other files on your system with the same call (from a Carp program)?

**Comment by goodmind** [comment]
@eriksvedang kernel reports length of files in `/proc` as 0. 
Other files are working
