### ISSUE TITLE
Tests should also check output

### ISSUE THREAD

**Issue by mkfifo** [carp-lang/Carp#216]
Ideally we should have a suite of tests where each is a pair of `foo.carp` (input program) and `foo.out.expected` (expected stdout output) to be compared against

we can then have these run within each Travis test, so we can detect unexpected ouput changes

**Comment by hellerve** [comment]
How would this complement the unit tests? Would those be for testing the basic language features with `examples`?

The unit tests themselves do check the output of various things (like stringification) already. I’m not saying that this is thus invalid, I just want to get a feel of what the use case is.

**Comment by mkfifo** [comment]
Generally unit tests test a unit in isolation, this is often a single function/feature, testing input against output over a set of cases. For this I was thinking more integration or system tests.

I was thinking of including a set of decent sized programs and testing these against their expected output as a whole, a good start would be examples/*.carp and test/*.carp.

The idea of these is to form a set of larger tests which try to capture a large cunk of the Carp sytem and runtime in order to capture regressions.

These also begin to form some kind of documentation about the system.



For my toy language Icarus I had:

* 'unit tests' [1] written in C (the host language) to test individual units of the language implementation
* 'milestone' tests [2] each covering one new feature more than the previous run and trying to test this feature end-to-end in isolation
* 'custom' tests [3] [4] [5] [6] which try to capture a wide array of small programs

both 'milestones' and my 'custom' tests are testing the output, some of my custom tests also test the various intermediate forms and compilation targets (AST, IR [7], Bytecode [8], C [9], ...).

These tests meant that whenever I had a regression I was able to quickly narrow it down to the exact phase it happened in, as well as giving me a large set of examples of where it fails/pases.

These kinds of tests only make sense if your language syntax and behaviour is reasonably fixed, adding new features is possible, but large-scale changes means you have lots of tests to also update.

[1] https://github.com/mkfifo/icarus/tree/master/t/unit 
[2] https://github.com/mkfifo/icarus/tree/master/t/milestones
[3] https://github.com/mkfifo/icarus/tree/master/t/custom
[4] https://github.com/mkfifo/icarus/blob/master/t/custom/test_generics_progress.pl
[5] https://github.com/mkfifo/icarus/blob/master/t/custom/test_backend_pancake_end_to_end_output_only.pl
[6] https://github.com/mkfifo/icarus/blob/master/t/custom/test_backend_2c_end_to_end_output_only.pl
[7] https://github.com/mkfifo/icarus/blob/master/t/custom/test_transform_simple.pl#L10
[8] https://github.com/mkfifo/icarus/blob/master/t/custom/test_backend_pancake_end_to_end.pl#L51
[9] https://github.com/mkfifo/icarus/blob/master/t/custom/test_backend_2c_end_to_end.pl#L24

**Comment by hellerve** [comment]
Sounds good to me! We already have a decently usable unit testing framework that is used to test most of the standard modules, but it would be good if we could actually test some larger scale behaviour.

Most of the test setup is a bit wonky, in that the tests are mostly smoke tests (we test a few inputs to a function to see whether it seems about right). I’d definitely like this to get better.

What you’re describing sounds complementarily useful!

PS: If I had infinite time and resources, I’d also check out whether I could write a decent property-based testing framework in Carp (with shrinking and all of the fancy bells and whistles).

**Comment by eriksvedang** [comment]
Can such "diff" tests be run locally too? What program is used to put them together?

**Comment by hellerve** [comment]
Running these tests locally should not be a problem. I’d be happy to write two scripts:
- one being a “recorder”: you give it a program, it records the output and saves it to a file. This is the expected output.
- the other being a “checker”: you give it the program, it checks the expected output file and diffs the outputs.

This should be completely doable locally.

**Comment by hellerve** [comment]
Also, sorry @mkfifo if I stole your thunder there. If you want to do any of those or meant to do something entirely different, that’s of course at your own discretion! :)

**Comment by mkfifo** [comment]
@hellerve no not at all, please if you have the time :)

A recorder and checker sound perfect.
Note that a minimal recorder could just be piping the output to a file.
A minimal checker could just be to run the program again, pipe output to a new file, and then diff them (using diff(1)), adding helpful output in the case of a failure.

In Icarus my 'milestone testing' fundamentally comes down to a perl string comparison between expected and actual result.

@eriksvedang I think they have to be able to be run locally to be useful, and then travis will also run them (travis should also be able to run them automatically against all pull requests, so you can see a pull request doesn't cause a regression before you accept it in).

**Comment by hellerve** [comment]
Can this be closed after merging #220?

**Comment by mkfifo** [comment]
@hellerve thaks for that, I think we can close this now.
