### ISSUE TITLE
possible bytecode refactor

### ISSUE THREAD

**Issue by mkfifo** [carp-lang/Carp#26]
looking at src/bytecode.c I see

```
// 'a' push lambda <literal>                                                    
// 'c' call <argcount>                                                          
// 'd' def <literal>                                                            
// 'e' discard                                                                  
// 'g' catch                                                                    
// 'i' jump if false                                                            
// 'j' jump (no matter what)                                                    
// 'l' push <literal>                                                           
// 'n' not                                                                      
// 'o' do                                                                       
// 'p' push nil                                                                 
// 'r' reset!                                                                   
// 't' let                                                                      
// 'u' end of function (process->function_trace_pos--)                          
// 'v' pop let scope                                                            
// 'x' direct lookup                                                            
// 'y' lookup <literal>                                                         
// 'q' stop                                                                     
```

and then throughout the code

```
  bytecodeObj->bytecode[*position] = 'a';    
```

would it be beneficial to refactor this?

we could represent the bytecode as an enum, that way instead of using the literal 'a' you could use `lambda` (we could even set the enum values to match the letters, so it is still printable).

we could instead use defines.

This could also just be busy work, what are your thoughts?

**Comment by mkfifo** [comment]
The obvious potential advantages with using an enum are 1) readability, 2) type safety (cannot accidentally use a character that doesn't exist, if you refactor you know you haven't missed a spot, etc.).

**Comment by eriksvedang** [comment]
I think enums take up sizeof(int), right?

**Comment by simonhaines** [comment]
GCC has -fshort-enums  but there are caveats: https://oroboro.com/short-enum/

**Comment by mkfifo** [comment]
@eriksvedang yes, fair point, enum size is implementation defined but on my system under gcc and clang it is `sizeof(int)`

```
C99, 6.7.2.2
Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type. The choice of type is implementation-defined,108) but shall be capable of representing the values of all the members of the enumeration.

Footnote 108 adds

An implementation may delay the choice of which integer type until all enumeration constants have been seen.
```

But in practice this is usually sizeof(int)

```
$ cat t.c
#include <stdio.h>

enum foo {
  a,
  b,
  c
};

int main(void){
  printf("%lu\n", sizeof(enum foo));
}


$ gcc t.c
$ ./a.out 
4

$ gcc t.c -fshort-enums
$ ./a.out 
1

$ clang-3.5 t.c
$ ./a.out 
4

$ clang-3.5 t.c -fshort-enums
$ ./a.out 
1
```

But I wouldn't recommend the use of the `-fshort-enums`, the link above is a good intro as to why.

Since space is a concern happy to drop this.

**Comment by simonhaines** [comment]
However, by using 0-indexed bytecodes (either byte-sized enums or `#define` values), you may find significant performance improvements in the bytecode dispatcher (eval?) by using computed gotos in a jump vector: https://gcc.gnu.org/onlinedocs/gcc-3.1/gcc/Labels-as-Values.html

Worth noting is the trade-off between 'fat opcodes' and the potential for compiler optimisation passes (possibly in a JIT context), which may not apply to Carp. There has been much hand-wringing recently on this topic in regard to Python's performance.

**Comment by mkfifo** [comment]
If enums take up too much size, I do think `#define` would be a good half-way.

Explicit names rather than character constants scattered around.

The ability to jump by them would be a bonus, if so you can always define a `print_bytecode(...)` method that converts them from the internal representation into a nice external character representation.

**Comment by mkfifo** [comment]
Worth mentioning that the above 'labels as values' is a GNU C extension, so is not portable.

It Does however seem to be supported in modern clang.

**Comment by eriksvedang** [comment]
Thanks for the suggestions guys! I did try to optimise the old interpreter using computed goto:s, with no effect whatsoever. So I thought maybe skipping them for now is good, so that the Visual Studio compiler can handle the code. Might be worth adding it later though.

Regarding #defines over the chars – yes that is a good solution, feel free to add that if you want to :) I have been meaning to implement a ```print_bytecode(...)``` function, primarily because the ints stored in the bytecode messes up the "print bytecodes as strings" solution which I use now.
