### ISSUE TITLE
Build-Error on new installation on macOS 10.13.6 

### ISSUE THREAD

**Issue by g3ntleman** [carp-lang/Carp#277]
After I cloned the repo as told on the installation page, I'm getting..

theisen@Colin [/Users/theisen/Projects/Carp] > stack build
Downloaded lts-11.12 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags: failed to parse field packages: failed to parse field constraints: failed to parse field flags: Invalid flag name: \"bytestring--lt-0_10_4\""
theisen@Colin [/Users/theisen/Projects/Carp] > 

I'm somewhat stuck as I do not know anything about the data being parsed there.

**Comment by hellerve** [comment]
That looks like an error in an upstream package. We don’t require bytestring or cassava directly, so it must be a bit higher up in the food chain.

I will try to reproduce in the coming days, but I doubt that we can do much about it! Sorry I don’t have better news for you.

Cheers

**Comment by hellerve** [comment]
I just removed my `.stack` directory and reinstalled from scratch, using the same LTS build plan you were using. I’m also on macOS 10.13.6, and was able to install it just fine.

I’m not terribly knowledgeable in how to debug this. Is the output you posted the complete output of the call?

Also, [this stack issue](https://github.com/commercialhaskell/stack/issues/3686) seems related. What version of stack are you using (I’m on 1.7.1, FWIW). Maybe you can try running `stack upgrade` and see whether that helps?

**Comment by g3ntleman** [comment]
Thanks for testing on your side. I did more diagnosis of my environment and found the culprit: An old stack version 1.2.1 in ~/bin/stack 
After deleting it, everything went normal. Looking forward to trying out Carp!

**Comment by hellerve** [comment]
Perfect, glad to know this is resolved!
