### ISSUE TITLE
Starting carp from the terminal messes up the terminal colours

### ISSUE THREAD

**Issue by timmyjose** [carp-lang/Carp#283]
I tried invoking `carp` from my terminal (iTerm2 to be precise), and this is what happened:

<img width="819" alt="screen shot 2018-08-28 at 6 38 52 pm" src="https://user-images.githubusercontent.com/2051158/44725067-153e1d80-aaf2-11e8-8c29-acae727563b1.png">

First of all, with my default White on Black profile, the content is almost illegible, and secondly, even after exiting the program, the colour profile still remained till some random commands such as `ls -la` cleared that up.

**Comment by hellerve** [comment]
This is due to the ANSI escape codes we use to set the colors. Usually, these should be resetted after you exit, but I’m using a setup that makes use of these escape codes in my prompt anyway.

I’ll try to reproduce and fix this ASAP! Thanks for reporting!

**Comment by hellerve** [comment]
@eriksvedang I’d suggest we move away from the grey and use the standard foreground color instead, what do you think?

**Comment by eriksvedang** [comment]
@hellerve Yes, sounds good. Can you do that?

**Comment by hellerve** [comment]
@eriksvedang Done!
