### ISSUE TITLE
IO.read->EOF segfaults if the file does not exist

### ISSUE THREAD

**Issue by sacredbirdman** [carp-lang/Carp#286]
Minimal crashing example:
```
(defn main []
  (println* (IO.read->EOF "foobar")))
```

**Comment by eriksvedang** [comment]
I guess we'll leave this open until we have some decent way of reporting errors :)

**Comment by eriksvedang** [comment]
This should be possible to fix now that we have a Result type?!

**Comment by hellerve** [comment]
Done!

**Comment by hellerve** [comment]
Just as a word of advice, though: I strongly suggest using the [`file` package](https://github.com/carpentry-org/file); it’s easier to use and has those safety guarantees as well!
