### ISSUE TITLE
Sum types and error / NULL -handling

### ISSUE THREAD

**Issue by sacredbirdman** [carp-lang/Carp#287]
Carp doesn't have sum types / tagged unions etc. yet but I think it would be good idea to discuss if the standard way of handling errors will be based on them and whether we could use them to abolish most/all(?) usage of null on the Carp-side of things. Should we have things like Option a = Some a | Nothing or Result a = a | Error String/code in the standard library?

It would be worth pondering if we could use for example the Option-type to handle NULLs in the C-interface: autoconvert between Nothing(Carp) <-> NULL(C) so the resulting NULLs would need to be handled.

**Comment by hellerve** [comment]
I’d love that and have already prepared branches on my fork of Carp to make `Either` and `Maybe` standard types (those are equivalent to `Option` and `Result`)!

**Comment by eriksvedang** [comment]
Yes, the plan is to have sum types (coming soon, after lambdas and lifetimes are done) – and to use to those for basically all error handling needs.

Autoconversion between NULL <-> Maybe is something the could be really cool and useful. If it can be done well, I'm all for it. My fear is that it will make it hard to interop with certain C-api:s that make use of `void*` and NULL in "interesting" ways. In that case we might be better off with keeping the simpler type in the api and wrap the access to it in Carp functions that return Maybe / Either on a case by case basis.
