### ISSUE TITLE
Dependent Types

### ISSUE THREAD

**Issue by Superpat** [carp-lang/Carp#303]
Are dependent types a potential goal for this project? 

Relevant links:
http://www.ats-lang.org/ 
https://www.idris-lang.org/
http://lambda-the-ultimate.org/node/5256

Or if it's too complicated, maybe contracts?

https://en.wikipedia.org/wiki/Design_by_contract

**Comment by eriksvedang** [comment]
No, it's not a goal. I'm interested in them in an academic sense but they will not be part of Carp, most likely.
