### ISSUE TITLE
Possible manual typo

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [carp-lang/Carp#306]
In https://github.com/carp-lang/Carp/blob/master/docs/Libraries.md checking the module info is referred to be:

```
(info "Bench")
```
Which results in:  `Invalid args to 'info' command: (info "Bench")`
When testing I noticed this requires the module passed itself, instead of the module name:
```
(info Bench)
```

**Comment by eriksvedang** [comment]
That’s right, will fix!
