### ISSUE TITLE
RFC: Sum Types API

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#315]
I’ve been thinking about how we can make [sum types](https://en.wikipedia.org/wiki/Tagged_union) (aka syntactically beautiful tagged unions) happen in Carp. For those readers that don’t know sum types, sum types are types with multiple constructors. In ML-like languages you would write:

```haskell
data Maybe a = Just a | Nothing
```

In Rust you would solve this via enums:

```rust
enum Option<T> {
    Some(T),
    None,
}
```

## Compiler needs

From a compiler standpoint it’s pretty straightforward (I think): do it as tagged unions and emit functions that check the tags and wrap/unwrap the values to work with them.

## The API

That’s all well and good, but what about the API?

### Defining multi-constructor types

I have a few ideas on how to define sum types:

```clojure
; variant a
(deftype (Maybe a)
    (Just [value a])
    (Nothing [])
)

; variant b
(deftype (Maybe a)
    [Just [value a]
     Nothing []]
)
```

There are other permutations that could be done on this theme, but these are my personal favorites. Feel free to add more!

## Initialization

As per initializing them, this would be done via the usual constructors, e.g. `(Just.init someval)` and `(Nothing.init)`. The compiler would then have to know that this is a constructor for a sum type and handle them accordingly. The emitted C would construct a tagged union.

## Unwrapping

I believe the most graceful way to handle sum type unwrapping is through pattern matching—if you have other ideas, let me know!

I’d like to propose a syntax as follows:

```clojure
(defn unwrap-maybe [maybe dflt]
    (match maybe
         (Just thing) thing
         Nothing default
     )
)
```

Alternative suggestions are welcome!

## Open Questions

- [x] Did I forget anything?
- [x] Who should this be assigned to? (I’m happy to do som work, but might not be able to figure out everything by myself)
- [x] Is this even a good idea?

<hr/>

Cheers

**Comment by eriksvedang** [comment]
I think variant A is the best, it's what I've been planning for (slightly) in the current code (not that B is impossible though).

I have also thought quite a bit of how to add this feature without breaking everything else. I'm thinking that the best way to do it is probably by adding it kind of "on the side", leaving normal structs in there more or less untouched. Normal structs *could* be a generalisation of enums but keeping them separate has some benefits, implementation wise at least. I'm not entirely sure about this without working out the actual code though – it's always pleasing to unify concepts, of course.

If kept separate, members in sum types doesn't need to have names (since they won't generate getter/setter functions). This would avoid creating lots of partial functions which is a pretty good design in my opinion.

Perhaps it could just look like this, then:

```
;; syntax c
(deftype (Maybe a)
    (Just a)
    (Nothing))
```

Or more in line with structs, using `[]`:
```
;; syntax d
(deftype (Maybe a)
    (Just [a])
    (Nothing []))
```

I'll take on the bulk of the compiler work to make this happen (the only thing that has equal or higher priority is  lifetimes, but perhaps it's better to do this change first actually...). 

I'm very happy for any help with testing, usability concerns, code reviewing, etc, though!

**Comment by eriksvedang** [comment]
Actually, thinking about it a bit more this is the syntax I originally planned, I believe:

```
;; syntax e
(deftype (Maybe a)
    Just [a]
    Nothing [])
```

**Comment by eriksvedang** [comment]
OK, `D` it is then, unless someone comes along and has great arguments for something else!

I will start playing around with this in a new branch asap. I *do* have a lot on my plate right now, but this is also something I really want to do so I will find the time, I'm sure.

Really looking forward to how this will improve the core libs..!

**Comment by hellerve** [comment]
Did we agree on the syntax of `match` as well, then?

**Comment by eriksvedang** [comment]
Yes, it's the most reasonable way to do it I believe, and it matches `cond` / `case` too.

**Comment by hellerve** [comment]
Perfect. We should probably check statically that all constructors are matched on in the long run. It doesn’t need to be part of the WIP, and I can help you with that as well!

**Comment by eriksvedang** [comment]
Yeah, that's an awesome feature that I have no idea how tricky it will be to implement :)

**Comment by chrisosaurus** [comment]
Beautiful work team, D looks gorgeous.

I agree we don't want to generate getter/setters - which would only be valid on some elements of the sum type anyway.

Rust enums support naming, which can be really helpful, consider their example from [1]

```
enum WebEvent {
    // An `enum` may either be `unit-like`,
    PageLoad,
    PageUnload,
    // like tuple structs,
    KeyPress(char),
    Paste(String),
    // or like structures.
    Click { x: i64, y: i64 },
}
```

[1] https://doc.rust-lang.org/rust-by-example/custom_types/enum.html

**Comment by hellerve** [comment]
That’s actually quite a reasonable addition, I think, and shouldn’t complicate the compiler too much. I think it’s also not something that needs to be added immediately, like the completeness check I was proposing earlier. We can open separate tracking issues for both when the time has come!

**Comment by eriksvedang** [comment]
Playing around with this now (it's going pretty well). Turns out that this style of initialisation is a bit leaner so I think I'm gonna go for that:

```
(deftype Flip (A [Int]) (B [Bool]))

(defn f []
  (Flip.A 123))

(defn g []
  (Flip.B true))
```

It also means that you can do things like `(use Maybe)` and then just:
```
(defn f []
  (Just 123))
```

I've been planning to enable similarly minimalistic syntax for normal struct initialisation, so I think these will mirror each other in a nice way.

**Comment by hellerve** [comment]
Cool, I’m looking forward to playing with this. Tell me when there’s an MVP for me to integrate into my changes to the stdlib!

**Comment by hellerve** [comment]
I thought some more about having the members in a sum type be unnamed. I think I haven’t been completely onboard with arguments being unnamed for a while and I can finally articulate why (with a fair bit of help by [Rich Hickey](https://www.youtube.com/watch?v=YR5WdGrpoug)): Basically, what we are doing if we throw names over board is what Hickey calls “Place-Oriented Programming”—you have to know where each of the arguments go.

Now, this is not a problem with the types we talk about (Maybe, Either, etc.), because they only have a small amount of arguments. But what if we put more complex product types in the same space? Let’s look at an example:

```clojure
(deftype Address
    European [String Int Int String] ; street, number, zip code, city
    American [Int String Int String String] ; number, street, zip code, city, state
)
```

Of course this is constructed, but I can see types like these appearing. Who would remember the order of the arguments?

It is tedious enough to remember in `init` functions, sometimes even annoying. If we remove names completely from the type definition, we also wall up our avenue to adding better checks or at least editor integration later.

So I guess that’s why I was hesitant about voicing these concerns: they are entirely non-technical and instead about the “human element”—removing the names makes it harder for humans to understand what’s going on.

We don’t have to add functions for these names, or anything really. We don’t even have to require them. But I do wish for them to be there, because they make it easier for me to keep things in my head—or rather, to write them down instead of keeping them in my head.

**Comment by jburell** [comment]
In Rust they support both variants. Enums (the Rust sum type, not to be confused with C/C++ enums) can have three struct variants:

* Unit-like structs - (think Clojure keywords), zero size markers
* Tuple structs - named structs, anonymous fields, "tuples with names"
* Regular structs - named structs, named fields

You could use tuple structs everywhere, and complex parameter lists, but the ideomatic way is to only use them when the fields are few and obvious. 

To me that gives good ergonomics, but also leaves the user with all the tools to design their ADTs poorly if they like.

**Comment by hellerve** [comment]
I think I would like to have a system where the “better” way is encouraged if not enforced. I understand Rust’s system, and it seems like an okay tradeoff to have, but I’d really like to encourage people to use names everywhere.

If the names are just metainformation that gets “compiled away” anyway, it shouldn’t be too hard to make them optional, though, and we could have something for everyone. (To be clear: I’m advertising for a system where those names are added to the data type inside the compiler, but nothing is done in the emitter and the names are just dropped; this gives us the opportunity to write analytics tools on top of Carp-as-a-library.)

**Comment by jburell** [comment]
@hellerve I totally agree. I'm in general in favor of strictness where it leads to better communication to the reader or better metadata to the compiler. It was just an example of the pragmatic approach. 

In general I feel that dynamic languages often favors the author and not the many readers, who are forced to dig deep in the code documentation/implementations to figure out the actual data being duck typed. That is bad in my book if you are looking for ease of use for new contributors to a given project, and causes scalability issues as the code base grows. Types does not merely aid the compiler, it helps with readability for the user as well (by the cost of extra key strokes in cases where inference is not possible or suitable, such as this). I'm all for named fields. 

I believe that names in Rust are just metainformation as well, that is why "zero cost" structs are possible (they are only used for matching, but carries no inherent data). Out of curiosity i disassembled an ADT match in Rust just to see what it generates and it basically splits the ADT in two parts. One part is the actual data (pushed on the stack or elsewhere) and the other part is the enumeration part that is used for the match expression, enumerated top to bottom in the sum type and follows the type in the call chain.

See example here: https://godbolt.org/z/nmZjld
Lines 3-8 in the disassembly shows the SumType data when initialized and line 9 and forward shows the match expression (which is basically a chain of equality tests against the enumeration part of the sum type, a simple integer). I'm guessing this grows in complexity if you include guards or partial matches, but the match on the types seems to only be equality tests on a simple enumeration created under the hood independent of content.

**Comment by eriksvedang** [comment]
These are good ideas and reflect my own thinking as well. When I have gotten the implementation into a usable state we can try out those adjustments and make sure everything feels great before merging into master.

**Comment by jburell** [comment]
@hellerve @eriksvedang Also, taking notes from Clojure-spec (https://clojure.org/about/spec) in where they are actively working on bolting these kinds of (optional) type safeties to an existing dynamic language is hard. There is something to be said about a guaranteed base line of type safety and being explicit where it matters. It makes all derivative work much more elegant and easier to implement. Whenever the compiler is uncertain about intention, there are always room for undefined behavior or bugs. And leaving checks to the runtime instead of compile time will apply costs to virtually all execution.

**Comment by chrisosaurus** [comment]
@hellerve +1, in general I dislike the order of arguments mattering as it can lead to subtle bugs, at least when you have more than 1 or 2 of the same type.

**Comment by hellerve** [comment]
This can be closed for now, though we still have problems with PLOP!
