### ISSUE TITLE
String.lines is slow

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#318]
I used `String.lines` on a big file today and realized just how long it takes to split up a long file. For a file that has around 10.000 non-empty lines, the `time` utility on my machine reports about 34 seconds to split this up.

Example run:
```~/.carp/out/Untitled  33.74s user 0.69s system 99% cpu 34.700 total```

Script for reproduction:
```clojure
(defn main []
  (let-do [ls (lines &(IO.read-file "some-big-file.txt"))]
    (IO.println &(str (Array.length &ls)))))
```

This is obviously too slow. I suspect that the culprit is the `split-by` utility or maybe `Pattern` itself, but I haven’t digged into it yet.

Cheers

**Comment by eriksvedang** [comment]
Ouch! Yes this needs to be investigated for sure.

**Comment by eriksvedang** [comment]
Will you have the chance to profile this?

**Comment by hellerve** [comment]
Sure, I will do that!

**Comment by hellerve** [comment]
When I use the reproduction script that I provided, the script still takes about 35 seconds to complete. Maybe it’s not `String.lines`, but I don’t know for sure.

**Comment by hellerve** [comment]
<img width="380" alt="string.lines" src="https://user-images.githubusercontent.com/7725188/47780204-3cd08280-dcfb-11e8-9738-b6a7dfdb1287.png">

It is in fact `String.lines`. How in the heck that happens I don’t know.

**Comment by eriksvedang** [comment]
Is that with the legs.txt file? Your example program above gives this output from `time` on my machine:

```carp -x --optimize $1 slow.carp  2.41s user 0.60s system 117% cpu 2.552 total```

**Comment by eriksvedang** [comment]
Do you get a hint from the profiler what takes time inside the String_lines function?

**Comment by hellerve** [comment]
Wow, if I add `--optimize`, it runs as quickly as yours. It’s the `assert`s?

**Comment by hellerve** [comment]
I think we can close this now. The asserts were the culprit!
