### ISSUE TITLE
let can generate invalid C

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#320]
When the same variable is bound twice in the same `let` expression, Carp generates invalid C by declaring the variable twice in the same scope. There are multiple ways to go about this; my personal favorite is disallowing it alltogether.

Example program:
```clojure
(defn main []
  (let [x 1
        x 2]
    (IO.println &(str x))))
```

Interestingly, this is not an issue with nested `let` bindings:
```clojure
(defn main []
  (let [x 1]
    (let [x 2]
      (IO.println &(str x)))))
```

This is because every `let` opens a new C scope by adding `{}` around the expression, and C is okay with redeclaring variables in an inner scope.

Cheers

**Comment by eriksvedang** [comment]
Good find! I'll think a little about where checks for things like this should happen in the compiler pipeline. If it's something you want to fix yourself, let me know!

**Comment by hellerve** [comment]
I can fix this if you tell me where the appropriate place to add it would be!

**Comment by eriksvedang** [comment]
Will do... when I know :)

**Comment by chrisosaurus** [comment]
Very nice find!

Are lets allowed to be recursive?
if not, then you could consider defining all lets as a translation

that is the input

```
(let [x 1
       y 2]
   ...)
```

is semantically equivalent to

```
(let [x 1]
  (let [y 2]
    ...))
```

internally we could translate it as such, and thus rely on the existing nesting generation logic.

Making it a compile-time error would also work.

**Comment by hellerve** [comment]
I thought about transforming `let` like that, but I’m not sure whether rebinding a variable inside `let` is likely to be a bug or not. If it is, then the transformation hides it, and it should rather be a compiler error. But I know I did things like this before:

```clojure
(let [my-collection (copy-map transform other-collection)
      my-collection (filter filter-fn my-collection)]
  ; ...
)
```

Mostly to avoid temporary meaningless names and still decompose a complicated action; I’m not sure whether this is an anti-pattern, though.

In general, it needs to be determined what the best course of action would be. There are three solutions as I see it:
- Make it a compile-time error. But does that restrict programmers too much?
- Transform `let` into a series of `let` forms that each only bind one variable. The simplest solution. Does opening more nested scopes influence the readability of the generated C code or the quality of the generated machine code?
- Make the compiler “smarter” and detect those rebindings, avoiding redeclaration. More complex than either of the other two solutions. It avoids the question of how the C code changes. But should it be allowed in the first place?

This is what I’m currently debating with myself; what do y’all think?

**Comment by chrisosaurus** [comment]
That was exactly the use case I was thinking about, but I am likewise a bit unsure - we would have to agree to define our let that way.

Naively I think the 3rd option is hard, as there are cases where we intentionally do want different scoped xs.

```
(let [x "world."]
  (do (let [x "hello "]
          (IO.println &x)) -- prints "hello "
        (IO.println &x)) -- print "world."
```

which should print "hello world.".

I think this means we would need to detect cases where shadowing occurs and there are no later uses of the earlier value, which doesn't sound fun.


I think making it a compile time error is okay, that is what Haskell appears to do

```
foo = let x = 1
          x = x + 1
      in x

main = do
  putStrLn $ show foo
```

gives the compile time error

```
error:
    Conflicting definitions for ‘x’
    Bound at: t.hs:2:11
              t.hs:3:11
```

to get around this in Haskell it is more common to do something like

```
foo = let x = 1
              x' = x + 1
              x'' = x' + 2
         in x''
```

whereas in Haskell this is fine

```
bar = let x = 1 in
      let x = 2 in
      x

main = do
  putStrLn show bar
```

so making it a compile time error for us would be consistent with Haskell, it seems.

I think the only difference is that Haskell is lazy, and so does not define any strict evaluation order of expressions within the let (all lets are letrecs), whereas we could if we wanted to.

**Comment by hellerve** [comment]
Any updates on where in the pipeline this should go?

**Comment by eriksvedang** [comment]
Line 323 in InitialTypes.hs should catch this already (with a fatal error). So perhaps just change that to a proper TypeError works..?

**Comment by eriksvedang** [comment]
Sorry, I mixed up the errors. But perhaps this area of the code could figure this out anyways. A more principled way is to add onother step in Infer.hs that just checks for these kinds of "assumptions" early on, so that the rest of the compiler can assume that they hold.
