### ISSUE TITLE
Prematurely expanded defn forms lead to the emission of broken C

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#323]
When writing macros, I often forget the odd quotation. As I discovered today, this can lead to the emission of broken C code when combined with `defn`. An example:

```clojure
(defn x [] (IO.println &(str (+ 22 3))))

(defmacro after-x [body]
    (list 'do
      (list x) ; misspelled because not quoted
      body))

(defn main []
  (IO.println &(str (after-x "test"))))
```

The use of an unquoted `x` in line 5 of this example will miraculously pass all of the phases of the compiler—even typechecking!—and go all the way to code emission, where the definition of the function will be inlined *inside of the `main` function*.

This is quirky, puzzling, and definitely wrong! How fun!

Cheers

**Comment by hellerve** [comment]
Relatedly, this will also generate invalid C:

```clojure
(defn x []
  (do
    (def y 1)
    0))
```

I suppose we should check whether `def` and `defn` are top-level forms and emit an error if they are note.

**Comment by eriksvedang** [comment]
This is fixed in master now.

**Comment by hellerve** [comment]
Thank you <3
