### ISSUE TITLE
Using non-symbols as lhs of bindings in let crashes the compiler

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#324]
When using something other than symbols as the left-hand-side of the bidnings inside a `let` expression crashes the compiler because it is piped through to the Qualification stage, where the AST walker expects a symbol—and righftully so, if the code weren’t broken. An example:

```clojure
(defn main []
  (let [1 2]
    (IO.println "wut")))
```

This will lead to utter disbelief on the compiler’s side, which, flabbergasted, only dares to mutter:

```
carp: src/Qualify.hs:(60,22)-(62,74): Non-exhaustive patterns in lambda
```

After which it quietly leaves the stage.

Whether the lambda within the Qualification stage needs to be fixed or a check should be added before I leave to those who masterfully carve the compiler from the stones.

Cheers

**Comment by scolsen** [comment]
#447 resolves the Qualify pattern issue. It's now handled somewhat more gracefully--the compiler has traded its muttered garble for a timid reminder that an let-crafting artisans do not bind non-symbols. 

Also related #414 (which I think might also be ready for closing, though I am not sure)

**Comment by hellerve** [comment]
You’re absolutely right, this can be closed now!
