### ISSUE TITLE
set! doesn't work for closure variables

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#337]
I'm not sure whether this is a feature of the language or not, so the fix is either better static analysis to disallow this,or better code generation to allow this :)

```
(defn main []
  (let [ret false
        f (fn [x]
            (set! ret true))]
    (do
      (f 0)
      (IO.println &(str ret)))))
```
```
./out//main.c:2847:5: error: use of undeclared identifier 'ret'
    ret = true;  // Bool = Bool
```
The generated function doesn't access `ret` via `env`:
```
void _Lambda_main_14(_Lambda_main_14_env* _env, int x) {
    ret = true;  // Bool = Bool
}
```

**Comment by eriksvedang** [comment]
Yeah, this will become outlawed by the compiler eventually, sorry about just leaving it there to cut your fingers on..!

**Comment by eriksvedang** [comment]
This is fixed in `master` now (you can't mutate captured variables).
