### ISSUE TITLE
nested closures break

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#342]
Example code:
```
(defn main []
  (let [f (fn [x] ((fn [y] (+ x y))
                   1))]
    (IO.println &(str (f 1)))))
```
Generates broken C:
```
./out//main.c:2631:22: error: use of undeclared identifier 'x'
        _18_env->x = x;
                     ^
```

**Comment by opqdonut** [comment]
I have a partial fix, but ran out of time today.

See https://github.com/carp-lang/Carp/compare/master...opqdonut:lambda-bug

**Comment by opqdonut** [comment]
I found the final (I think?) problem, but I'm not sure how to solve it. More info is needed during code generation.

See https://github.com/carp-lang/Carp/compare/master...opqdonut:lambda-bug#diff-50cdbb20457c1f774c6a4a542d8b25abR200

I won't continue working on this.

**Comment by hellerve** [comment]
Thanks for this, this is super helpful! I can look into this once I find time, but I think @eriksvedang is probably the right person to check this out.

**Comment by jacereda** [comment]
Looks like this one works on latest master.

**Comment by eriksvedang** [comment]
Huh, interesting! I wonder what fixed it...
