### ISSUE TITLE
Array.sort subtly broken

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#343]
Sorting large arrays doesn't always quite sort the data.

Luckily I managed to reproduce this with a fairly small example:

```
(defn hash-comparison [a b]
  (< (hash a)
     (hash b)))

(defn main []
  (let [expected (Array.copy-map &(fn [i] (str @i)) &(Array.range 100 200 1))
        ;; shuffle input by sorting by hash:
        in (Array.sort-by @&expected &hash-comparison)]
    (do
     (let [out (Array.sort in)]
       (do
        (println* &out)
        (println* (= &out &expected)))))))
```
Output:
```
[@"100" @"101" @"102" @"103" @"104" @"105" @"106" @"107" @"108" @"109" @"110" @"111" @"112" @"113" @"114" @"115" @"116" @"117" @"118" @"119" @"120" @"121" @"122" @"123" @"124" @"125" @"126" @"127" @"128" @"129" @"130" @"131" @"132" @"133" @"134" @"135" @"136" @"137" @"138" @"139" @"140" @"141" @"142" @"143" @"144" @"145" @"146" @"147" @"148" @"149" @"150" @"151" @"152" @"153" @"154" @"155" @"156" @"157" @"158" @"159" @"160" @"161" @"162" @"163" @"164" @"165" @"166" @"167" @"168" @"169" @"170" @"178" @"171" @"172" @"173" @"174" @"183" @"175" @"176" @"177" @"179" @"180" @"181" @"182" @"184" @"186" @"185" @"187" @"188" @"189" @"190" @"191" @"192" @"193" @"194" @"195" @"196" @"197" @"198" @"199" @"200"]
false
```

Note the part `@"170" @"178" @"171"`.

**Comment by hellerve** [comment]
That’s interesting! This must be a regression of moving away from `qsort` (a C function) to our own heap-based sort (see also #262 #252 #331). At least I hope it is, because otherwise I’m at a loss what it could be!

**Comment by opqdonut** [comment]
yeah an off-by-one in the heapsort is my guess as well

**Comment by eriksvedang** [comment]
Who wants to fix it?

**Comment by hellerve** [comment]
I can take a look at it when I get my pipeline back on track. I can’t promise I’ll have time for that this week, maybe next. I’ll keep y’all posted if I can’t make it happen!

**Comment by chrisosaurus** [comment]
Ohhh awesome! Thanks for the awesome bug report.

I can take a look at this if you want, as it is likely my bug, worst case I will have time this weekend.

**Comment by chrisosaurus** [comment]
Thanks to the awesome test case I have been able to shrink it down ever further

```
(defn hash-comparison [a b]
  (< (hash a)
     (hash b)))

(defn main []
  (let [expected (Array.copy-map &(fn [i] (str @i)) &(Array.range 110 136 1))
        ;; shuffle input by sorting by hash:
        in (Array.sort-by @&expected &hash-comparison)]
    (do
     (let [out (Array.sort in)]
       (do
        (println* &out)
        (println* (= &out &expected)))))))
```

running it gives

```
$ stack build && stack exec carp -- sort-bug.carp -x
[@"110" @"111" @"112" @"113" @"114" @"115" @"116" @"117" @"118" @"119" @"120" @"121" @"122" @"123" @"124" @"125" @"127" @"131" @"126" @"128" @"129" @"130" @"132" @"133" @"134" @"135" @"136"]
false
```

changing either bound to be tighter makes the problem go away.

Changing therange from '110..136' to '10..36' also makes the problem go away, which is very fun.

Taking a deeper look when I get more time, will have to call it a night soon.

**Comment by chrisosaurus** [comment]
Okay I've been able to reproduce a sublte bug within my Heapify, still working on cause. Going to call it a night *very* soon now :)

**Comment by chrisosaurus** [comment]
Smaller test case, took a lot of effort to distill, thanks for the amazing reproduction case - I couldn't have found it without it.

```
(defn main []
  (let [in   [20 0 10 21 11 1 2 22 12 24 23 13 3 14 4 25 5 15 16 6 17 7 8 18 19 9]
        exp  (Array.range 0 25 1)
        heap (Array.copy &in)
        out  (Array.sorted &in)]
    (do
      (MaxHeap.heapify! &heap)

      (println* "in:   " &in)
      (println* "heap: " &heap)
      (println* "exp:  " &exp)
      (println* "out:  " &out)
      (println* "(= out exp): " (= &out &exp)))))
```

running it

```
$ stack build && stack exec carp -- sort-bug.carp -x
in:   [20 0 10 21 11 1 2 22 12 24 23 13 3 14 4 25 5 15 16 6 17 7 8 18 19 9]
heap: [25 24 22 23 16 21 19 20 12 15 17 18 14 3 4 10 0 5 11 6 1 7 8 13 2 9]
exp:  [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
out:  [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 17 16 18 19 20 21 22 23 24 25]
(= out exp): false
```

we can see that the output is incorrect as it orders `15 17 16 18`

we can see that the heap is incorrect as it has `17` as the right child of `16`

**Comment by chrisosaurus** [comment]
I've found the bug, I have a fix I will sent for PR later today.
I'm just adding more unit testing now to make sure this doesn't happen again.

**Comment by chrisosaurus** [comment]
Pull request up at #344 

Thanks @opqdonut for the superb bug report with a repro case, I cannot overstate how much that helped, sorry for making your AoC a bit harder :)
