### ISSUE TITLE
return type not checked for recursive calls

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#349]
This crashes with segmentation fault:
```
(defn recurse [a]
  (if (= a 0)
    ;; We return an Int
    0
    ;; But treat the return value of the recursive call as &Int
    @(recurse (dec a))))

(defn main []
  (println* (recurse 1)))

**Comment by eriksvedang** [comment]
I've investigated this one a bit now. It's a weird one – making the return type something else (like changing the `@` to a `&`) *will* be detected by the compiler. Seems like it's only refs that are the problem. So that's a hint...
