### ISSUE TITLE
No mutual recursion

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#350]
Not sure if this is an issue, but I'm jotting it down just in case.

Mutual recursion is not supported.

```
(defn even? [a]
  (or (= a 0)
      (odd? (dec a))))

(defn odd? [a]
  (not (even? a)))

(defn main []
  (println* (odd? 1)))
```
```
Trying to refer to an undefined symbol 'odd?' at line 4, column 22 in '.../dbg.carp'.
```

I don't see a reason why it couldn't be supported, since Carp already generates declarations for all functions before their definitions.

**Comment by eriksvedang** [comment]
There is an example of how to do mutual recursion in `examples/mutual_recursion.carp`. It requires a forward declaration since the compiler is single pass. Hope that helps!

**Comment by opqdonut** [comment]
Thanks!

What's the second argument? Return type?
