### ISSUE TITLE
String escape parsing broken

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#358]
```
(def s "\\")

(defn main []
  (println* s))
```
```
[PARSE ERROR] ".../dbg.carp" (line 5, column 1): unexpected end of input expecting "\\" or "\""
```

**Comment by opqdonut** [comment]
this works:
```
(def s "\\ ")

(defn main []
  (println* s))
```

**Comment by hellerve** [comment]
I have a possible fix for this in my branch [fix-string-escapes](https://github.com/hellerve/Carp/tree/fix-string-escapes), but I haven’t been able to fix my setup yet.

**Comment by eriksvedang** [comment]
Oh? I was just playing around with this but couldn't come up with anything quickly... what's the trick?

**Comment by eriksvedang** [comment]
Checking out your solution now...

**Comment by eriksvedang** [comment]
Doesn't seem to solve this particular error I'm afraid... what's the reasoning behind it?

**Comment by hellerve** [comment]
I completely forgot this issue, sorry! I have a fix for this that seems to work rather nicely, but sadly obfuscates the string parser a little bit. I’m going to make a PR and you can tell me whether you find a more elegant solution!

**Comment by hellerve** [comment]
We should be able to close this (because of #375).
