### ISSUE TITLE
Inconsitent Refs in Array functions

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#362]
IMO:
- Array.index-of should take a ref to the element to be searched
- Array.first should return a ref, just like Array.nth does

**Comment by eriksvedang** [comment]
Totally agree! The first one is probably just a slip up but the second one is because non-internal functions are not allowed to return references right now, due to lack of lifetimes. When we have lifetimes this restriction can hopefully be lifted.

**Comment by eriksvedang** [comment]
`Array.index-of` is now fixed. Will close this because `nth` is on the todo list already.
