### ISSUE TITLE
Can't set! given away value

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#363]
Seems like this should be possible:
```
(defn pair-arr [arr]
  (Pair.init 1 arr))

(defn main []
  (let-do [arr [1]
        int-and-arr (pair-arr arr)]
    (set! arr @(Pair.b &int-and-arr))
    (println* &arr)))
```
but I get an error:
```
Using a given-away value 'arr' at line 7, column 11 in '.../dbg.carp'
```
It works if I don't use a let, but then I can't access the first entry of the pair:
```
(defn pair-arr [arr]
  (Pair.init 1 arr))

(defn main []
  (let-do [arr [1]]
    (set! arr @(Pair.b &(pair-arr arr)))
    (println* &arr)))
```

**Comment by hellerve** [comment]
You give away `arr` in the call to `(pair-arr arr)`, so you can’t reset it later. But then the second one also shouldn’t work?

**Comment by opqdonut** [comment]
Yeah, but we do stuff like
```
(set! arr (Array.filter &pred arr))
```
all the time, right?

**Comment by eriksvedang** [comment]
Mhm, this seems like it should be possible...

**Comment by eriksvedang** [comment]
Looking into this some more, I think this is OK behaviour. Perhaps the ergonomics of it can be improved with lifetime parameters, but I'm not sure... Will close this for now.
