### ISSUE TITLE
Allow for customization within documentation generation

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#374]
Currently, everything in the documentation generator is hardcoded. This is a little annoying when writing custom documentation, and it would be nice if we could rectify this. An example for some of the things I’d like to be able to do can be found in [the documentation for anima](http://veitheller.de/anima/). I’m hiding the navigation, using a custom icon, and add a documentation prelude. Stuff like this should be supported.

Things I want to be able to customize:

- [x] Styling
- [ ] Which sections to display
- [x] The icon
- [x] Add custom prelude/sections
- Any other ideas?

I’d be up for working on this, and I’d like to hear about any wishes you might have to create a great automatic documentation system! This issue should serve as a conversation starter and brain dump.

Cheers

**Comment by hellerve** [comment]
Another one: I’d like to be able to write markdown in the doc strings (and have it be rendered as HTML on the page). People probably have strong feelings about what markup language to use, but Markdown seems like a pretty common choice and is used by a lot of people already.

**Comment by eriksvedang** [comment]
Sounds like a good idea.

**Comment by hellerve** [comment]
It seems like a lot of this can be fulfilled by changing `projectIndexPage` in `RenderDocs`. I believe rethinking the entire documentation rendering architecture might be worth it, if we have the time, but if push comes to shove, that function might be all that we need to change!

**Comment by eriksvedang** [comment]
OK, yeah I haven't looked at it in a while but I'm definitely open to changing the structure there, if needed.

**Comment by hellerve** [comment]
I’m going to look at this over the weekend, but I’m not sure whether I’ll find a satisfying API just yet. It just hasn’t quite cleared up to me.

**Comment by eriksvedang** [comment]
Sounds good!

**Comment by eriksvedang** [comment]
Can this be closed or are there more features needed?

**Comment by hellerve** [comment]
I think #459 just about made this perfect!
