### ISSUE TITLE
Provide a Dockerfile

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#379]
As suggested in #329, we could provide a Dockerfile for prospective users to facilitate experimentation. I’d like to wait for a stable release before providing this, but maybe we disagree here?

Also, I’d like to hear some input on whether that should be community-provided (as in, not maintained by the Carp maintainers themselves) or part of this organization.

Cheers

**Comment by eriksvedang** [comment]
I know nothing about Docker and don't want to use it, but if it's something that would let people try out the language more easily I think it would be worthwhile to add to the official repo.

**Comment by hellerve** [comment]
Alright, I’m going to try and write a Dockerfile then; we could alternatively also add another repository to this org?

**Comment by eriksvedang** [comment]
Yeah, good idea. I'll do that and add you to it.

**Comment by hellerve** [comment]
I added an initial Dockerfile. It should work, although it isn’t particularly optimized. Is this close to what you requested, @Immortalin?

**Comment by Immortalin** [comment]
Looks awesome! Thanks so much 👍

**Comment by hellerve** [comment]
I’ll close this issue for now then :)
