### ISSUE TITLE
Can't define a function that begins with a hyphen

### ISSUE THREAD

**Issue by cnasc** [carp-lang/Carp#398]
```clojure
(use Int)

(defn -mod
  [a b n]
  (mod (- a b) n))

(defn main []
  (let [x (str (-mod 5 12 2))]
    (IO.println &x)))
```

When this function is defined as `mod-sub`, it builds (although it returns what I believe to be an erroneous `-1`...). However, defined as above I get the following error:

```
I didn’t understand the `defn` at line 3, column 1 in '/home/cjn/code/diffie-hellman/test.carp':

(defn - mod [a b n] (mod (- a b) n))

Is it valid? Every `defn` needs to follow the form `(defn name [arg] body)`.
```

It seems like I may have run afoul of some identifier rules that are different from other Lisps (although, there is still a `-` function in Carp). I couldn't find the definition of a valid identifier in the docs, and I'm going to take a look through the source to see how it's defined, but I wanted to raise an issue because this didn't feel like the "right thing".

**Comment by eriksvedang** [comment]
Right... if I remember correctly the parser has a list of valid initial characters for symbols, where `-` is missing. Perhaps it has something to do with the negation of numerals also (e.g. `-10`). Do you want to fix it?

**Comment by cnasc** [comment]
I’ll take a look tomorrow!

**Comment by cnasc** [comment]
I think you're on to something with the negation of numerals being a factor. I tried moving `symbol` to be the first choice in the definition of `atom`.

https://github.com/carp-lang/Carp/blob/5ad6e94579fd583a5b6e333f79fe6811873cba23/src/Parsing.hs#L245-L246

The first result of that was that it broke Carp's ability to read numbers. However, the second result was the following REPL session (huge cascade of errors omitted):
```
Welcome to Carp 0.2.0
This is free software with ABSOLUTELY NO WARRANTY.
Evaluate (help) for more information.
> (defndynamic -mod []
     "hello")
> (-mod)
=> "hello"
```

Now time to dig into the numbers...

**Comment by hellerve** [comment]
The error is in fact in `maybeSigned`, or more specifically in the use of `Parsec.many`. This combinator will match zero or more numbers, meaning that if `num0` is the sign, it’s perfectly valid for `num1` to be empty, resulting in the parsed number being `-`.

We don’t actually need this setup at all. Instead we can write:

```haskell
sign <- Parsec.optionMaybe (Parsec.char '-')
digits <- Parsec.many1 Parsec.digit
let num = maybe "" (\x -> [x]) sign ++ digits
```

This gets rid of `firstDigit` completely, and simplifies the whole setup! I’ll open a PR with the change. Thanks for digging into this, @cnasc!

**Comment by cnasc** [comment]
Thank you for the great demonstration of how to solve it!

**Comment by eriksvedang** [comment]
Very good!

**Comment by hellerve** [comment]
I think this ready to be closed then!
