### ISSUE TITLE
Command line argument to generate C source but not compile it?

### ISSUE THREAD

**Issue by babelchips** [carp-lang/Carp#416]
I want to build my Carp generated C code in a separate build process.  How can I get just the C output via the Carp command line?

**Comment by eriksvedang** [comment]
There isn't a command to do that right now I'm afraid (feel free to add it if you have the time). 
What you can do is to set the compilation command to an empty string `(Project.config "compiler" "")`, then do a build with `carp -b` and finally `cat out/main.c`.

**Comment by babelchips** [comment]
It seems like there are a few different ways I could go about adding this feature.  Which one is preferred?

1. Add an extra option to the command line `--genOnly` which simply prevents the compiler from being called.
2. Add a different command line switch `-g` which behaves similar to `-b` but just generates the C source without compiling.
3. Add a new command line option, e.g. `-p` which lets you specify a project file containing overrides (e.g. compiler: "")

**Comment by hellerve** [comment]
I think this can be closed now that #418 is merged!

**Comment by hellerve** [comment]
Thanks for your hard work, @babelchips!
