### ISSUE TITLE
Using Carp for pointer arithmetic etc. of arrays of C structs

### ISSUE THREAD

**Issue by babelchips** [carp-lang/Carp#423]
I’m interested in using Carp to directly and efficiently manipulate collections of C data. For example, the following C code manipulates a struct pointer to a bunch of Particles in a malloc’d buffer.  I’d like to have access to the same (C owned) buffer in my Carp code and then use Carp pointer arithmetic and dereferencing to modify any of the data.

1. Get a reference to the buffer (call out to C and get the address..)
2. Define a type to the underlying C struct (already possible)
3. Set and get values of referenced memory using Carp syntax e.g. ```(particle-ref set-x 2.5)```
4. Do pointer arithmetic on the reference (to point to any other struct in memory), e.g. ```(address-inc particle-ref)``` or ```(address-index 24 particle-ref)```

How many of these steps does Carp support currently?
What is missing?
I’m aware this may be asking a lot of Carp but it is even remotely feasible?

```
#include <stdlib.h>
#include <stdio.h>

struct Vector3 {
    float x;
    float y;
    float z;
} Vector3;

struct Particle
{
	struct Vector3 pos; // the particle’s position
	struct Vector3 vector; // the particle’s vector
} Particle;

struct Particle* p;

void dumpParticle(struct Particle *p)
{
    printf("Pos: %f %f %f\n",p->pos.x,p->pos.y,p->pos.z);
}

void main()
{
    p = malloc(1000 * sizeof(struct Particle)); // allocate memory for the collection of particles
    
    // modify the first particle
    p->pos.x = 1.0f;
    p->pos.y = 2.0f;
    p->pos.z = 3.0f;
    dumpParticle(p);
    
    p++; // point to the next particle
    p->pos.x = 4.0f;
    p->pos.y = 5.0f;
    p->pos.z = 6.0f;
    dumpParticle(p);
    
    p--; // point back to the original particle
    dumpParticle(p);
}
```

**Comment by hellerve** [comment]
This is an interesting questions. Where you’d be able to go with Carp right now is registering the C type and hangling the pointer. The functions `address-*` that you’re envisioning would have to be created. They shouldn’t be too hard, though. As a draft, something like this could work:

```clojure
(register address-inc (Fn [(Ptr a)] (Ptr a)) "address_inc")
```

And in C:

```c
void* address_inc(void* in) { return ++in; }
```

And you’re good to go (ideally this would be part of the standard library).

The downside of an approach like this would be that it’s basically impossible to guarantee safety in that case! I guess that would be a fair tradeoff, but it’d have to be communicated very clearly that this is an unsafe operation.

**Comment by babelchips** [comment]
Ok thanks for the info.  I'll see what I can achieve.

**Comment by eriksvedang** [comment]
This seems like a cool thing to have in Core for people who want to do very unsafe things :)
