### ISSUE TITLE
SDLHelper.h:1:10: fatal error: 'SDL.h' file not found

### ISSUE THREAD

**Issue by jkleiser** [carp-lang/Carp#430]
I just installed Carp on my Mac (macOS 10.14.4), and I have put the "Very Small Example" in a separate folder, and started carp from there. When I do `(load "example.carp")` and then `(build)`, I get this:
```
/bin/sh: sdl2-config: command not found
In file included from ./out/main.c:1:
/Volumes/P3/Carp//core/../core/SDLHelper.h:1:10: fatal error: 'SDL.h' file not found
#include <SDL.h>
         ^
1 error generated.
carp: callCommand: clang -fPIC -lm -g ./out/main.c -o "./out/Untitled"  -I/Volumes/P3/Carp//core/  `sdl2-config --cflags --libs` -D_THREAD_SAFE  (exit 1): failed
```
What may be the reason?

**Comment by bjorn3** [comment]
Is SDL installed?

**Comment by jkleiser** [comment]
No, I'm not familiar with SDL. Shall I do `brew install sdl2`, or shall I use `stack` for this?

**Comment by bjorn3** [comment]
Probably `brew install sdl2`.

**Comment by jkleiser** [comment]
I now did `brew install sdl2`, but then I get this:
```
In file included from ./out/main.c:1:
In file included from /Volumes/P3/Carp//core/../core/SDLHelper.h:1:
In file included from /usr/local/include/SDL2/SDL.h:32:
In file included from /usr/local/include/SDL2/SDL_main.h:25:
In file included from /usr/local/include/SDL2/SDL_stdinc.h:31:
In file included from /usr/local/include/SDL2/SDL_config.h:33:
/usr/local/include/SDL2/SDL_platform.h:71:10: fatal error: 'AvailabilityMacros.h' file not found
#include "AvailabilityMacros.h"
         ^
1 error generated.
carp: callCommand: clang -fPIC -lm -g ./out/main.c -o "./out/Untitled"  -I/Volumes/P3/Carp//core/  `sdl2-config --cflags --libs` -D_THREAD_SAFE  (exit 1): failed
```

**Comment by hellerve** [comment]
That file is apparently part of the XCode developer package (how annoying!).

Do you have XCode installed?

Clarification: none of this is required to get Carp to run, but the example uses SDL, a toolkit for graphical applications.

**Comment by jkleiser** [comment]
Yes, I have XCode installed, and `xcode-select --version` says "xcode-select version 2354."

I'm sure I can I have much fun with Carp without SDL, but since that example was just a "Very Small Example", I wanted to try that first. ;-)

**Comment by hellerve** [comment]
Hmmm, I fear that I’m at a loss here. The issue seems to be within SDL, and I’m not an expert there. Sorry!

**Comment by eriksvedang** [comment]
You could try to compile a minimal main.c with clang from the command line, that just includes and links SDL, to rule out any problems with Carp. Sounds like there's some kind of Brew problem really. Installing SDL manually is pretty simple too, basically `./configure; make; make install;`

**Comment by jkleiser** [comment]
Hi. I now installed SDL manually, no problems. Then I could `(build)` and `(run)` the "Very Small Example". Worked fine. Thanks! (I may take the time to report the problem to Homebrew.)

**Comment by jkleiser** [comment]
"No problems" wasn't quite true. That was on an old Mac mini. On the big iMac, however, where first tried brew, I did a `brew uninstall sdl2` and then installed SDL manually. There I still get "fatal error: 'AvailabilityMacros.h' file not found". And now I have tried on a third Mac, a MacBook Air, and I get the same problem there. Strange. Now I have to take a break. ;-)

**Comment by hellerve** [comment]
Thanks for digging into this, and thanks for your patience! FWIW, Erik and I are both using Macbook Pros (mine is also running OS X 10.14.4), and at least for me SDL doesn’t seem to have a problem. I have SDL installed via Homebrew (`sdl`, `sdl_mixer`, `sdl_image`, and `sdl_ttf`, to be precise).

**Comment by jkleiser** [comment]
Right now my MacBook Air is the only one available to me. It has problems with the SDL example, but it also has problems building a simple hello.carp:
```
(defn main []
  (IO.println "Hello, Carp!"))
```
When I do `(build)`, I get this:
```
In file included from ./out/main.c:1:
In file included from /Volumes/P3/Carp/core/carp_debug.h:1:
/Volumes/P3/Carp/core/core.h:5:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
carp: callCommand: clang -fPIC -lm -g ./out/main.c -o "./out/Untitled"  -I/Volumes/P3/Carp/core/   (exit 1): failed
```
Is it possible that I'm using a wrong clang version?
```
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```
I also have this:
```
$ /usr/bin/clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by eriksvedang** [comment]
Seems like a mysterious problem..! You can use `sdl2-config` and `which sdl2-config` to identify remnants of old installations. Try to get rid of all of it before doing a clean install, I have had most success with source builds but brew should work too of course.

**Comment by jkleiser** [comment]
Simply doing `brew uninstall` solved my problems (on this Mac). Now both hello.carp and the SDL example.carp works!

**Comment by jkleiser** [comment]
By the way, the docs/Install.md tells us to use something like
```
export CARP_DIR=~/Carp/
```
I think the final "/" may cause problems.

**Comment by eriksvedang** [comment]
Yay, glad you solved it!

**Comment by eriksvedang** [comment]
Regarding the trailing `/` – did it cause problems for you? You might be right, I just never ran into trouble with it.

**Comment by jkleiser** [comment]
Yes, before I got rid of the other llvm, I encountered this:
```
鲮 (build)
In file included from ./out/main.c:1:
In file included from /Volumes/P3/Carp//core/../core/SDLHelper.h:1:
In file included from /usr/local/include/SDL2/SDL.h:32:
In file included from /usr/local/include/SDL2/SDL_main.h:25:
In file included from /usr/local/include/SDL2/SDL_stdinc.h:31:
In file included from /usr/local/include/SDL2/SDL_config.h:33:
/usr/local/include/SDL2/SDL_platform.h:71:10: fatal error: 'AvailabilityMacros.h' file not found
#include "AvailabilityMacros.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
carp: callCommand: clang -fPIC -lm -g ./out/main.c -o "./out/Untitled"  -I/Volumes/P3/Carp//core/  `sdl2-config --cflags --libs` -D_THREAD_SAFE  (exit 1): failed
```
You can see a couple of "Carp//core" here.

**Comment by eriksvedang** [comment]
Right, but it works now even with the extra `/`, right? I agree that it's ugly though, should probably fix it in the compiler instead, so that it checks for the duplicate there and removes it.
