### ISSUE TITLE
Entering `help` into the repl crashes it

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#437]

**Comment by hellerve** [comment]
This is because were trying to set initial types on a command function, for which it isn’t defined. I’m not quite sure whether we should fix it there or disallow not calling command functions alltogether?

**Comment by eriksvedang** [comment]
I think adding a case in InitialTypes is correct.

**Comment by hellerve** [comment]
Should it error or return the object?

**Comment by eriksvedang** [comment]
Return it I think? But I guess in the case of `help` we could actually tell the user how to call the function (since they're clearly looking for help), perhaps?

**Comment by eriksvedang** [comment]
Turns out your fix made it impossible to call help with parens :) I made a fix so it doesn't crash at least (works for all commands now) but this was a nice usability thing so we should try to get it working properly...

**Comment by hellerve** [comment]
Whoops! I’m so sorry!

**Comment by hellerve** [comment]
I can’t reproduce the crash anymore.

**Comment by eriksvedang** [comment]
No, I fixed the crash but there isn't a helpful message anymore.

**Comment by eriksvedang** [comment]
This will do for now.
