### ISSUE TITLE
Problem with loading via git

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#456]
I get this error when trying to load libraries via git (using for example `(load "git@github.com:carpentry-org/file@0.0.4")`)

```
I tried interpreting the statement as a git import, but got: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Do you know what could be up @hellerve ? This used to work for me...

**Comment by hellerve** [comment]
Did you possibly remove or change your SSH keys? Do you use Git via https usually?

**Comment by eriksvedang** [comment]
OK, that must be it. Works on my other computer so probably is something with my git setup on the first one. Thanks!
