### ISSUE TITLE
Feature Request: Provide a mechanism to document modules

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#459]
I think it'd be great if we could specify a description for modules using a form similar to `doc`, perhaps:

```clojure
(defmodule Foo
  (doc-module "Some brief description about the Foo module.")
  ;;...definitions
)
```

Or perhaps we can just extend `doc` to work on module definitions (this would, probably(?) be simpler):

```clojure
(doc Foo "A brief description of the Foo module.")
(defmodule Foo)
```

The resulting html can look something like the following, using the existing `Array` html as an example:

```html
<h1>
  Array
</h1>
<p class="module-doc">Some description of the Array module.</p>
<!--Binder descriptions-->
```

I think high-level module descriptions would help orient library users. 

What do you think?

**Comment by hellerve** [comment]
I agree, and Ive actually worked on this before. I don’t think we need a new form for this, using `(doc Module "my module documentation")` should also work! Sadly, at the moment, somewhere in the compiler the meta information for modules gets thrown away (before the docs are generated). I’m not sure when that happens yet, which is where I got stuck last time!

**Comment by eriksvedang** [comment]
I'll take a look at this! I agree that it's an important feature.

**Comment by eriksvedang** [comment]
I've fixed this now, it's in `master`. Here's how it looks: http://carp-lang.github.io/Carp/core/Dynamic.html

**Comment by scolsen** [comment]
Woo! Fantastic!

**Comment by hellerve** [comment]
This doesn’t seem to work for my modules. Is there any flag i have to enable for this to work?

**Comment by hellerve** [comment]
I got it to work! It seems like this doesn’t work if it’s used before a `deftype`.

**Comment by hellerve** [comment]
In other news, [this beautiful documentation site](http://veitheller.de/time/) is completely autogenerated!

**Comment by eriksvedang** [comment]
> It seems like this doesn’t work if it’s used before a deftype.

Can you elaborate, please? Is this a bug? :) (sure sounds like one...)

**Comment by hellerve** [comment]
This is the MVP for the bug that I can come up with:

```clojure
(doc T "My type!")

(deftype T [])

(save-docs T)
(quit)
```

Basically, the docstring `My type!` gets lost somewhere. If it’s “just” a module, this works as expected.

**Comment by eriksvedang** [comment]
Ah right, will fix.

**Comment by eriksvedang** [comment]
This is fixed in master now, so I'll close this issue!
