### ISSUE TITLE
Non-exhaustive patterns in Concretize

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#464]
When I attempt to use the following definitions, I get an error about non-exhaustive patterns in `concretize.hs`

```clojure
(def scheduled-propagators (the (Array (Fn [] ())) (zero)))                 
    ;; all propagators ever scheduled during the scheduler's lifetime.          
(def history (the (Array (Fn [] ())) (zero)))  

(defn run-alerted []                                                        
        (do                                                                     
          (clear-schedule)                                                      
          (foreach [propagator &scheduled-propagators]                          
            (~propagator))                                                      
          (if (propagators-scheduled?)                                          
              (run-alerted)                                                     
              (State.Done))))    
```

My guess is that concretize doesn't yet account for the `()` type? either that or there's something wrong in my carp code. 

Happy to look into this!

**Comment by hellerve** [comment]
Because that code refers to a bunch of things that aren’t there I can’t really reproduce the error. Do you have a small, self-contained example for reproducing?

**Comment by hellerve** [comment]
If I stub out the functions and types, the program compiles just fine, making me think that maybe the problem isn’t in the code presented:

```clojure
(def scheduled-propagators (the (Array (Fn [] ())) (zero)))                 
;; all propagators ever scheduled during the scheduler's lifetime.          
(def history (the (Array (Fn [] ())) (zero)))  

(deftype State
  (Done [])
  (Doing []))

(defn clear-schedule [] ())
(defn propagators-scheduled? [] true)
(defn run-alerted [] (do (println* "red alert!") (State.Doing)))

(defn run-alerted []                                                        
        (do                                                                     
          (clear-schedule)
          (foreach [propagator &scheduled-propagators]                          
            (~propagator))                                                      
          (if (propagators-scheduled?)                                          
              (run-alerted)                                                     
              (State.Done))))  
```

**Comment by scolsen** [comment]
Hm, that’s a hint that there’s probably just some logical error in my code that’s the root of this instance. Nonetheless, we should probably fix the non-exhaustive pattern and throw a meaningful error if we can. I’ll try to tease out the error and provide a small reproducible sample.

**Comment by scolsen** [comment]
So, here was my dumb error:

`(deftype (State a) Done (Value [a]))`

The repl/compiler treats this definition as a-ok, but will choke in a variety of ways when you attempt to use the first form as: `State.Done`.

It seems as though the particular Concretize error I encountered relies on a couple of conditions...so I'm still working on reproducing precisely that issue, but it does seem as though the root cause is the above definition of the `State` sumtype being accepted. It seems as though the concretize error is encountered if you use the invalid type definition in a particular way. I have dug into reproducing it yet, but here is the function it was hung up on (when State is defined incorrectly as I defined it above)

```clojure
    (private run-alerted)                                                                                                                               
    (doc run-alerted "Run all of the alterted propagators.")                                                                                            
    (sig run-alerted (Fn [] (State a)))                                                                                                                 
    (defn run-alerted []                                                                                                                                
        (do                                                                                                                                             
          (clear-schedule)                                                                                                                              
          (foreach [propagator &scheduled-propagators]                                                                                                  
            (~propagator))                                                                                                                              
          (if (propagators-scheduled?)                                                                                                                  
              (run-alerted)                                                                                                                             
              (State.Done))))        
```

If I had to guess it probably has something to do with the fact that [a] is not bound using `the` nor is it contextualized by a function argument.

The definition of `State` above should probably emit the `Sumtype` error like this def does:

```
(deftype Foo Nada)
Invalid type definition for 'Foo':

I failed to read `Nada` as a sumtype case at line 1, column 14 in 'REPL'.

Sumtype cases look like this: `(Foo [Int typevar])`
```

**Comment by hellerve** [comment]
We should definitely check type definitions more thoroughly before handing them off. I can do that on the weekend maybe.

**Comment by eriksvedang** [comment]
Is this bug solved? I can't reproduce.

**Comment by hellerve** [comment]
```clojure
(deftype (State a) Done (Value [a]))

(defn emit-done [] (State.Done))
```

This should be enough to reproduce the error. The error is still the first case of the sumtype.

**Comment by eriksvedang** [comment]
Thanks!

**Comment by scolsen** [comment]
Ah, so the problem is, whenever we have a type definition that has an argument like `a` we map over all of its members to replace instances of the variable, that is, each member is expected to look like:

`(Just [a...])` or `(Nothing [])` (note the empty array)  which obviously isn't the case for `(deftype (State a) Done (Value [a]))`.

In the function we use to map, we only match against `Lst` `XObjs`, but case like `Done` isn't a `Lst`. I think I know how to fix it more or less.

**Comment by eriksvedang** [comment]
Ah, that's it! Should be a one-liner...

**Comment by scolsen** [comment]
#754 has a fix!

**Comment by eriksvedang** [comment]
Thanks!
