### ISSUE TITLE
Better error messages for REPL commands

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#466]
Right now, the error messages for undefined symbols and symbols that might be actual REPL command (like `project` or `help`) are the same. Instead, they should be different: the error message for REPL commands should tell the user that they should call them instead.

Cheers

**Comment by eriksvedang** [comment]
Maybe this is a bad idea since it will complicate the code in Eval. I still think it would be a nice feature for people new to Carp.

**Comment by hellerve** [comment]
I think this is getting better already with primitives. Now primitives still aren’t first class (see #719 etc), but most of the forms are now less special. We should thus be able to resolve this once primitives are normal `Obj`s.

**Comment by eriksvedang** [comment]
Thinking about this some more it feels like it will complicate things in the evaluator unnecessarily.

**Comment by hellerve** [comment]
It’s solved already, too, because just typing `help` and `project`, for instance, prints the symbol documentation, which tells the user to call the function.

**Comment by eriksvedang** [comment]
@hellerve Ah, right! 👍
