### ISSUE TITLE
Type annotations should manipulate the type right away

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#468]
Currently, type annotations are enforced, but do not change the signature ahead of compilation, i.e.:

```
鲮 (sig f (Fn [Int Int] Int))
鲮 (defn f [x y] (+ x y))
鲮 (type f)
f : (λ [a, a] a)
```

The type is still enforced at compilation, but it’s wildly uninformative for the user not to see the correct type annotation interactively.

Instead, the type should be changed on the form right away!

Cheers

**Comment by scolsen** [comment]
This would be a great addition!

**Comment by eriksvedang** [comment]
Fixed.
