### ISSUE TITLE
Matching should work on references

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#469]
Matching is the most integral part of sumtypes. Sadly, using `match` currently takes ownership of the value, meaning that we can’t reuse it. This is annoying, since it leads to a lot of copies in `core/Maybe.carp` and `core/Result.carp`.

Matching should be possible on references. Enabling that has interesting lifetime consequences, though, since currently the matching clause gets full control over the members of the sumtype, which would be a potentially dangerous operation when using references. We might have to change the API to rely on references on the members as well, but that requires some experimenting.

Cheers

**Comment by eriksvedang** [comment]
This is fixed in branch `match-on-refs` which will be merged soon.

**Comment by eriksvedang** [comment]
It's in!
