### ISSUE TITLE
Is `local-include` needed?

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#472]
`relative-include` is a macro building on `local-include` that is strictly more powerful. Using `relative-include` means we’ll always be relative to the file we’re including from, which is invariably what we want. `local-include` is an older relic that includes relative to the C compilate’s location instead, which is never what the user would expect.

Maybe it’s time to drop `local-include`?

Cheers

**Comment by eriksvedang** [comment]
If I remove this, how many of your packages will be affected @hellerve ? Don't want to ruin everything before you're having a chance to respond.

**Comment by hellerve** [comment]
Here’s a trick to check stuff like that:

https://github.com/search?q=extension%3Acarp+local-include

This shows 10 code results, two of which are in a repo by @goodmind, four are in a repository by @titan, and four are in Carp core. In other words, none of my packages would break!

**Comment by eriksvedang** [comment]
Awesome! Thanks for the tip =)

**Comment by goodmind** [comment]
What to use instead?

**Comment by hellerve** [comment]
`relative-include` would be the alternative!

**Comment by hellerve** [comment]
Should we go ahead and remove `local-include`, then?

**Comment by eriksvedang** [comment]
Yes!

**Comment by hellerve** [comment]
I’ll take this over, then! PR incoming in a few hours.
