### ISSUE TITLE
Add .clang-format

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#499]
Would you be willing to add a .clang-format file?

**Comment by hellerve** [comment]
As for me, I’d be happy to! Anything that leads to more consistent code is a plus in my book.

That said, I don’t have strong opinions about what the “right style” looks like in C. My default would be something close to this:

```
---
BasedOnStyle: Google
AlignEscapedNewlinesLeft: 'true'
AlignTrailingComments: 'true'
AllowAllParametersOfDeclarationOnNextLine: 'true'
AllowShortBlocksOnASingleLine: 'true'
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: 'true'
AllowShortLoopsOnASingleLine: 'true'
BinPackParameters: 'true'
ColumnLimit: '80'
PointerAlignment: Left
SpaceBeforeAssignmentOperators: 'true'
SpaceBeforeParens: ControlStatements
SpacesInContainerLiterals: 'true'
Standard: Cpp11
TabWidth: '4'
UseTab: Never

...
```

**Comment by jacereda** [comment]
Is that close to the current style?

**Comment by hellerve** [comment]
As I just realized, `TabWidth` and `IndentWidth` have to be set (to 4). Then more or less, except that it seems way more aggressive in putting short functions on a single line, which I personally don’t have a problem with. Ultimately, I defer to the authority of @eriksvedang.

**Comment by hellerve** [comment]
The most heavily reformatted file seems to be `carp_pattern.h`, which is more than welcome.

**Comment by eriksvedang** [comment]
We can try this, it's probably very good to have! If it drives me crazy I'll reserve the right to change my mind.

**Comment by hellerve** [comment]
It seems pretty low-noise to me, but I’m not 100% sure. I just enjoy having a consistent codebase :)

**Comment by jacereda** [comment]
> We can try this, it's probably very good to have! If it drives me crazy I'll reserve the right to change my mind.

It's easy to change your mind in blocks, just surround them like:

```
// clang-format off
...
// clang-format on
```

Once you get used to it you'll never look back. It changes the way you program. I tend to write chunks in a single line and, upon save, they turn into the right thing.

**Comment by jacereda** [comment]
> except that it seems way more aggressive in putting short functions on a single line

Well, there're settings for that. There're settings for almost everything you can think of :)
