### ISSUE TITLE
Coerce

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#501]
Hi,

What would be the best way to implement `Unsafe.coerce :: a -> b`? Something like this could help with #494

**Comment by hellerve** [comment]
The simplest way would be probably a template that does a typecast, which could work for some types. I’m not sure how to make it “smarter” to make it work with more complex types, though.

The template could roughly look like this:

```c
<b> Unsafe_coerce(<a> inp) {
  return (<b>) inp;
}
```

That would make sense for e.g. the integral types defined by OpenGL (`GLint`, `GLuint`, `GLsizei`, et al.).

This could also work for isomorphic structs, but not really for sumtypes, which is a bit of a bummer.

**Comment by jacereda** [comment]
Great, thanks. My attempt is at https://github.com/carp-lang/Carp/pull/502

**Comment by jacereda** [comment]
Closed, https://github.com/carp-lang/Carp/pull/502
