### ISSUE TITLE
Embedded.md

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#503]
A lot of people seem interested in using Carp for embedded programming, which is awesome! To help those people we should really have a document explaining (in general terms) how to set up the toolchain (using `--no-core` and whatnot). Anyone interested in helping out with this?

**Comment by hellerve** [comment]
I think @trentgill mentioned that he had some insights into this when we spoke last.

**Comment by Immortalin** [comment]
Go and Rust use a series of Docker containers to make the cross compilation easy (including C toolchain and cross compilers). Carp can do this too.

https://github.com/karalabe/xgo/blob/master/README.md
https://github.com/rust-embedded/cross/blob/master/README.md

Setting up cross compilers can be non-trivial and waste a lot of time.

**Comment by eriksvedang** [comment]
This exists now, "just" needs to be filled in: https://github.com/carp-lang/Carp/blob/master/docs/Embedded.md
