### ISSUE TITLE
Cannot reference lowercase type names

### ISSUE THREAD

**Issue by perkinslr** [carp-lang/Carp#514]
Using lowercase type names inside type definitions throws a compiler error.  

    Invalid type definition for 'broken':

    I can’t use the type `userdata` as a member type at line 13...

If I change the type name to start with an uppercase letter, it works fine.  Also, if I try to bind the datatype to another name `(def Broken userdata)`, the compiler hangs forever.

    (deftype userdata
        [data Int]  )

    (deftype UserData
        [data Int]  )

    (deftype broken
        [udata userdata])

    (def broken userdata)
    (def Broken UserData)

    (deftype works
       [udata UserData])

**Comment by eriksvedang** [comment]
This is the desired behaviour for `deftype` since lowercase names are reserved for type variables. When registering external C types that use lowercase names that's of course a problem, I was under the impression that that's what you were trying to do? (regarding the gitter chat)

I think fixing this for `register-type` should be relatively straight forward. The behavior for `deftype` should stay the same though.

**Comment by perkinslr** [comment]
I first encountered the problem with `register-type`.  The `deftype` example was a simpler, self-contained, example of the problem.  I'm not generally in favour of artifically imposing case restrictions, but that's probably not too big a deal.  At the very least, I'd say the error message produced needs to mention that type names must start with an upper case, or better would be to throw the error at the `deftype` call rather than when trying to use the defined type.

**Comment by eriksvedang** [comment]
Definitely, very good points. The case restriction is there to allow for a way to differentiate between type variables and type names (the design is taken straight from Haskell). It leads to some problems when interacting with C types though, for sure. I'll think about how to solve this in a clean way – any ideas are welcome!

**Comment by perkinslr** [comment]
If the case restriction is to allow a distinction between type variables and type names, then leading-capital type variables need to be disabled, which does not appear to be the case.  If you're just reusing Haskell's restrictions, given that this is a Haskell-like language targeting C, that's reasonable I suppose.  I think you would get the same effect, but with a clearer solution, allowing lower case types in `deftype`, but make `deftype` itself throw an error if you try to create a lowercase type.  Then lowercase types registered from C would work as expected, and the casing errors would be thrown on the line where the problem exists.  

If you want to totally avoid lowercase types, then `register-type` should also throw an error if a lowercase type is registered.  It would probably be good to let `register-type` take another parameter to provide the C name of the type anyway (similar to how `register` does for functions), as that would let you do things like `(register-type SomeType [somefield Int] "struct SomeType")` instead of requiring a `typedef` on the C side.

**Comment by eriksvedang** [comment]
Thanks for the feedback, I agree with all of it I think. My gut feeling is to go with your second suggestion, allowing for "overwrites" of the type names when registering them. That – coupled with good error messages – seems like it would be quite clean and user friendly.

**Comment by eriksvedang** [comment]
This is solved in `master` now, `register-type` can take an alternative name for the type as a final argument (of type string).
