### ISSUE TITLE
Seamless C Interop

### ISSUE THREAD

**Issue by Immortalin** [carp-lang/Carp#518]
Zig and V has seamless C interop. I.e. pull in C headers, call c code directly without having to write a wrapper function. Zig even supports pre-processor macros. This would be a valuable addition to Carp and help solve the chicken and egg problem of libraries.

**Comment by eriksvedang** [comment]
There is actually a tool included with carp, `carpe-header-parse` that tries to do this too. Any help with making that tool better would be great! (using it and reporting bugs would be enough, really)
