### ISSUE TITLE
Type aliases

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#520]
I've noticed some references in the code to `defalias`, but looks like it was removed at some point. Was that supposed to be haskell's `type Foo = Bar`? Why was it removed, is there some other way to do that?

**Comment by eriksvedang** [comment]
Yeah, I think so... 

I guess we need something like that, right?

**Comment by jacereda** [comment]
In my case I just wanted to make `V3` an alias for `(Vector3 Float)` so I could easily change my mind and use `Double` at some point.

**Comment by scolsen** [comment]
We had some discussion around this idea earlier. I think the recommendation was to simply use macros to define the synonyms, and @hellerve defined a couple synonym-making macros that work, but there are some restrictions as to exactly where they're evaluated (e.g. they work just fine in`the` forms, but they won't work in `sigs`).

I concur that it would be nice to have some special syntax for it as Haskell does.

Here's the previous [discussion](https://gitter.im/carp-lang/Carp?at=5ce9d11975d9a575a64502bc). (hopefully the link works)

**Comment by eriksvedang** [comment]
Oh, right... Yeah I think there was some bug that made the macro solution not work, but if we fix that perhaps it will be enough? Adding in-language support for it isn't that hard I think, and leads to better errors, so perhaps that's better anyways.

**Comment by jacereda** [comment]
I'm not sure the macro solution is good enough. I would need some way to access the module enclosing the type. That is, for my use case:
```
(defalias V3F (Vector3.Vector3 Float))
```

I would also need to refer to functions like:

```
(V3F.zero)
```

So, looks like there must be something that interprets `V3F` as the `Vector3` module.

**Comment by eriksvedang** [comment]
I guess we actually need a built-in way of doing this. If anyone wants to give it a go I think it could be a fun endeavour :)

**Comment by eriksvedang** [comment]
Closing this I favor of #884.
