### ISSUE TITLE
Support Recursive Definitions in Let?

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#537]
Currently, one can't define recursive (or more specifically, self-referential) functions in a `let` form:

```clojure
(defn foo []
  (let [recursive (fn [x] (if (= 1 x) "done" (recursive 1)))]
    (recursive 0)))
```

The prior function definition results in an error, as `recursive` can't refer to itself in its body. 

Are recursive let-bindings not yet supported in carp, or is there another way to achieve this?

**Comment by hellerve** [comment]
I think we’ve talked a little bit about this in #402, and I think this issue can be classified as a duplicate.

Does the issue match your problem?
