### ISSUE TITLE
Functions taking unit type as argument emits invalid C code

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#557]
Functions taking (and returning?) the unit type as an argument, i.e. `f : (Fn [()] ())` will emit invalid C code.

**Comment by hellerve** [comment]
Should this be special-cased or forbidden alltogether?

**Comment by eriksvedang** [comment]
I think it should be allowed, it's sometimes useful.

**Comment by hellerve** [comment]
Huh, do you have examples for when it is?

**Comment by jacereda** [comment]
I think the fix is easy:

```
diff --git a/src/Emit.hs b/src/Emit.hs
index adaaff37..549a7d6f 100644
--- a/src/Emit.hs
+++ b/src/Emit.hs
@@ -733,6 +733,7 @@ toDeclaration (Binder meta xobj@(XObj (Lst xobjs) _ t)) =
 toDeclaration _ = error "Missing case."
 
 paramListToC :: [XObj] -> String
+paramListToC [XObj _ _ (Just UnitTy)] = ""
 paramListToC xobjs = intercalate ", " (map getParam xobjs)
   where getParam :: XObj -> String
         getParam (XObj (Sym (SymPath _ name) _) _ (Just t)) = tyToCLambdaFix t ++ " " ++ mangle name
```

**Comment by eriksvedang** [comment]
@hellerve I (re)discovered the bug when trying to use SDLApp with `()` as the game state, before deciding on what to really use. Instead I had to use `0` which of course works but it's a bit annoying. I also think there are a lot of cases when doing more theoretical stuff with types and so on where the "Unit-version" is the easy and most understandable (kinda like the Trivial Monad and so on).

@jacereda Will you make a pull request?

**Comment by hellerve** [comment]
Note that this fix only works if the argument list is just one unit type. I think filtering before mapping in the line below might be more general but maybe not needed.
