### ISSUE TITLE
Kind-checking of type constructors is missing

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#561]
Right now it's possible to use type constructors like `Vector3` without applying them to a type, for example:

```
(deftype Player
    [pos Vector3
     hp Int])
```

This leads to warnings about missing deleters, etc. but that misses the main point which is that the `Vector3` type must take an argument:

```
(deftype Player
    [pos (Vector3 Float)
     hp Int])
```

**Comment by eriksvedang** [comment]
So, here's an old issue that we can use for discussing how a kind checker would work, @scolsen (and anyone else who's interested, of course!)

**Comment by eriksvedang** [comment]
Ideally we could just have a (Haskell) function that goes something like `checkKinds :: TypeEnv -> Ty -> Maybe TypeError` and we can call that in a pass (in Infer.hs) just before `assignTypes` or something like that (and in `Deftype`).

My intuition is that nothing else should be needed, but I haven't thought about it much. I know that there will be quite some overlap with the existing type checking algorithm, but to avoid that we would have to go into dependent types territory (or so goes the Haskell lore). I think it could be considerably smaller though, since the kinds are less complex.

**Comment by scolsen** [comment]
> Ideally we could just have a (Haskell) function that goes something like `checkKinds :: TypeEnv -> Ty -> Maybe TypeError` and we can call that in a pass (in Infer.hs) just before `assignTypes` or something like that (and in `Deftype`).
> 
> My intuition is that nothing else should be needed, but I haven't thought about it much. I know that there will be quite some overlap with the existing type checking algorithm, but to avoid that we would have to go into dependent types territory (or so goes the Haskell lore). I think it could be considerably smaller though, since the kinds are less complex.

I'm not certain either, but that sounds like it would work to me too! I might try this out today if I get a chance.

**Comment by scolsen** [comment]
I got basic checks working, but now it's possibly too strict? 

```
[INTERFACE ERROR] RefBool.=:(λ [(Ref Bool a), (Ref Bool b)] Bool) kind mismatch
[INTERFACE ERROR] Maybe.str:(λ [(Ref (Maybe a) q)] String) kind mismatch
I couldn’t find the symbol 'Nothing' at line 9, column 8 in '/Users/scottolsen/dev/Carp/core/Maybe.carp'.
```

Basically, I'm giving any thing that takes an argument `structs, refs, pointers, and fns` a kind of `Higher` and anything else a kind of `base`.

This means a lot of the old interfaces are defined over `base` kinds since they use a single variable e.g. `([a] a)`....so I'm guessing we need to make the matching slightly more permissive. I guess solitary VarTy's should match both `Base` and `HIgher` kinds

**Comment by eriksvedang** [comment]
> I guess solitary VarTy's should match both Base and HIgher kinds

That sounds reasonable. A single type variable can be any type, even a higher kinded one.

**Comment by scolsen** [comment]
I think I got it-- it's a little weird, but it seems like the right rule to prevent erasure is that a variable cannot replace a variable (at least when it comes to interfaces, haven't looked at deftype yet).

Right now, it works:

```
(definterface fmap (Fn [(Fn [a] b) (f a)] (f b)))
(defmodule Maybe (defn fmap [f x] (match x (Maybe.Just v) (Maybe.Just (f v)) (Maybe.Nothing) (Maybe.Nothing)))) ;; works!
(defmodule Int (defn fmap [f x] (f x))) 
[INTERFACE ERROR] Int.fmap:(λ [(λ [a] b c), a] b) kind mismatch
```

**Comment by scolsen** [comment]
Unfortunately it relies on the order of the arguments insofar as the implementing signature is allowed to replace `Base` kinds with `Higher` kinds, but not vice versa...I'm not sure that there's anyway around that.
