### ISSUE TITLE
Segfault on MacOS with empty Map

### ISSUE THREAD

**Issue by TimDeve** [carp-lang/Carp#566]
I get a segfault on MacOS with both gcc and clang when I compile this example:
https://gist.github.com/TimDeve/3272f0725448444ad64fbb674192dd98

The function turns a (Map String String) into a String by doing Map > (Array Pair) > String.Concat pair > String.Concat array, the function works correctly with data in it but segfault when passed an empty map.

I have only observed this behavior on MacOS Mojave 10.14.6, it works correctly on Windows/GCC

Here is another example:
https://github.com/TimDeve/hoquet

**Comment by eriksvedang** [comment]
The gist link doesn't seem to work...

**Comment by hellerve** [comment]
I can’t reproduce this on macOS 10.14.6 with the newest version of Carp in `master`.

NB: The program has to be transformed (because `String.join` takes references now) to work there.

**Comment by TimDeve** [comment]
You're right, I was using 4f9c1500f2625f28f30ea738c6e242adad3c3989 on my Mac which is from July while the Windows one must have been more recent.
Sorry about that I should have pulled master before raising an issue.
I can't see the issue on latest on Mac.

**Comment by hellerve** [comment]
It happens! :)
