### ISSUE TITLE
Can't use `load` with SSH on Windows

### ISSUE THREAD

**Issue by TimDeve** [carp-lang/Carp#571]
Trying to load a library from a git repo using `load` and SSH on Windows fails with this error:
```
$ carp -b main.carp --generate-only
carp: CreateDirectory "C:\\Users\\myuser\\.carp\\libs\\github.com:carpentry-org\\sockets.git\\master": invalid argument (The filename, directory name, or volume label syntax is incorrect.)
```
This is the content of main.carp:
```clojure
(load "git@github.com:carpentry-org/sockets.git@master")
```

**Comment by hellerve** [comment]
I think this might be due to the colon, but I’m not sure what the restrictions are on Windows. Apologies, I don’t have a Windows machine at hand and so can’t really test the code on Windows. :(

**Comment by TimDeve** [comment]
That seems to be correct, colons are not allowed in path on Windows. Could maybe replace them by _COLON_...

**Comment by hellerve** [comment]
I’ll look at how to generally sanitize strings for Windows paths instead I think.

**Comment by TimDeve** [comment]
Happy to be guinea pig for this.
