### ISSUE TITLE
Can't use `load` with HTTP on Windows

### ISSUE THREAD

**Issue by TimDeve** [carp-lang/Carp#572]
Trying to load a library from a git repo using `load` and HTTP on Windows fails with this error:
```
$ carp -b main.carp --generate-only
I can't find a file named: 'http://github.com/carpentry-org/sockets.git'

I tried interpreting the statement as a git import, but got: fatal: Not a git repository (or any of the parent directories): .git
 at C:\Users\myuser\dev\sandbox\carpload\main.carp:2:8.
```
This is the content of main.carp:
```clojure
(load "https://github.com/carpentry-org/sockets.git@master")
```

**Comment by hellerve** [comment]
I think for now we decided on supporting SSH only.

**Comment by jacereda** [comment]
@TimDeve Can you try that PR?

**Comment by hellerve** [comment]
Oh wow, did we actually leave the `http`/`https` code in? My memory is failing me hard on this one.

**Comment by TimDeve** [comment]
@jacereda Thanks, I'll try it when I get home.

@hellerve Why was it planned to be removed, it works on Linux/Mac.

**Comment by jacereda** [comment]
I would just leave https.

**Comment by hellerve** [comment]
The problem with HTTPS is that it doesn’t work with private repos (because we don’t mirror Git’s stdout which asks for your username and password). That’s often a tad confusing. Go does the same thing IIRC.

The drawback is that this just flat out won’t work if you don’t have an SSH key associated with your Git account.

**Comment by bjorn3** [comment]
> The drawback is that this just flat out won’t work if you don’t have an SSH key associated with your Git account.

Or you dont even have an account. For example CI, or an end user of your program.

**Comment by TimDeve** [comment]
@jacereda I tried your branch, it doesn't seem to have had any effect, sorry.

**Comment by hellerve** [comment]
Is this still a problem or was this fixed with the latest changes?

**Comment by hellerve** [comment]
Clarification: it should work now, since for now we don’t strip `https:` from the final target path and the colon was most likely the problem.

The whole include path system could probably use an overhaul. I’m surprised it isn’t more of a problem already.

**Comment by TimDeve** [comment]
This is the error I get with latest:
```
carp: CreateDirectory "C:\\Users\\myuser\\.carp\\libs\\https:\\github.com\\TimDeve\\hoquet.git\\master": invalid argument (The filename, directory name, or volume label syntax is incorrect.)
```
So it seems it stills try to create a path with a colon in it.

To be fair I'm not sure it makes tons of sense to have http and https in different folders/namespaces.

**Comment by hellerve** [comment]
We didn’t use to do this, this is actually a bug. Basically, there was a check for `https:` and `http:` to be removed from the filepath, but now that we replace the colon, we actually have to check for `https_COLON_` and `http_COLON`. This regression should be fixed in #588 (could you confirm?)

**Comment by TimDeve** [comment]
Ah makes sense, will check tonight.

**Comment by TimDeve** [comment]
Happy to close the issue once #588 is merged.

**Comment by TimDeve** [comment]
Looks good 👍
