### ISSUE TITLE
About the `鲮` REPL prompt

### ISSUE THREAD

**Issue by zxygentoo** [carp-lang/Carp#578]
I'm Chinese. `鲮` as a word in Chinese means dace, not carp. The character for carp is `鲤`. In modern Chinese, these are usually written as `鲮鱼`(dace) and `鲤鱼`(carp) (`鱼` means literally fish).

There is another word `鲮鲤` means pangolin which is an armadillo like animal (I know it's confusing but nowadays Chinese people usually call pangolin `穿山甲`). 

I don't speak Japanese, but some quick search shows the Kanji character for carp should also be `鲤` (https://jisho.org/search/carp).

Maybe there are reasons I'm not aware, just provide some information I have. But in my opinion `鲤` might be better :)

**Comment by eriksvedang** [comment]
Huh, I really tried researching this when putting the character there :) But you make a convincing argument, I'll fix this..!

**Comment by zxygentoo** [comment]
Glad it helps :)

Nice work by the way. Carp is a really interesting language, love to play with it more.
