### ISSUE TITLE
Deprecate Project.set!

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#583]
`Project.set!` has been deprecated for a while, but it’s still around. I think it is time to remove it in the next release (`0.3.1`?). It would get rid of a bunch of duplicated code and general confusion.

I don’t think it would break much code as it currently stands, [and GitHub search seems to agree](https://github.com/search?q=extension%3Acarp+project-set%21&type=Code). I’ll have to fix `anima.carp`, but that shouldn’t be a big problem. (@jedahan if you want to keep your calendar experiment up-to-date this might be of interest)

Cheers

**Comment by eriksvedang** [comment]
Right on, let's do this!

**Comment by hellerve** [comment]
Anima has been updated, so I’ll remove the code and see to it that everything still works!
