### ISSUE TITLE
Windows warnings/errors

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#585]
We are getting some warnings and errors on Windows now after some of your changes @jacereda (they are good changes though, just didn't try them on Windows until now...). I'm a little unsure of the best way to solve them. Do you have any suggestions on how you'd do it?

First one:
```
In file included from .\out\main.c:18:
.//core\carp_double.h(25,5): warning: 'memcpy' will always overflow; destination buffer has size 4, but size argument is 8 [-Wfortify-source]
    memcpy(&y, &x, sizeof(double));
    ^
```

Second one:
```
In file included from .\out\main.c:21:
.//core\carp_string.h(19,5): error: use of undeclared identifier 'ssize_t'
    CHK_INDEX(i, strlen(*s));
    ^
.//core\core.h(24,18): note: expanded from macro 'CHK_INDEX'
             __LINE__, (ssize_t)i, (ssize_t)n);         \
                        ^
```

**Comment by jacereda** [comment]
The first one is probably fixed by the numeric protocols branch.
The second one should probably use `size_t` with the appropriate format (probably one of those `PRIxxx` macros in `inttypes.h`.

**Comment by eriksvedang** [comment]
This works, but is it a good idea:

```
#define ssize_t size_t
```

**Comment by eriksvedang** [comment]
Seems like the numeric protocol branch introduces some other issues on Windows, will post them in the PR discussion.

**Comment by hellerve** [comment]
I’d advise against redefining standard types, since we include core in third party libs as well.

**Comment by jacereda** [comment]
If you want to typedef ssize_t on windows you can use something like:
```
#if defined(_MSC_VER)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#endif
```
Defining it to `size_t` is bad, it must be signed.

**Comment by eriksvedang** [comment]
Right. That looks more like it!

**Comment by eriksvedang** [comment]
I think this is solved now?
