### ISSUE TITLE
Failed to open dylib: "libglfw.so.3"

### ISSUE THREAD

**Issue by acron0** [carp-lang/Carp#60]
```
#:~/p/p/carp|master✓   
➤ bin/carp
λ> (load-lisp "examples/spin.carp")
ERROR: Failed to open dylib: "libglfw.so.3"
 ----------------------------------------------------------------
  3 load-dylib                     gl.carp 9:0
  2 load-lisp                      core.carp 365:0
  1 No meta data.
  0 load-lisp                      repl 1:0
 ----------------------------------------------------------------

λ> 
#:~/p/p/carp|master✓                                                                 
➤ whereis libglfw.so.3
libglfw.so: /usr/lib/libglfw.so /usr/lib/libglfw.so.2 /usr/local/lib/libglfw.so /usr/local/lib/libglfw.so.3
```

I'm not very experienced building on Linux. Is there something I'm missing?

**Comment by honix** [comment]
I had same problem, and solve this by folllowing
https://github.com/carp-lang/Carp/blob/master/INSTALL.md#installation

Dowload libffi srcs here ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
Before ```make``` your own libffi do 

```./configure --enable-static --disable-shared```

and before ```cmake``` and ```make``` carp do  
```export PKG_CONFIG_PATH=../libffi/<ARCHITECTURE>/```
```export C_INCLUDE_PATH=../libffi/<ARCHITECTURE>/include```

Hope it helps!

**Comment by acron0** [comment]
This didn't fix the issue for me, unfortunately.

**Comment by honix** [comment]
@acron0 
I also installed some glfw package from repository, maybe solution is there.

**Comment by mkfifo** [comment]
On linux you shouldn't need to set paths manually, linux should use `pkg-config` so make sure it is  installed.

`pkg-config` will set the paths automatically for you.

@acron0 what distro are you using? do you have pkg-config installed?

**Comment by acron0** [comment]
I just reproduced this again on an different box, roughly same spec.

```
(master) λ uname -a                                                                                                                                                                                                                                                                                       (~/P/l/carp) 10:14:47
Linux acron-ubuntu 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
(master) λ cat /etc/*-release                                                                                                                                                                                                                                                                             (~/P/l/carp) 10:14:49
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
```

**Comment by mkfifo** [comment]
@acron0 notice that you are installing libffi-dev rather than libglfw-dev

@honix ahh saw you beat me to it, thanks.

**Comment by acron0** [comment]
Works now, many thanks!

**Comment by mkfifo** [comment]
@acron0 thanks for reporting back.

Closing issue as resolved.
