### ISSUE TITLE
Remove generated docs from repo

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#607]
Could the generated docs be moved to a separate repo? The CI could then commit to that separate repo to keep them updated...

**Comment by eriksvedang** [comment]
Sure, sounds good. I can create another repo for docs right away. What do I need to do more to set it up?

**Comment by hellerve** [comment]
That’s an awesome idea!

I think we need to really double down on the CI pipeline for this. We should do that anyway, though!

**Comment by bjorn3** [comment]
Maybe a gh-pages branch instead?

**Comment by bjorn3** [comment]
https://docs.travis-ci.com/user/deployment/pages/

**Comment by jacereda** [comment]
Now that we have CI active might be a good time to revisit this.

**Comment by jacereda** [comment]
I'm not sure pushing to another branch (and increasing this repo size for no reason) is the best option. A separate docs repo would be better IMHO.

**Comment by eriksvedang** [comment]
Finally this is underway – stay tuned!

**Comment by eriksvedang** [comment]
Done!
