### ISSUE TITLE
Dependency problems within set-<member>!

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#624]
It looks like `set-<member>!` doesn’t always have access to all the types it
needs when it works with nested generic types. As an example, consider the
following:

```clojure
(deftype (X a) [
  inner (Maybe a)
])

(defmodule X
  (defn broken [x y]
    (set-inner! x (Maybe.Just y)))
)

(defn main []
  (let-do [x (X.init (Maybe.Nothing))]
    (X.broken &x 2)))
```

`set-inner!` here emits `Maybe_delete___QMARK_`, which is obviously invalid.
This seems to be due to the fact that the unresolved type is emitted as `?`,
which is then mangled to `_QMARK_`. The type checker should be able to infer
the types for the `X` used here, though. I assume those constraints are not
propagated across the nesting correctly.

I’m not sure whether this is a problem within this particular function or across multiple functions.

Cheers

**Comment by eriksvedang** [comment]
This compiles fine for me now so perhaps it's fixed?

**Comment by hellerve** [comment]
Seems fine to me!
