### ISSUE TITLE
Nested, immediately-called `fn`s emit faulty C

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#629]
If I nest and immediately apply `fn`s I’m able to generate invalid C.

Take this example program:

```clojure
((fn [x] ((fn [y] (+ x y)) 10)) 11)
```

This emits declarations like the following:

```c
_Lambda_((fn _LT__GT_ [x] ((fn _LT_x_GT_ [y] (_PLUS_ x y)) 10)) 11)_10_env* _Lambda_((fn _LT__GT_ [x] ((fn _LT_x_GT_ [y] (_PLUS_ x y)) 10)) 11)_10_env_copy(_Lambda_((fn _LT__GT_ [x] ((fn _LT_x_GT_ [y] (_PLUS_ x y)) 10)) 11)_10_env* pRef);
```

which looks to me like the stringified version of the IR of the `fn`, and it’s definitely not valid C.

NB: Defining and immediately applying `fn`s might seem like a weird thing to do, but it often happens inside macro-generated code, which is where I encountered this bug.

Cheers

**Comment by eriksvedang** [comment]
whaat

**Comment by eriksvedang** [comment]
"Interesting"

**Comment by hellerve** [comment]
This seems to be fixed now!
