### ISSUE TITLE
The example for Array.reduce is incorrect

### ISSUE THREAD

**Issue by Emiluren** [carp-lang/Carp#631]
[The documentation for `Array.reduce`](https://github.com/carp-lang/Carp/blob/c2d479424674538caeb2696baee8dc4779f9c1eb/core/Array.carp#L8) has this alternative definition of Array.sum as an example:
```
(defn sum [x]
  (reduce + 0 x))
```

But this does not work since reduce passes each element by reference. So I assume the example should be something more similar to the actual definition of `Array.sum` like
`(Array.reduce &(fn [x y] (+ x @y)) 0 xs)`.

Or is the plan to change the language so that the example definition will run as it is?

**Comment by hellerve** [comment]
That one’s on me, sorry. I think that we should probably update the documentation for now. It’d be neat if you didn’t need to care about references versus owned values when doing arithmetic on integers, but were just not there yet. Would you like to update the docs or should I?

**Comment by Emiluren** [comment]
If it's ok I think it's better if you do it. I am still very new to the language.

**Comment by hellerve** [comment]
Totally fine! I added #632, you can look at the change if you want to find out how to change the documentation. Thanks again!
