### ISSUE TITLE
Syntax for static arrays

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#633]
With lifetimes kinda working (in a branch for now, it has not been merged into `master` yet) it should soon be possible to implement static arrays in a good way. My question is if they should have special syntax? Something like `[| 1 2 3 |]` perhaps? Or should the old syntax create (refs to) static arrays and then we use a function for converting those to dynamic (heap allocated) arrays? This would be more like how strings are handled (which of course *are* arrays too, so it makes sense to be consistent).

**Comment by hellerve** [comment]
I think having arrays be static by default would be a good idea, though that would have a pretty big impact on existing code, right?

**Comment by jacereda** [comment]
I would try to avoid special syntax. Maybe there's a middle ground that performs automatic conversion from static to dynamic?

**Comment by eriksvedang** [comment]
@hellerve Yeah, it would but ideally a lot of the existing literals could just be wrapped with a call to `Array.from-static` or something like that.

@jacereda Agreed, I'm not a fan of my proposed syntax either :) I think that automatic conversions are pretty scary too, but some way of helping the programmer out would be nice, for sure.

**Comment by hellerve** [comment]
Sounds good to me, actually. I’m happy to work on the stdlib in lockstep with your efforts.

**Comment by hellerve** [comment]
I have another argument against using special syntax: one of my ideals for Carp is making the compiler figure out boring details—such as whether this array should be static or dynamic—for me. The cognitive load should be produced by writing the program, not by where in memory my values reside. If I _need_ to know these things, I should be able to find out; the default should be that the compiler infers the best option according to its rules.

I’d like to optimize the compiler for that ideal; if it goes counter to some of yours, please tell me, otherwise I think this ideal pretty much rules out syntax based on implementation details.

**Comment by eriksvedang** [comment]
That's a good point. I totally agree with that the compiler should figure out stuff as much as possible and that the code the programmer ("user") writes should be as close to normal Lisp code as possible. We don't have overloaded syntax in any other place though, so that's almost another thing in my mind (although very much related of course). Basically I like non-overloaded syntax because it gives the programmer a way to pinpoint behaviour in one location (in this case the exact kind of array) and then the compiler propagates that information to the rest of the program automatically. Without any inference points it can sometimes become too hard to know those details that you refer to. So all in all I think that we agree very much in principle, but I also think there's room for interpretation of those principles :)

With that said I'm not against the possibility of overloaded syntax, it's certainly helpful and neat in a lot of situations. I think we need to be careful with it though, since it introduces even more "looseness" to the inference. I know that I've solved many refernce bugs and the like by working backwards from something known, like a string literal having the type `(Ref String)`.

It's an interesting topic and something I would be happy to discuss more!

**Comment by hellerve** [comment]
Yeah, I think this is a fundamental thing. My current mantra is: the compiler should infer as much as possible, but it should be easy to get to the information if I need it (in fact, that’s why I’ve started [pond](https://veitheller.de/git/carpentry/pond)). The compiler should expose hooks for us to get information about lifetimes, for instance, but it shouldn’t be visible by default. Does that make sense?

I’m happy to chat more about this; it’s been on my mind for a long time (my talk on Carp at CurryOn was a pretty bad attempt at explaining this mindset).

**Comment by eriksvedang** [comment]
So it seems we got a little bit of syntax anyways: `$[1 2 3]`. Still possible to change if we come up with something better, but at least you can play around with static arrays and get a feel for them.
