### ISSUE TITLE
README > Very small example fails to build on Catalina

### ISSUE THREAD

**Issue by spencerking** [carp-lang/Carp#638]
I am running a clean install of macOS Catalina 10.15.2 with Carp 0.3.0 and have been unable to build the example from the README.

The first issue is Catalina does not ship libiconv. This is an easy fix (just install libiconv) but needs to be documented alongside the other dependencies.

The second issue is `ld: framework not found CoreAudio`, which I am not yet sure how to fix.

Edit: I wonder if the second issue is a problem with nix

Edit2: It was a nix issue (https://github.com/NixOS/nixpkgs/issues/9809#issuecomment-140181430).

**Comment by eriksvedang** [comment]
Can I close this now?

**Comment by spencerking** [comment]
Yes, this is good to close.
