### ISSUE TITLE
Carp/examples/ don't all build with current release

### ISSUE THREAD

**Issue by spencerking** [carp-lang/Carp#640]
It seems that some of the examples have been updated for changes in master that have not yet made it into a release build. 

This isn't a huge deal since we know what commit the release was built from, but may confuse less git savvy users who are interested in Carp. 

I don't have a solution to propose, but it's something to think about as the project matures.

**Comment by eriksvedang** [comment]
Oh, really? We have a test suite that runs most of the examples (in `master`) so this shouldn't happen. Do you have any specific examples in mind?

**Comment by eriksvedang** [comment]
Or are you referring to the `0.3.0` release, specifically?

**Comment by spencerking** [comment]
Yes, I am on 0.3.0. I have only tested reptile.carp.

**Comment by eriksvedang** [comment]
OK. But the example included in that release works, right? It's only if you try the examples in master with the 0.3.0 binary that it explodes, I assume..? If so, I think that's fine.

**Comment by GrayJack** [comment]
Yes, there was some breaking changes, the major one was the `Array.nth` function, and in master the examples were updated. In that specific case reptile.carp, there was 3 occurrences of `Array.nth` (now `Array.unsafe-nth`)

**Comment by eriksvedang** [comment]
Right. Well this is acceptable behaviour so I'll close the issue.
