### ISSUE TITLE
Dynamic functions don't bind anonymous functions as arguments

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#660]
It's possible to get around this by simply binding every function one needs to a name, but that can be quite inconvenient at times.

A simple example:

```clojure
(defndynamic apply [f x] (f x))
(apply (fn [x] x) 1)
=> I couldn’t find the symbol 'f' at line 1, column 2 in 'REPL'.

Maybe you wanted one of the following?
    /=
    <=
    =>
    >=
    IO
    fmt
    for
    id
    or
(defndynamic id [x] x)
(apply id 1)
=> 1
```

Quoting the anonymous function doesn't solve the issue either.

Possibly related to #659 #460

**Comment by sdilts** [comment]
Was this fixed in #664 ?

**Comment by hellerve** [comment]
It seems to work now, so I guess so :)

**Comment by scolsen** [comment]
WOO! 

@hellerve the champion
