### ISSUE TITLE
Dependencies of sumtypes aren’t always correctly generated

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#671]
Sometimes dependent functions for sumtypes aren’t correctly generated. Here’s an example:

```clojure
(deftype X
  (Y [(Array String)]))

(defn main [] (println* "I do not compile"))
```

This should work, but no `str` function for `(Array String)` will be emitted, which `X` depends on, so we fail in the C compile step.

Cheers

**Comment by eriksvedang** [comment]
Ehrm, OK. Very strange that the examples doesn't already generate this error, but a good find indeed!
