### ISSUE TITLE
defdynamic in modules lead to errors in documentation generation

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#673]
When generating documentation for modules that internally use `foreach` (which as of #656 emits `gensym`s) we encounter errors related to some internal macro code. The error message always reads as follows:

```
carp: Unhandled binder: XObj {obj = Lst [XObj {obj = DefDynamic, info = Nothing, ty = Nothing},XObj {obj = Sym RESP.*gensym-counter* Symbol, info = Nothing, ty = Nothing},XObj {obj = Num Int 1001.0, info = Just (Info {infoLine = 0, infoColumn = 0, infoFile = "dummy-file", infoDelete = fromList [], infoIdentifier = -1}), ty = Just Int}], info = Just (Info {infoLine = 361, infoColumn = 34, infoFile = "/Users/veitheller/Documents/Code/Github/carp/carp/core/Macros.carp", infoDelete = fromList [], infoIdentifier = 0}), ty = Just Dynamic}
CallStack (from HasCallStack):
  error, called at src/Obj.hs:205:26 in CarpHask-0.3.0.0-HIw6hfOW0ih6jzjLFsz5xF:Obj
```

The module of course changes. What’s weird about this is that the dynamic `*gensym-counter` seems to be inlined into the module; I didn’t know that happened. This can be fixed by patching the code that fails to handle `defdynamic` objects as well, and the `defdynamic` will be visible in the generated documentation. The symbol should not however be inlined in the module in the first place.

I'm not quite sure how to best resolve this since I don’t know where the dynamic gets inlined into the enclosing module but I assume it happens somewhere in the macro code in `Eval.hs`.

Cheers

**Comment by eriksvedang** [comment]
Interesting..!

**Comment by eriksvedang** [comment]
Is this solved now @hellerve ?

**Comment by hellerve** [comment]
Yeah, this should be fixed.
