### ISSUE TITLE
Add functions to interfaces that have been defined before

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#675]
Currently functions that adhere to an interface but have been defined before the interface has been defined do not make it into the interface. This is annoying for things such as `length`, which could easily be an interface, but by the time we define it `Array.length` already has been defined and thus does not show up there. It is also problematic for “mixin” libraries that define interfaces for other types, since they then have to be loaded before everything else; I’d rather not have semantics to the load order when it comes to interfaces.

The fix should be to traverse the symbols that are already defined when an interface is encountered, and add all of the ones that match the interface.

Cheers

**Comment by eriksvedang** [comment]
Yeah, this is probably a good idea. Shouldn't be super hard to add either, one can have a look at the inverse (defining a function that adheres to an interface) and go from there.

**Comment by eriksvedang** [comment]
Should be fixed now, let me know if it works for you!
