### ISSUE TITLE
Type variables in `sig` are not unified correctly

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#685]
When using type variables in `sig` annotations, the unifier does not seem to honor naming them the same. Consider this program:

```clojure
(sig x (Fn [a a] a))
(defn x [p1 p2] p1)

(defn main [] (println* (x 10l 10)))
```

This should not compile, because both arguments to `x` are of type `a`, according to its `sig`, and we call them with `Long` and `Int`, which are both concrete and thus shouldn’t unify.

Cheers

**Comment by eriksvedang** [comment]
OK, I will make a rework of the sig macro this coming Carp Friday... they really don't do their job atm.

**Comment by eriksvedang** [comment]
This is fixed now.

**Comment by hellerve** [comment]
Neat! Thank you!
