### ISSUE TITLE
Unification in `sig` doesn’t handle indirections

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#693]
Thank you for fixing some of the issues in sig unification @eriksvedang! #685 is now fixed, but it seems like indirection still isn’t handled correctly. Consider `Phantom`:

```clojure
deftype (Phantom a) [])

(defmodule Phantom
  (sig ensure (Fn [a (Phantom a)] a))
  (defn ensure [a p] a)
)

(defn m [a] (Phantom.ensure a (the (Phantom Int) (Phantom.init))))

(defn main [] (println* (m 123l)))
```

The `a` used in `ensure` should be the same everywhere, but it seems like it’s typed as `(Fn [a b] a)`.

Cheers

**Comment by eriksvedang** [comment]
There's a fix for this in branch `fix-693` but it produces other errors (the mixup of signatures encountered by @TimDeve). So when that bug is fixed, this should be good to go (hopefully).

**Comment by eriksvedang** [comment]
This will hopefully be fixed by #819, crossing my fingers...

**Comment by eriksvedang** [comment]
Hmm, weirdly enough it doesn't seem to have solved the issue.

**Comment by eriksvedang** [comment]
Seems like there's still a bug with sigs in modules since the code for looking up sigs is separate from the code fixed in #819. Perhaps we can rely on that fix and port it over to `getSigFromDefnOrDef`.

**Comment by scolsen** [comment]
Oh, it's not so easy as a drop in solution since `existingMeta` (called by the sig code) doesn't take a context. This means that while the example here doesn't work, it should work when fully qualified, but it doesn't....because `metaSet` has the same consPathing issue! I think we can fix this.

**Comment by scolsen** [comment]
I got this to work. Types are now constrained by their signatures

Turns out there's two byte functions that violate their signatures ahah 😅 
```
I can’t match the types `(Fn [ByteOrder, (Ref (Array Byte) a)] (Array Uint16))` and `(Fn [(Ref r26 r27)] Uint16 r25)`.

  (sig unsafe-bytes->int16-seq (Fn [ByteOrder (Ref (Array Byte) a)] (Array Uint16))) : Macro
  At no info

  (fn <> [b] (Binary.unsafe-bytes->int16 order b)) : (Fn [(Ref r26 r27)] Uint16 r25)
  At line 165, column 13 in '/Users/scottolsen/dev/Carp/core/Binary.carp'
 at /Users/scottolsen/dev/Carp/core/Binary.carp:163:3.

Traceback:
(defmodule Binary (register to-int16 (λ [Byte Byte] Uint16))...) at /Users/scottolsen/dev/Carp/core/Binary.carp:69:1.
(load-once "Binary.carp") at /Users/scottolsen/dev/Carp/core/Core.carp:48:1.

I can’t match the types `(Fn [a, (Ref (Fn [b] b) d), (Ref (Fn [b] Bool) e), b] b)` and `(Fn [(Ref t14 tyvar-from-info-25_18_23), (Ref t11 tyvar-from-info-15_17_20), t13] t13)`.

  (sig iterate-until (Fn [a (Ref (Fn [b] b c) d) (Ref (Fn [b] Bool c) e) b] b)) : Macro
  At no info

  (defn Control.iterate-until [f pred start] (let [result start] (do (while (not ((deref pred) (ref result))) (set! result ((deref f) result))) result))) : (Fn [(Ref t14 tyvar-from-info-25_18_23), (Ref t11 tyvar-from-info-15_17_20), t13] t13)
  At line 15, column 3 in '/Users/scottolsen/dev/Carp/core/Control.carp'
 at /Users/scottolsen/dev/Carp/core/Control.carp:15:3.

Traceback:
(defmodule Control (doc iterate "Apply function `f` `n` time...) at /Users/scottolsen/dev/Carp/core/Control.carp:3:2.
(load-once "Control.carp") at /Users/scottolsen/dev/Carp/core/Core.carp:49:1.

Welcome to Carp 0.3.0
This is free software with ABSOLUTELY NO WARRANTY.
Evaluate (help) for more information.
鲤 (load "phantom.carp")
鲤 :i Phantom.ensure
Phantom.ensure : (Fn [a, (Phantom a)] a)
Defined at line 5, column 3 in '/Users/scottolsen/dev/Carp/phantom.carp'
鲤 
```

**Comment by scolsen** [comment]
I'll open a PR tonight!

**Comment by scolsen** [comment]
Hrm, so this problem is a bit thornier than expected. The problematic function sigs are problematic because they use a bound anonymous function. RIght now the type checker requires that an inner anonymous function have the same exact type as the enclosing function definition:

for example, here's the constraint it's solving for for `unsafe-bytes->int16-seq`

```
{(Fn [ByteOrder, (Ref (Array Byte) tyvar-from-info-0_162_47)] (Array Uint16)) == (Fn [t18] t19 t21) (ord OrdSignatureAnnotation)}
```

The second function it's comparing is a bound anonymous function `f` that has the right return type of `Uint16` in the context, but currently the type checker is trying to constrain it by the enclosing functions full type.

**Comment by scolsen** [comment]
Figured it out. Turns out we were constraining interior let-bindings by outer definition sigs as well. I've put a stop to that for now, since it doesn't seem to be correct. Now we'll only generate a `sig` constraint when the xobj we're looking at is the one that corresponds to the `sig` (the root object in the generation loop).

**Comment by eriksvedang** [comment]
Ah, that is what stumped me when I tried to fix this! Thanks so much for figuring it out.
