### ISSUE TITLE
Some examples for the new evaluator to handle

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#697]
As promised @hellerve, here are some examples of what the new evaluator / macro expander (#695) has to handle (in no particular order).

I'm not 100% sure about these. To anyone who finds an error or ambiguity – please comment below!

# Situation 1

Expanding macro in function position:

```
(defmacro DEF [] 'defn)
((DEF) f [x] (+ x 1))
```

Should be equivalent to

```
(defn f [x] (+ x 1))
```

# Situation 2

Side effecting macros:

```
(defndynamic define-constants []
  (do
    (def x 123)
    (def y 456)))

(defmacro m [s]
  (do
    (define-constants)
    (list '+ s s)))

(defn f []
  (m 666))
```

Should be equivalent to

```
(def x 123)
(def y 456)
(defn f [] (+ 666 666))
```

# Situation 3

Dynamic functions using macros:

```
(defmacro if-not [conditional x y]
  (list 'if conditional y x))

(defndynamic foo []
  (if-not true (def a 10) (def a 3.5)))
```

Should be equivalent to

```
(defndynamic foo []
  (if true (def a 3.5) (def a 10)))
```

# Situation 4

Difference between dynamic functions and macros, apart from macros not evaluating their args:

```
(defndynamic d [] (do (macro-log "hello from dynamic") 123))
(defnmacro m [] (do (macro-log "hello from macro") 456))

(defndynamic f []
  (do (d) (m)))
;; Prints "hello from macro"
;; => ()

(f)
;; Prints "hello from dynamic"
;; => 456 (because the final form in f:s do-block is the expanded 'm', which returned 456)

(defmacro g []
  (do (d) (m)))
;; Prints "hello from macro"
;; => ()

(g)
;; Prints "hello from dynamic"
;; => 456
```

# Situation 5

Macros using macros

```
(defmacro if-not [conditional x y]
  (list 'if conditional y x))

(defmacro m [x a b]
  (if-not x a b))

(m true 'AHA 'BOO)
```

Should be equivalent to

```
'BOO
```

#  Sitation 6

Calling dynamic functions inside static code

```
(defndynamic d []
  (do
    (macro-log "hello from d")
    123))

(defn f []
  (d))
;; Prints "hello from d"
;; => ()

(defn main [] (f))
:bx
;; Program returns 123
```

**Comment by eriksvedang** [comment]
I'll add further examples I come up with at the end.

**Comment by hellerve** [comment]
Thank you for this, this is super useful!

**Comment by eriksvedang** [comment]
I guess we should try to convert them into tests.

**Comment by hellerve** [comment]
I think this can be closed now!
