### ISSUE TITLE
out\main.c(1,10): fatal error: 'assert.h' file not found

### ISSUE THREAD

**Issue by damon-kwok** [carp-lang/Carp#700]
$ carp
Welcome to Carp 0.3.0
This is free software with ABSOLUTELY NO WARRANTY.
Evaluate (help) for more information.
> (defn add [a b] (+ a b))
> (add 2 3)
clang-cl: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
out\main.c(1,10): fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
carp.exe: callCommand: clang-cl.exe -D _CRT_SECURE_NO_WARNINGS out\main.c -o "out\Untitled"  -ID:/msys64/home/damon/.ome
_local/repo/carp/core/   (exit 1): failed

**Comment by hellerve** [comment]
Hello! Would you mind sharing some details about your setup? What OS and compiler are you using?

It seems like you’re running Windows. What command prompt are you using?

Also, I might add that the WIndows version of Carp is sadly extremely undertested. We appreciate you trying it out there, but you might run into trouble getting everything to work properly at this time.

**Comment by damon-kwok** [comment]
resolved：
@call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build\vcvarsall.bat" x64

**Comment by eriksvedang** [comment]
Try installing LLVM and use `clang-cl.exe` for compilation.
