### ISSUE TITLE
Unicode characters generate invalid c

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#708]
When I build the following:

`(def foo \😀)`

It generates invalid c:

```
 out/main.c:2899:15: error: character too large for enclosing character literal type
        foo = '😀';
              ^
1 error generated.
carp: callCommand: clang -fPIC -lm -g out/main.c -shared -o "out/Untitled"  -I/Users/scottolsen/dev/Carp//core/   (exit 1): failed
```

...I fuzzily recall that this used to work correctly? Everything works right in the repl as well, e.g.

`(= \😀\😀)` evaluates to `true` without a problem.

I believe this is due to the fact that we translate carp `Chars` to C's `char` type which is not large enough for unicode values. This [document](https://www.cprogramming.com/tutorial/unicode.html) recommends using `uint32` to represent characters in order to provide full unicode support.

Alternatively, we can keep Carp's types closer to their direct C equivalents and solve this in Carp itself...this is probably/possibly the right way to go for portability reasons? We would need to define a new types/functions etc. that translate Char arguments to the appropriate UInt32 type.

**Comment by jacereda** [comment]
I would stay away from uint32 and just use UTF8.

**Comment by jacereda** [comment]
Oh, never mind... you mean for single characters. A single character should probably be an uint, yes.

**Comment by jacereda** [comment]
It's probably a matter of prefixing characters with `U`. This builds for me with clang:
```
uint32_t foo = U'😀';
```

**Comment by scolsen** [comment]
> It's probably a matter of prefixing characters with `U`. This builds for me with clang:
> 
> ```
> uint32_t foo = U'😀';
> ```

Wide characters `wchar_t` work similarly--only the prefix is `L'\u2665'`--shouldn't be too tricky to add a new type for the compiler. 

What does confuse me a little, however, is that the repl can evaluate the equality comparison `=` just fine; meanwhile several other functions break on this input (e.g. prn or str).

**Comment by jacereda** [comment]
`wchar_t` can be 16 or 32 bits. Some compilers have flags to select the size.

**Comment by jacereda** [comment]
I guess the right type is `wint_t`. That's what things like `iswalnum()` and friends use.

**Comment by scolsen** [comment]
> `wchar_t` can be 16 or 32 bits. Some compilers have flags to select the size.

Right, sorry--wasn't suggesting it as an alternative, just mentioning that it works similarly. (though I actually do need to support wchar_t for ncurses bindings and having the L'' literals in carp would be nice)!

Anyway, I do think adding a distinct type and using the U prefixing is a good solution--but from a language design perspective, not sure if it's good to have two separate character types.

**Comment by scolsen** [comment]
Feels like it'd be a nicer experience just to have the one type in Carp itself and let the compiler make the right choice for you

**Comment by eriksvedang** [comment]
Can we just add `U` in front of all chars and be done with it?

**Comment by jacereda** [comment]
@eriksvedang I don't think so, looks like the `Char` type would need to be modified to be an `unsigned int` so it can hold the literal.

**Comment by eriksvedang** [comment]
Right. What should normal strings be defined as, then?

**Comment by jacereda** [comment]
Normal strings should be the same, UTF-8 encoded `char *`.

**Comment by eriksvedang** [comment]
OK, thanks!

**Comment by eriksvedang** [comment]
I tried implementing this here: https://github.com/carp-lang/Carp/tree/unicode-chars
It does not work though, but perhaps someone can see what I did wrong.

**Comment by jacereda** [comment]
My suggestion would be to stay away from wide chars. I can attempt this if you want.

**Comment by eriksvedang** [comment]
Yes please :)
