### ISSUE TITLE
Eval buffer in REPL does not emit main(), fails to compile

### ISSUE THREAD

**Issue by adityaathalye** [carp-lang/Carp#713]
This issue is seen as of SHA 84403988

With reference to `examples/arrays.carp`

Eval buffer in REPL (bound to `C-c C-l` in emacs) fails to generate main() in examples/out/main.c causing the clang compile step to fail. 
* This is independently reproducible and has been confirmed by @hellerve
* I can call (ex1) and (ex2) from the REPL and they work
* However, calling (main) from the REPL fails and the inferior carp process exits
* The `examples/out/main.c` file shows ex1() and ex2() generated along with the structs and includes, but does not have main()

I can further confirm that:
* `carp -x examples/arrays.carp` works and produces the expected output.
* Build-and-run (bound to `C-c C-c` in emacs) works and produces the expected output, in the inferior Carp process. 
* The fat binary generated by build-and-run at `example/out/Untitled` also successfully runs standalone and produces the expected output.

**Comment by hellerve** [comment]
Thanks for looking into this!

I just want to add that I can confirm this in any Carp REPL, not just in emacs. Calling `(main)` will result in emitted C code that is missing its `main` function, weirdly.

**Comment by adityaathalye** [comment]
I don't know why the issue got closed. I must have fat-fingered something.

**Comment by adityaathalye** [comment]
I just tried this out... looking good. Thanks!
