### ISSUE TITLE
`Dynamic.or` and `Dynamic.and` should be primitives

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#718]
Historically, `Dynamic.or` and `Dynamic.and` have been special forms, since they do not evaluate their arguments. There is no reason for this anymore, since primitives behave in exactly that way since #695.

Making these forms primitives would allow us to use them in higher-order functions.

It would require a bit of work inside `makePrim` to make this work, since it does not expect a module path now. This should be a fairly minor change, though.

I’d be happy to take this on.

Cheers

**Comment by hellerve** [comment]
This also affects #549 (although there’s a workaround).

**Comment by eriksvedang** [comment]
Sounds good.
