### ISSUE TITLE
Dynamic.String.join and String.join are inconsistent

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#720]
`String.join` has the pseudo-signature

```
(String.join [String (Array String)] String)
```

while `Dynamic.String.join` has the signature

```
(Dynamic.String.join [(Array String)] String)
```

Which is the same as `String.concat`

This difference isn't a huge deal, but it does make it a little harder to determine what the right inputs are to either variant based on the definition of the other. Perhaps we should rename `Dynamic.String.join` to `concat` to better mirror the `String` module?

**Comment by eriksvedang** [comment]
Oh, that's no good!  I agree this should be corrected. 

So we should probably rename `Dynamic.String.join` to `Dynamic.String.concat`?  
And `String.join` could use the Haskell name of `String.intercalate`.
That will free up the name `join`, which is good I guess..?

**Comment by eriksvedang** [comment]
Or actually there is a third `join`, `Dynamic.Symbol.join` which works on symbols. Maybe it should be called `concat` too actually.

**Comment by scolsen** [comment]
Cool, I like your proposal!

So we'd do the following renames:

`Dynamic.String.join -> Dynamic.String.concat`
`Dynamic.Symbol.join -> Dynamic.Symbol.concat`

Freeing up the name `join` would be good for me in particular since I'm going to add some monad stuff to my higher-kinds library...but I probably shouldn't be selfish :P

The nice thing about `join` is that it's a simpler word and easier to understand than `intercalate`, we can always use some alternative word for Monad stuff like `merge` or something.

So I'm ok with keeping `join` in place, but totally up to you!

**Comment by hellerve** [comment]
I’m not a big fan of the name `intercalate`, personally; I think it is unnecessarily long and esoteric. Keeping consistency with Haskell would be nice, but I think `intercalate` makes more sense with lists than with strings. That strings are lists of characters in Haskell is a happy accident, but I don’t believe it’s necessarily a name that translates well there.

**Comment by eriksvedang** [comment]
True, it's a weird word. So do you suggest we use `join` for that kind of function, or something else @hellerve ?

I do agree with @scolsen that saving `join` for the monads is tempting :)

**Comment by hellerve** [comment]
I think `join` makes sense. It can be used both by monads and strings for different purposes, as long as it’s in different modules, right? Or is the problem that `join` would be an interface and `String` would (likely) not adhere to it?

**Comment by eriksvedang** [comment]
Since interfaces are somewhat like typeclasses I think that would be the problem, yes.
Something like `join-with` could maybe work?

```(join-with ", " numbers)```

**Comment by hellerve** [comment]
If we’re going down that route, how about `join-by`?

**Comment by eriksvedang** [comment]
Either one is fine by me, I'll let the native English speaker decide then :)

**Comment by scolsen** [comment]
I'd avoid `join-by` and `join-with` if possible because I think it muddles the meaning slightly. If I had to pick between the two, I'd pick `join-with`, just because the phrase `join by` is usually followed by an instruction in english, which makes me think it'd take a function e.g. `*join* the results *by* taking the first, splitting it, and....etc.`; this makes me feel `join-by` should take a function that performs some operation on an each string in an array before concatenating them (i.e. `concat . map f`. 

Sorry to waffle back and forth on this, but I think I'd lean toward keeping `join` for Strings and figuring out some alternative for monads if and when we get there.

Using `join` for this String function is pretty common, Rust, Python, Go, Javascript, Clojure, and I'm sure others, all use `join` to mean what we mean here. 

I think it'd be better to reserve it for this use--it may potentially cause problems with monads, but to be honest, I don't think `join` is actually even the best name for the monad function, even though it happens to be its historical name. I think there are plenty of alternatives for expressing what `monad.join` does that wouldn't be accurate for `String`, for example, `Monad.join` could easily be renamed `flatten`, `merge`, `combine`, or something similar, whereas `flatten` wouldn't work for the `String` case at all, `merge` would be a stretch, and `combine` might be ok.

I also anticipate less people using monadic stuff in carp than use the `String` functions, so after some thought, I'd vote for keeping `join` for `String`.

Another alternative is `String.combine` which would be novel (no other programming languages really use this term as far as I can tell) but to me makes sense and is basically synonymous with the meaning of `join` in this case.

**Comment by eriksvedang** [comment]
OK, so lets rename the dynamic functions to `concat` and keep the `String.join` then. I kinda like `combine` too, but it's probably to surprising and hard to find to be worth it.

**Comment by eriksvedang** [comment]
This is fixed in master now, let me know if I got it wrong :)
