### ISSUE TITLE
New evaluator can't access top-level interfaces

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#721]
This should reproduce the issue:

1. Define an interface at top level, outside modules
2. implement the interface in a single module
3. call the interface function, unprefixed against a value
4. Carp spits out `can't find symbol <interface>`

Calling the function with a module prefix makes it work as expected, as does calling it without any prefix in the body of another function.

Here's the code I ran into the issue with:

```clojure
(defn p [x] (+ 1 x))
(definterface fmap (Fn [(Ref (Fn [a] b)) (Constructor a t)] (Constructor b t)))

(defmodule Maybe
(defn fmap [f maybe-constructor] 
    (match maybe-constructor
      (Constructor.App x b) 
        (match b
          (MaybeBrand.Just) (Constructor.App (~f x) (MaybeBrand.Just))
          _ (Constructor.App (~ f x) (MaybeBrand.Nothing)))))
)

(fmap &p (Maybe.constructor (Maybe.Just 4)))
;; => Can't find symbol 'fmap' at REPL:1:2

(Maybe.fmap &p (Maybe.constructor (Maybe.Just 4)))
;; => (App 5 (Just)) yay!

(defmodule Functor
  (defn replace [x f]
    (fmap &(const x) f))
)

(Functor.replace \a (Maybe.constructor (Maybe.Just 3)))
;; => (App \a (Just)) Works just fine!
```

I've confirmed that the problematic case `(fmap &p (Maybe.constructor (Maybe.Just 4)))`, the naked call at top level, worked as expected without module prefixes prior to the new Evaluator

Hopefully some info just isn't being passed to the REPL and this is a quick fix!

**Comment by scolsen** [comment]
I've also confirmed it works just fine if it's evaluated as the argument to another call:

```clojure
(Maybe.construct (fmap &p (Maybe.functor (Maybe.Just 3))))
```

So, it's only when it's the outer form in a top level call that causes problems.

**Comment by hellerve** [comment]
Good catch! I was able to reproduce this using you higher kinds package (before that I couldn’t resolve a bunch of symbols used in the  example).

This seems to be a problem with symbol lookup and concretization. I’m not quite sure what’s missing there, but I traced down the code path and I’d like to talk to @eriksvedang about whether a concretization step is missing somewhere.

**Comment by eriksvedang** [comment]
Huh, interesting bug. I'll take this on, seems like I have just forgotten to do something easy...

**Comment by hellerve** [comment]
I think concretization is done after the first eval (and `eval` fails in the lookup stage). Maybe this jsut needs to be turned around? Or `eval` needs to become `macroExpand`?

**Comment by eriksvedang** [comment]
Perhaps you're better suited to figuring this out now, @hellerve :)

**Comment by eriksvedang** [comment]
Or we could try to debug it together? @hellerve

**Comment by hellerve** [comment]
Yes please! I was unable to figure out where and when to concretize. Maybe on Friday?

**Comment by eriksvedang** [comment]
@hellerve It's a date!

**Comment by eriksvedang** [comment]
After a nice hacking session with @hellerve this is now resolved!
