### ISSUE TITLE
Incorrect parenthesis placement results in infinite loop

### ISSUE THREAD

**Issue by sdilts** [carp-lang/Carp#729]
The following code produces an infinite loop in the compiler:
``` clojure
(defn test [)
   (prn "Infinite loop!"))
```
Notice that the error is that the argument array is closed with a parenthesis and not a bracket.

**Comment by hellerve** [comment]
Hey, good catch!

Actually, it seems like this does not produce an infinite loop in files. What’s happening is that the bracket/parens matcher that determines whether you’re doing multiline or single-line input is getting tricked into thinking the input will continue. It seems as if typing `]` doesn’t resolve it either.

**Comment by hellerve** [comment]
Ah, because of the way the balance parser works, you’ll have to first close the bracket, then the paren. Typing `])` should work. This kind of behavior makes sense, but a guide might help here.

**Comment by eriksvedang** [comment]
Will close since this isn't a bug as much as a usability problem (which is greatly eased by enabling the fix in #730, perhaps it should be on by default though?).

**Comment by eriksvedang** [comment]
Oh, it is on by default! Nevermind then :)
