### ISSUE TITLE
envWithArgs fails on certain inputs

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#73]
When trying to compile this—faulty—program:

```
(use Array)

(defn add-int [&x &y] (Int.+ (Int.copy x) (Int.copy y)))

(defn main []
  (do (println (Array.reduce add-int 0 [1 2 3 4 5]))))
```

the compiler dies with the error `carp: src/Obj.hs:433:29-104: Non-exhaustive patterns in lambda`. The line is `envWithArgs`, where a pattern match occurs in a lambda that is not exhaustive.

The line of the above program that triggers the bug is `(defn add-int [&x &y] (Int.+ (Int.copy x) (Int.copy y)))`. Typing this in a REPL will also cause a crash.

Cheers

**Comment by eriksvedang** [comment]
Ah, it's the '&' in the parameter list. Thanks for pointing this out. Eventually that syntax will work also, but for now it shouldn't crash at least.

**Comment by hellerve** [comment]
In that case I’ll close this issue for now.
