### ISSUE TITLE
Regression after recent commits.

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#731]
After pulling from the latest master, I can't use lambda's as member types:

```
out/main.c:10088:36: error: initializing 'void *' with an expression of incompatible type 'Lambda'
        Lambda _13 = { .callback = f, .env = NULL, .delete = NULL, .copy = NULL }; //Sym f Symbol
```

I've confirmed that there's no issue as of commit de8104eb--the problem arose someplace after that commit.

**Comment by eriksvedang** [comment]
Thanks, will investigate!

**Comment by scolsen** [comment]
Looks like the code that's crashing here runs fine up until commit e96259fe
