### ISSUE TITLE
How to implement a custom `delete`

### ISSUE THREAD

**Issue by linkpy** [carp-lang/Carp#737]
I'm working on a binding for Godot's GDNative interface. I'm able to register the functions, but they uses opaque structures that I can't instantiate with Carp code, so I need to make the structure inside some C code. I want the object to follow the lifetime concept, and thus call `delete` when they are dropped.

Here is my code : 

~~~~~~carp
(load "./src/core/inline-c.carp")

(add-cflag "-Iout/")
(inline-c "
#include <stdio.h>

typedef struct {
  int v;
} MyType;

MyType MyType_init() {
  printf(\"INIT\n\");
  MyType r;
  r.v = 0;
  return r;
}

void MyType_delete(MyType t) {
  printf(\"DELETE\n\");
}


")
(register-type MyType)

(defmodule MyType
  (register init (Fn [] MyType))
  (register delete (Fn [MyType] ()))
)

(defn main []
  (let [v (MyType.init)]
    (IO.println "in let")))
~~~~~~

The `inline-c` macro simply generates a `.h` file which is then included :

~~~~~~carp
(defdynamic *c-counter* 0)

(defndynamic inline-c [s]
  (let [f (Dynamic.String.concat [(Project.get-config "output-directory") "/"
                                  "carp_inline_c_generated" (str *c-counter*) ".h"])
        i (Dynamic.String.concat ["carp_inline_c_generated" (str *c-counter*) ".h"])]
    (do
      (write-file f s)
      (set! *c-counter* (inc *c-counter*))
      (system-include i))))
~~~~~~

By using `(register-type MyType)`, the delete function is never called, the console output is 

~~~~~~
INIT
in let
~~~~~~

I tried to use `(deftype MyType)` but since it generates a struct definition in the .c file, I can't use it in the `inline-c` macro (because it is included before the declaration of the structure) and I can't define it either (otherwise the compiler complains about duplicate declaration).

I see that `String` has `init` and `delete` in C and for this one the delete function is called. How was it managed ? I'm unable to find anything related to that in the core files.

**Comment by hellerve** [comment]
We currently do not call `delete` on external (i.e. C) types. I see how this is often desirable, though, and I think adding support for this should not be too hard.

**Comment by linkpy** [comment]
For now the way to implement automatic foreign memory freeing would be to make a wrapper type defined in Carp which can use the `delete` mechanic, right ? 

I think it is actually possible but there's is a warning notifying the user that `delete` is redefined.

For example, something like that : 

~~~~~~lisp
(deftype MyType [v Int])

(defmodule MyType
  (defn delete [o]
    (IO.println "in delete")))

(defn main []
  (let [v (MyType.init 0)]
    (IO.println "in let")))
~~~~~~

Sadly, for this example I have the issue #738. But I remember having a warning when a function was redefined. Maybe allowing the code to provide custom `init`/`delete` ? Or maybe something like Rust's `#[derive(...)]` macro. As in, by default not generating any functions for a type, and using this macro to automatically generate "generic" functions for a given type and/or for some (or all) of its fields.

**Comment by eriksvedang** [comment]
> I'm working on a binding for Godot's GDNative interface.

Very cool!

Sorry about the bug, I'll investigate after the weekend. Creating a wrapper type is probably the best option for now, but yes, we could definitely add support for deleting external types too. 

I don't remember the exact implementation details now, but it could probably be done with a little bit of meta data or something like that. I guess the most flexible thing would be to be able to set the name of the function to be called when the value is dropped?

**Comment by linkpy** [comment]
Most of the time (depending on the library of course), the initialization of a structure is done through a C function (in the case of gdnative, every structure is created like that) which make the structure actually unusable in Carp directly without a helper `.h` file.

When I tried to do it, I first searched a bit in the carpentry and found that : https://github.com/carpentry-org/dynlib/blob/master/dlfcn_helper.h

Here is the important part : 

~~~~~~c
Lambda* DynLib_dlsym(void* l, char* f) {
  void* cb = dlsym(l, f);
  if (!cb) return NULL;
  Lambda* x = malloc(sizeof(Lambda));
  x->callback = cb;
  x->env = NULL;
  x->delete = NULL;
  x->copy = NULL;
  return x;
}
~~~~~~

If something like that is implemented, i think it would be best to think it from the C side (unless it's possible to define custom `init` functions for types (including FFI ones) and the ability to create uninitialized structures, in that case the C-side wouldn't be relevant, as everything could be done from Carp itself.

As an example : 

~~~~~~c
typedef struct {
	uint8_t _dont_touch_that[GODOT_STRING_SIZE];
} godot_string;

void GDAPI godot_string_new(godot_string *r_dest);
~~~~~~

This structure can't be initialized from Carp for the current version, a helper must be made, looking something like that : 

~~~~~~c
godot_string GDString_new() {
    godot_string r;
    godot_string_new(&r);
    return r;
}
~~~~~~

From the top of my mind, my "idealized" version of that function would be :

~~~~~~lisp
(register-type godot_string)
(register godot_string_new (Fn [(ptr godot_string)] ()))

(defmodule GDString
  (defn new []
    (let [r (uninit godot_string)]
      (godot_string_new (address r))
      r)))
~~~~~~

For that piece of code to work, only the addition of a `uninit` commad/dynamic/macro would be needed. 

I opened #739 to be able to discuss that idea more in details. This issue should remains only for the bug described above.

**Comment by linkpy** [comment]
> Creating a wrapper type is probably the best option for now, but yes, we could definitely add support for deleting external types too.

I experimented a bit with that idea but I encounter an issue :

~~~~~~
Invalid type definition for 'GDString':

I can’t use the type `godot_string` as a member type at line 4, column 28 in '/home/linkie-pi/Documents/devel/carp/gdnative-carp/src/gdnative/string.carp'.

Is it defined and captured in the head of the type definition?

Traceback:
(deftype GDString [inner godot_string]) at /home/linkie-pi/Documents/devel/carp/gdnative-carp/src/gdnative/string.carp:4:3.
(defmodule GDNative (deftype GDString [inner godot_string]) ...) at /home/linkie-pi/Documents/devel/carp/gdnative-carp/src/gdnative/string.carp:3:2.
(load "gdnative/string.carp") at /home/linkie-pi/Documents/devel/carp/gdnative-carp/project.carp:20:1.
(load "project.carp") at REPL:1:1.
~~~~~~

It seems like it's not possible to wrap a C-type within a Carp-type, or maybe I'm missing something ? What does "captured" mean in that context ?

**Comment by linkpy** [comment]
> I guess the most flexible thing would be to be able to set the name of the function to be called when the value is dropped?

For that point I dont think it's necessary. Maybe the simple presence of a function `delete (Fn [MyType] ())` would be enough to tell the compiler that `MyType` can be dropped. Or, to give more flexibility :

~~~~~~lisp
(register-type MyType)

(droppable MyType)

(defmodule MyType
  (defn delete [o] ...))
~~~~~~

`droppable` would just be a macro that writes a meta for the given type to true, telling the compiler the type should follow that lifetime mechanism ?

**Comment by hellerve** [comment]
> It seems like it's not possible to wrap a C-type within a Carp-type, or maybe I'm missing something ? What does "captured" mean in that context ?

That is possible, the problem here is that the type is lower case, and by default is read as a type variable (which you would capture in the type head, thus the error message).

Did you register the type `godot_string` before using it here?

**Comment by hellerve** [comment]
Ah, it seems that it is read as a type variable even after registering/defining. That smells like a bug to me.

**Comment by linkpy** [comment]
> That is possible, the problem here is that the type is lower case, and by default is read as a type variable (which you would capture in the type head, thus the error message).
Oh, that could cause some bugs indeed.

> Did you register the type godot_string before using it here?
Yes. The example code I send contains the `register-type` method.

So for this particular example, adding a `typedef godot_string GodotString;` and using `GodotString` should work ?

**Comment by hellerve** [comment]
That’s how I’ve been doing it in the past. I added #741 to make this cleaner, though!

**Comment by eriksvedang** [comment]
With the fix for typedef:ing external types, does your custom deleter work now?

**Comment by linkpy** [comment]
I tried and no it still does not work. The `(register-type Name "c_name")` doesn't make the type managed so the custom `delete` is not called when the variable is dropped.

**Comment by eriksvedang** [comment]
Right.

**Comment by eriksvedang** [comment]
We have a bunch of variations on this issue, so I’ll close this one.
