### ISSUE TITLE
[Proposal] Custom `init` and `delete` for types

### ISSUE THREAD

**Issue by linkpy** [carp-lang/Carp#739]
I'm opening that issue to discuss the addition of custom `init` and `delete` (also other automatically defined functions for structs, like `str`, `copy`, accessors, etc).

For now, it's possible to redefine these functions : 

~~~~~~lisp
(deftype MyType [v Int])

(defmodule MyType
  (defn delete [o]
    (IO.println "in delete")))

(defn main []
  (let [v (MyType.init 0)]
    (IO.println "in let")))
~~~~~~

(note: for me this code doesn't work, as mentioned here https://github.com/carp-lang/Carp/issues/737#issuecomment-622999750) This code should work, but should also generate a warning because `delete` is redefined (this warning is generated for each redefinition), showing this is not intended.

In the mentioned comment above, I gave the given idea : 

> Maybe allowing the code to provide custom init/delete ? Or maybe something like Rust's #[derive(...)] macro. As in, by default not generating any functions for a type, and using this macro to automatically generate "generic" functions for a given type and/or for some (or all) of its fields.

In my opinion, since Carp is low level, i think it should give as much controls to the developer as possible, and limits side-effects. I think that  `(deftype MyType)` (as an opaque type, or as a struct with fields) should actually define no methods at all. At this point, it wouldn't be possible to create a variable of that type, except if a macro/command `(uninitialized MyType)`, returning `MyType`, is added. 

As an example to illustrate what would that command do :

~~~~~~lisp
(let [myvar (unintialized MyType)]
    ...)
~~~~~~

This code would be equivalent to : 

~~~~~~c
MyType myvar;
...
~~~~~~

If the developer wants the "default" generated functions, he could just then use the macro/dynamic `(derive MyType ...)` :

~~~~~~lisp
(deftype MyType [v Int])
(derive MyType
  copy delete init prn str
  (set v) (set! v) (update v) (accessor v))

; Or maybe include it in the `deftype` directly, which I guess would require more work than making a new command or macro : 

(deftype MyType 
  ; list of fields
  [v Int]
  ; list of derivations
  [copy delete init prn str
   (set v) (set! v) (update v) (accessor v)])

; since this list of derivation is pretty common, a shortcut could be made : 

(deftype MyType
  ; list of fields
  [v Int]
  ; list of derivation
  [standard])
~~~~~~

That example shows two different `derive` macro : 

1. Per-structure derivation : derive a function for a whole structure.
2. Per-field derivation : derive a function for one or more fields.

This approach adds another issue : without the automatically generated functions, I do not think there is a way to access a field of a struct without a C helper file. Thus, it requires the addition of a few other commands :

1. `(set-field var field-name value)` where `var` would be a binding of type `MyType` (+ maybe a `Ref` variant)
2. `(get-field var field-name)` ditto

Example :

~~~~~~lisp
(deftype MyType [v Int])

(defn main []
  (let [myvar (uninitialized MyType)]
    (set-field myvar v 42)))
~~~~~~

I do not know how hard it would be to define such commands and maybe it could be done in another way. I assume these commands will have to know the type of `myvar` to be able to check if a field `v` actually exists in that type.

Maybe it could be shifted into some kind of reader macro :

~~~~~~lisp
(deftype MyType [v Int])

(defn main []
  (let [myvar (uninitialized MyType)]
    (set! myvar:v 42)))
~~~~~~

That kind of syntax could make it more trivial to access and use fields but it raises the issue of privacy : a module could define an accessor/setter private for a given field. Maybe the same syntax could be used here :

~~~~~~lisp
(defmodule MyModule
  (deftype MyType [v Int])

  ; Defines the field `v` of MyType to be private to that module.
  (private MyType:v)

  (sig set-v (Fn [&MyType Int] Int))
  (defn set-v [o v]
    (set! o:v v)))

(defn main []
  (let [myvar (uninitialized MyType)]
    (do
      (MyModule.set-v myvar 42) ; OK
      (set! myvar:v 24)))) ; NOK
~~~~~~

Finally, I think that these ideas should be usable for C-types (`register-type`) and Carp-type (`deftype`). It would allow the developer to avoid boilerplate code for wrapping a C-type into a Carp-type to be able to use the lifetime mechanism. For example, a C-type with an associated `delete` function would make instances of that C-type to use the lifetime mechanism.

**Comment by ManlyArix** [comment]
WE ARE ALL IN A WORLD OF POLITICAL SUBSTITUTION

**Comment by hellerve** [comment]
I’ve definitely wished for a feature like this in the past, and I think it’s very useful.

I do think this proposal conflates multiple features, though:
1) Proper support for custom initializers and deleters,
2) a change of the getter/setter syntax, and
3) a derive mechanism.

I don’t believe those are necessarily linked. I personally am in favor of 1) and 3), but not of 2), since I think the current mechanism of autogenerating accesor and updater functions are adequate, and I think those functions should always be generated, because they are rarely if ever not useful.

Making a field private is also already possible with the old syntax. Let me demonstrate the “trick” for that using your type:

```clojure
(deftype MyType [v Int])

(defmodule MyType
   (private set-v)
   (private set-v!)
   (private update-v)
)
```

The autogenerated functions can be marked as private like any other functions. If you want to enforce using a certain constructor rather than `init`, something similar can be used:

```clojure
(deftype MyType [v Int])

(defmodule MyType
   (private init)

   (def default 10)

   (defn new [] (init default))
)
```

I think that mechanism is fairly elegant.

**Comment by linkpy** [comment]
The issue with the automated functions is when you need to have custom one, which requires redefining the function. I didn't really proposed to change the getter/setter syntax, just add a "low level" syntax that doesn't require a function. Currently, if you want to do a custom setter/getter :

~~~~~~lisp
(deftype MyType [_v Int])

(defmodule MyType
  (private set-_v)
  (private set-_v!)
  (private update-_v)
  (private _v)

  (defn set-v [o v] ...)
  (defn set-v! [o v] ...)
  (defn update-v [o fn] ...)
  (defn v [o] ...))
~~~~~~

In my opinion it adds boilerplate code. If you just want to modify the getter, you still need to rename the field and rewrite each setter/getter or go for the unintended way : redefine the function.

> The autogenerated functions can be marked as private like any other functions. If you want to enforce using a certain constructor rather than init, something similar can be used:

This indeed works, but only if you are able to construct the struct's fields. In the case of a foreign opaque data-type, you can't use `init` :

~~~~~~lisp
(register-type MyForeignType)

(deftype MyType [v MyForeignType])

(defmodule MyType
  (private init)

  (defn new []
    (init ...))) 
~~~~~~

You can't construct `MyType`, because you have no way to construct `MyForeignType` unless you write a C helper functions. That's why I propose a "low level" field acces syntax and a way to create uninitialized structures, to allow these situations to be done fully in Carp.

> I do think this proposal conflates multiple features, though:

Yes :

1. A way to create uninitialized memory (uninitialized structures) for Carp-types and C-types.
2. A way to choose what method should be generated or not for Carp-types and C-types by using some kind of macro system, which would allow the developer to define custom generated functions.
3. A way to manipulate a struct's field without requiring functions for Carp-types and C-types.

These three points share a common point : allowing the usage of nearly all structures C-struct without needing to add C helper functions, however these structures are declared or used in the C library using them.

**Comment by TimDeve** [comment]
@carp-lang/maintainers Do we feel this is covered by the recent changes?

**Comment by eriksvedang** [comment]
I think so. It's not exactly the same, but we need more precise issues moving forward on this feature.
