### ISSUE TITLE
Allow aliases for registered types

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#741]
We are currently able to alias C functions to make them more manageable in Carp:

```clojure
; given this C function
(inline-c "
int my_fun_function() { return 1; }
")
; we can do
(register my-fun-function (Fn [] Int) "my_fun_function")
```

This ensures that we keep consistent naming convention across language boundaries.

This is currently not possible with types, and it’s a bit of an annoyance. Consider a type like `godot_string`, mentioned int #737:

```clojure
; i can register it
(register-type godot_string)
; but i cant use it
(deftype MyWrapper [
  inner godot_string
])
; this will be read as a type variable and blow up!
```

We could relax our naming conventions, but I don’t think this is a good solution. Instead, in the spirit of what we can do for types, we should be able to do this:

```clojure
(register-type GodotString "godot_string") ; with optional members before

(deftype MyWrapper [
  inner GodotString
])
```

Since we already have a mechanism for this, this shouldn’t be _too big_ of a change. I’d be open to contributing it!

cc: @linkpy because he reminded me that this is an issue, and because it also gives some context to the problem he’s experiencing.

Cheers

**Comment by eriksvedang** [comment]
Sounds like a great first step towards solving the problems described in #737 !

**Comment by linkpy** [comment]
I started working on implementing C-type aliases : https://github.com/linkpy/Carp/tree/c-type-aliases

But to be honest I'm not entirely sure what I'm doing (I dont know much about Haskell). What I did is basically handle `ExternalType` the same way as `External` is handled : `ExternalType (Maybe String)`. For now the project compiles, and I think when emitting C code, a `ExternalType (Just String)` uses `LookupGlobalOverride` to emit the right type name.

But I encountered some issues (which I think is the reader for the `register-type` syntax ?) : https://github.com/linkpy/Carp/blob/e73534dede586cfd68ad57d9313181807450364e/src/Primitives.hs#L208
This line generates the following error and I'm not sure why exactly. Futhermore I'm not even sure it's the right place or the right way to do it.

~~~~~~
/home/linkie-pi/Documents/Carp/src/Primitives.hs:208:1: warning: [-Woverlapping-patterns]
    Pattern match is redundant
    In an equation for ‘primitiveRegisterType’:
        primitiveRegisterType _ ctx [XObj (Sym (SymPath [] t) _) _ _, ty, XObj (Str override) _ _] = ...
    |
208 | primitiveRegisterType _ ctx [XObj (Sym (SymPath [] t) _) _ _, ty, XObj (Str override) _ _] = do
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
~~~~~~

Maybe this isn't the right place to talk about that ? Should I make a PR for that part specifically ?

**Comment by hellerve** [comment]
Yeah, a PR would be great. The pattern match does not work, because the pattern before it in line 190 matches a variable number of arguments as `members` ([here](https://github.com/linkpy/Carp/blob/e73534dede586cfd68ad57d9313181807450364e/src/Primitives.hs#L190)). That will prevent the pattern matcher from even considering the pattern below.

**Comment by linkpy** [comment]
Pull request merge, this issue can be closed.
