### ISSUE TITLE
[Question] Explicitly Implemented or Scoped Interfaces?

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#758]
Right now, any function that shares a name with an interface is considered a potential implementation of that interface. This can lead to some clashes. Consider:

```
(doc empty                                                                                                                                                                                  
  "The identity of choice.")                                                                                                                                                                
(definterface empty (Fn [] (f a)))
```

When we load this interface, the following error occurs:

```
carp: [INTERFACE ERROR] Bucket.empty : (λ [] (Bucket a b)) doesn't match the interface signature (λ [] (f a))
CallStack (from HasCallStack):
  error, called at src/Primitives.hs:413:17 in CarpHask-0.3.0.0-5ZhYmqzW9hmAQ94u8eHNWx:Primitives
```

Because `Bucket` happens to already define a function `empty` that has the same name as our interface.

In large programs, the possibility of this occurring increases. I'm wondering if we should consider adding a way to make interface implementations more explicit to avoid these kinds of problems? 

One possibility: instead of taking the declaration of the binding itself to be an interface based on name alone, we require an additional call:

```
(defn empty [] ...fn-body)
(implements empty empty)
;; this would also grant us naming flexibility
(defn foobar [] ...fn-body)
(implements empty foobar)
```

This is how most languages do it with keywords like `override` or e.g. Haskell's `instance where`

What does everyone think?

**Comment by scolsen** [comment]
I guess a counterpoint to this is that anyone can come up with a different name when needed. That said, I could see that state of affairs being annoying to people who want to use some really clear interface name in their projects but can't because of core implementations that differ.

On the other hand, this would add an extra line of code every time you want to implement an interface, and it is nice how flexible the system currently is.

I guess another impetus for changing it is to protect against name changes. It'd stink to have a large codebase with `foos` everywhere only to discover you have to rename the `foo` interface because now core uses it somewhere.

**Comment by eriksvedang** [comment]
Yeah, I think this is a good idea! There's still the "multi symbol" lookup that will be more ad-hoc (and solves overloaded member names, etc). Have you thought about how to implement it? (I haven't)

**Comment by hellerve** [comment]
I just want to add that in this particular case, `Bucket.empty` should probably be `Bucket.zero` anyway. That doesn’t resolve this issue, but clean semantics probably make this case less common.

**Comment by scolsen** [comment]
> Yeah, I think this is a good idea! There's still the "multi symbol" lookup that will be more ad-hoc (and solves overloaded member names, etc). Have you thought about how to implement it? (I haven't)

I haven't given it much thought yet. My instinctive idea is to just use a `meta` tag and primitive, similar to the way `doc` works—but I'm not sure if it's really sound to make changes to the compiler based on the expectation of a meta tag—doc it seems fine since we're just adding additional information, but an `implements` tag would alter whether or not the compiler attempts to unify the binder with an interface...which seems a bit more dubious.

Right now though, that does seem to be the best place to put it. Info isn't appropriate because that contains positional information. Context also doesn't seem appropriate. 

The other option is that we introduce totally new functionality for the special case. In this case `Implements` would still be a primitive that takes two binders, gets the tys, then runs the current interface checking function against those tys. This solution also seems OK to me, and would presumably:

- make it easy to pull this feature in or out of the compiler (just remove `implements` and call the interface checking (which will be unaltered) in the position it was called before)
- seems less brittle than using `meta`

So, I guess after thinking through it a tiny bit, I'd prefer the custom primitive over implementing new `metadata`. Though the benefit to implementing it as meta is that the programmer can then use the meta utilities to check whether or not someone else's function implements an interface! Which would actually be pretty neat. i.e.

```
;; File a.carp
(definterface printer (Fn [(Ref String)] ()))
(defmodule A
   (defn basic-printer [s] (IO.println s))
)

;; File b.carp (someone else's library)
(load "a.carp")
(implements? printer A.basic-printer)
;; => true
```

That seems potentially very useful if one wants to explore someone else's code in the repl or if one just wants to fail slightly more gracefully upon interface errors--i.e. one could roll custom logic based on `implements?` such as executing an alternative branch instead of letting Carp error out with `no implementation of interface w/ type....`

So I think we need:

- To define a new primitive `implements` that does two things:
  1. calls the  existing interface unification fn on two binders
  2. If  (1.) is successful, sets a `meta` `implements` on the binder that implements the interface.
-  Define an `implements?` function that reports whether or not a binder for a function implements an interface.

How does that sound?
