### ISSUE TITLE
Twice wrapped match does not terminate

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#767]
Writing `(match)` is not valid, and the compiler will tell you that it isn’t. Writing `((match))`, on the other hand, will not terminate—of course it is equally invalid, but the compiler shouldn’t choke on it.

Cheers

**Comment by eriksvedang** [comment]
Seems like this is solved?!

**Comment by hellerve** [comment]
It is, though the error message is a little weird. It seems like `eval` is getting confused there. I’ll prepare a better error message.
