### ISSUE TITLE
Create simpler CI script for Windows

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#775]
There were some (mysterious) trouble with the GithubActions script that runs the test suite, for Windows. How about that we create a simpler version that just runs some basic checks? That will give us a fair amount of help not messing up Carp on Windows completely until we have figured out the original problem.

Ping @TimDeve and @hellerve .

**Comment by TimDeve** [comment]
As in one that runs is explicitly running the test file rather than looping through that folder? Or just running less tests/examples? 

Something else to explore is that I think, need to confirm, that Git Bash is available on the CI, could try running the unix script on Windows as well.

**Comment by eriksvedang** [comment]
Yeah, something like running a few select "important" tests that have a high chance of making sure that nothing is broken.

Trying the git bash thing sounds good too.

**Comment by TimDeve** [comment]
Should this be closed since https://github.com/carp-lang/Carp/pull/781 was merged?

**Comment by eriksvedang** [comment]
Yes, it should!
