### ISSUE TITLE
Cleanup Types.hs

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#783]
Types.hs currently contains a couple of functions that:

- mangle names into valid C identifiers
- convert types to C identifiers
- manipulate Sympaths

The types system might be a little bit more modular/cleaner if we move these functions elsewhere.

wdyt?

**Comment by eriksvedang** [comment]
For sure!

**Comment by hellerve** [comment]
Sounds good!

**Comment by Vertmo** [comment]
Hi ! Beginner here ! That sounds like a simple enough task, I could try that :)

**Comment by hellerve** [comment]
Sounds great! [Hope on the chat](gitter.im/carp-lang/carp) if you need guidance/want to hang out. You can always ping me or probably @scolsen (sorry for speaking for you)  if you need more info!

**Comment by scolsen** [comment]
Thanks @Vertmo!
