### ISSUE TITLE
Add `String.to-bytes`

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#794]
Since we now no longer live under the assumption that a string is a collection of bytes (kudos to us, especially @jacereda), we should probably add an escape hatch to get back to a simpler time where they were. This is useful when implementing encodings, even simple ones.

Carpentry’s UTF8 library in particular builds on that notion.

Cheers

**Comment by jacereda** [comment]
Maybe the `Char` change is too problematic? Would it be better to keep the old behaviour for `chars`/`from-chars` and have `runes`/`from-runes`?

**Comment by hellerve** [comment]
I don’t think it’s problematic, but it’s definitely a behavioral change!

What I personally did before was use the UTF8 library on carpentry, which did indexing on runes if I needed multibyte indexing and so on. But I think that having a multibyte-by-default type makes more sense. The only thing that we need is an “escape hatch” so we can go back to bytes if we need to, I think.

**Comment by hellerve** [comment]
I’ll also deprecate the UTF8 library this week, because it doesn’t provide any functionality we don’t already have with this change.
