### ISSUE TITLE
NULL should not be callable

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#802]
Because `NULL` can be anything, Carp will not complain when you call it like so: `(NULL)`. This will emit `NULL()`, which the C compiler is not happy with.

We should probably add a special case to disallow that (`NULL` is already a special case anyway).

Cheers

**Comment by hellerve** [comment]
Maybe `NULL` should be `(Ptr a)` instead of `a`?

**Comment by eriksvedang** [comment]
Maybe we should add an easter egg when you do that? :)

The type change seems like a good idea, I think...
