### ISSUE TITLE
address shouldn’t allow literals

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#806]
Currently `address` will accept literals, such as `(address 1)`. This will emit `&1`, which does not work in C.

I think what needs to happen is that `address` needs to be a primitive that needs to check whether the argument passed is a symbol.

I volunteer to work on this.

Cheers

**Comment by jacereda** [comment]
Somewhat related, how do you refer to, say, a memory-mapped register located at an absolute address?

**Comment by hellerve** [comment]
You can do `Pointer.from-long` if you know the address and have it as a long value somewhere. That should cover msot cases I think?

**Comment by jacereda** [comment]
Sure, thanks.
