### ISSUE TITLE
Consolidate/Clean up Meta related code

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#822]
Carp's meta system is super flexible and super useful, but, right now, the code that defines it is slightly less so! A variety of functions deal with binding metadata, but they do so inconsistently, some permit qualified names, some don't, some lookup paths contextually, others don't, etc. 

I think it'd be a worthwhile code health project to try and unify and simplify some of the Meta related code.

**Comment by scolsen** [comment]
While it's in my head, there are a couple of places that come to mind:

`Eval.hs` -- looks up metas using the `Lookup.hs` function
`Primitives.hs` -- often performs ad-hoc/custom meta lookups.
`Lookup.hs` -- provides a meta function, but this doesn't take a context.

I'm sure there are other places too.

**Comment by eriksvedang** [comment]
Could this be considered done, @scolsen ?

**Comment by scolsen** [comment]
We have `Meta.hs` now so I think we're good for now!
