### ISSUE TITLE
Calling a function with a sig from within a submodule results in a compiler error

### ISSUE THREAD

**Issue by TimDeve** [carp-lang/Carp#823]
Calling a function with a sig from within a submodule results in a compiler error.
Example:
```clojure
(defmodule Sub
 (defmodule Mod
  (defmodule Ule
    (sig a-func (Fn [String] String))
    (defn a-func [a] a)

    (defn hey [a] (String.append a &(a-func @a))))))

(defn main []
  (println* (Sub.Mod.Ule.hey "Wow")))
```
Result in error:
```
I encountered an error when emitting code:

I found an ambiguous symbol `a-func` at line 7, column 38 in '/Users/tim/example/main.carp'

Possibilities:
  Sub.Mod.Ule.a-func
  Sub.a-func

All possibilities have the correct type.

Traceback:
(build) at Compiler (Build & Run):1:5.
```

Example of working code for context:
```clojure
(defmodule Sub
    (sig a-func (Fn [String] String))
    (defn a-func [a] a)

    (defn hey [a] (String.append a &(a-func @a))))

(defn main []
  (println* (Sub.hey "Wow")))
```
```clojure
(defmodule Sub
 (defmodule Mod
  (defmodule Ule
    ;(sig a-func (Fn [String] String))
    (defn a-func [a] a)

    (defn hey [a] (String.append a &(a-func @a))))))

(defn main []
  (println* (Sub.Mod.Ule.hey "Wow")))
```
```clojure
(defmodule Sub
 (defmodule Mod
   (defmodule Ule
     (defn a-func [a] a)

     (sig hey (Fn [(Ref String)] String))
     (defn hey [a] (String.append a &(a-func @a))))))

(defn main []
 (println* (Sub.Mod.Ule.hey "Wow")))
```

**Comment by scolsen** [comment]
Dumping a bunch of notes from chat:

> Somehow pathstrings for submodules aren't captured in the pathstrings that primitiveMetaSet recieves
so when it's called before a form exists it only adds a DocStub to the top-level module
```
鲤 :i Sub
Sub : Module = {
    Mod : Module = {
        Ule : Module = {
            a-func : (Fn [a] a)
            hey : (Fn [(Ref String a)] String)
        }
    }
    a-func : a
}
```
> I tried altering primitiveDefModule...but it pretty muich breaks everything
what's odd is that the module itself/defining binding is correct
only MetaSet doesn't get the full story for some reason

> So, I think the issue underlying #823 is that we pop off a module name everytime we define a brand new module:
```
鲤 (load "tricky.carp")
pathstrings:["Sub","Mod","Ule"]
pathstrings:["Sub","Mod"]
pathstrings:["Sub"]
鲤
```
> On the face of it, this isn't problematic in eval because we dive down to eval the other expressions, but when it comes to meta-set of a sig it's receiving only the last path string, with the interior modules popped off, which assigns the sig to the wrong module.

> Not sure why the execution branch for the primitive differs from the defn, but it does which causes the issue
So, this change will be a bit complicated, I think—we basically need to make forward metadeclarations behave the same as defns and defs insofar as context resolution goes
