### ISSUE TITLE
Non-exhaustive patterns in function `members`

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#824]
In `Primitive.hs` we're missing a case in `deftype` handling:

```
鲤 (deftype Foo [Int])
carp: src/Primitives.hs:(556,36)-(557,50): Non-exhaustive patterns in function members
```

Should be fairly simple to fix!

**Comment by naveenk97** [comment]
Can I do it. I am a beginner in this bug thing. @scolsen

**Comment by scolsen** [comment]
Go for it @naveenk97 ! Let me know if you have any questions and I can help out

**Comment by hellerve** [comment]
Closing this because #873 was merged!
