### ISSUE TITLE
Primitives may be used as binding names

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#825]
Currently, it's possible to use the name of a primitive as a binding:

```
鲤 (defn definterface [x] x)
鲤 :i definterface
definterface : (Fn [a] a)
Defined at line 1, column 1 in 'REPL'
鲤 
```

This is...somewhat problematic. Right now, we usually prevent this for Xobjs using `isUnqualifiedSym`:

```
鲤 (defn defn [x] x)
`defn` identifiers must be unqualified symbols, but it got `defn` at REPL:1:1.
鲤 
```

however, excluding primitives would require calling `lookupInEnv` which `Obj.hs` presently doesn't depend on (a good thing)

So the solution is a bit trickier than anticipated.

**Comment by scolsen** [comment]
@hellerve FYI, you might have a good idea on how to fix this?

**Comment by hellerve** [comment]
I actually think that this is intended behavior and works like in a lot of other Lisps. You should be able to rebind and break things as you wish; we could potentially emit a warning for this, though.

As for fixing this, I think the best way would be to do a lookup before doing any binding. That shouldn’t be too hard, and I can do this. But again, I don’t know whether this should actually be considered a bug.

**Comment by scolsen** [comment]
Ah, good to know! Maybe a warning would be nice, but may also not be necessary. I'll change this to `enhancement` for now and potentially close it down the line if we don't think it's worthwhile.

**Comment by scolsen** [comment]
Let's consider this off the table!

**Comment by eriksvedang** [comment]
👍
