### ISSUE TITLE
The `cond` keyword is undocumented.

### ISSUE THREAD

**Issue by Liorst4** [carp-lang/Carp#829]
There is no documentation on how to use `cond`.

**Comment by mitchell-frost** [comment]
Can I work on this?

**Comment by eriksvedang** [comment]
@mitchell-frost You sure can!

**Comment by mitchell-frost** [comment]
I am new to open source so, I am a little confused. Do I add an html file to Carp/docs/core about the cond keyword? and 'cond' refers to the conditional rendering in Carp language right?

**Comment by eriksvedang** [comment]
cond is a macro defined in core/Macros.carp. So you can look at other definitions that have docs there and follow their style. Good luck!

**Comment by mitchell-frost** [comment]
Thank you. I will look into it.

**Comment by mitchell-frost** [comment]
I have made a pull request. Would really appreciate if you could review it.
