### ISSUE TITLE
The `Pair` module is undocumented.

### ISSUE THREAD

**Issue by Liorst4** [carp-lang/Carp#830]

**Comment by scolsen** [comment]
Another thing that's a bit pesky about `Pair` is that it's defined in a file called `Tuples.carp` and not `Pair.carp`--which breaks with the convention we have for other files; typically the name of the file is the name of the primary module it defines.

**Comment by eriksvedang** [comment]
My idea was that other arities could be defined in there too, but maybe that was a bad idea and the file should be renamed...

**Comment by scolsen** [comment]
> My idea was that other arities could be defined in there too, but maybe that was a bad idea and the file should be renamed...

I think that'd be cool, actually :) It would be useful and make the file name make more sense!

**Comment by hellerve** [comment]
I’m currently working on generating tuples of multiple arities from macros. This should make it simple to add new functionality and document!

**Comment by eriksvedang** [comment]
> I’m currently working on generating tuples of multiple arities from macros. This should make it simple to add new functionality and document!

Oh, what a good idea!
