### ISSUE TITLE
core/geometry.carp should probably be core/Geometry.carp

### ISSUE THREAD

**Issue by avatarwin** [carp-lang/Carp#84]
At least, that's how its referenced in preludeModules and it would be consistant with the other modules in core.

Not a problem if you're on a case-insensitive filesystem, I guess...

**Comment by eriksvedang** [comment]
True, fix this

**Comment by hellerve** [comment]
Oops, I’m the guy with the case-insensitive file system who did this. I actually thought I’d fixed this before PRing.

Sorry about that!
