### ISSUE TITLE
Put scripts into a directory?

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#851]
We have a *lot* of bash scripts in the root of the repo right now, perhaps we should do some spring cleaning and put them in their own directory? Would make the Github landing page a bit more welcoming, I think.

**Comment by hellerve** [comment]
Yeah, that sounds good to me. We’d just have to update the CI scripts and such accordingly, but it shouldn’t be too much work.

**Comment by TimDeve** [comment]
@eriksvedang I see you've assigned this to yourself, did you hit any snag? If not do you mind if I pick it up?

**Comment by eriksvedang** [comment]
@TimDeve Oh please do!

**Comment by TimDeve** [comment]
I believe this can be closed.
