### ISSUE TITLE
Help (help)

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#852]
I think that the `(help)` command is a good idea in theory, but it's a bit unwieldy right now. Perhaps someone has ideas for how to make it more useful? And who is it for? (beginner/expert/both?) Should it be more of a collection of links to the docs?

I think that making it possible to write `(help macros)` rather than `(help "macros")` could be a good thing. If it even makes sense to have these "chapters"?

**Comment by hellerve** [comment]
I think it currently is at a midway point where it shouldn’t be. It could be either:

- much more complex, like a tour with chapters, or
- much more simple, giving you just the basics.

Otherwise, it’s just another place in which to update docs, and it’s usually the last place people remember.

**Comment by eriksvedang** [comment]
Yeah agreed, it’s always out of date. Some kind of interactive tutorial would be the coolest, but that’s a lot of work of course...

**Comment by scolsen** [comment]
[Miranda's](http://miranda.org.uk/) repl includes a help system/structure that I found super helpful and really great for getting into the language--might be able to draw on that for inspiration? There's a browsable version here: http://miranda.org.uk/manual. iirc when you run help in `mira` it basically displays the full contents of the manual w/ commands to jump to different sections, etc.

**Comment by eriksvedang** [comment]
That sounds super cool, will check it out!
