### ISSUE TITLE
Static lists in the calling position lead to hangs in the REPL

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#853]
As discussed in #850, trying to evaluate something with a list in the calling position will lead to a hang in the REPL. This is because we don’t match that in the special cases in `executeCommand` yet.

Unfortunately, it’s slightly more tricky to detect than the other cases: the nesting of the static code could be arbitrarily deep, and we can’t just do a simple pattern match.

Cheers

**Comment by hellerve** [comment]
Example for reproducibility:

```clojure
(((fn [] Int.+)) 1 1) ; should end up being (Int.+ 1 1), but hangs
```

**Comment by eriksvedang** [comment]
This seems to be fixed! Please confirm :)
