### ISSUE TITLE
Decide target standard

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#855]
Which standard should the emitted code adhere to?

- C89 is supported everywhere, but lacks some recent niceties (`stdint.h` for one).

- C99 is supported by all current compilers, even in the embedded world you'd have trouble finding a non-compliant compiler. 

So I guess the deciding factor is whether to support legacy platforms like, say, Amiga/Atari.

**Comment by scolsen** [comment]
I don't know too much about the details of each standard, so forgive me if this is a silly question:

Would it be feasible to support C99 by default and tuck C89 support away under a compiler option?

It wouldn't be insignificant work, but seems like it'd be possible by using different templates and emitting the appropriate variant based on the requested standard.

If we have to choose just one, choosing C99 seems right to me, but on the other hand it would be cool to support use cases like Amiga/Atari.

**Comment by jacereda** [comment]
There's a table at https://en.wikipedia.org/wiki/C99#Implementations

I would read Partial/Mostly as valid for our purposes, since our codegen won't use the obscure features not present in those.

**Comment by jacereda** [comment]
Partial list of things we would need to get rid of:

- `// comments`

- Variable declarations in `for` loops, i.e. `for (int i = 0...`.

- `inline` keyword.

**Comment by jacereda** [comment]
Even legacy platforms will probably have an old GCC (2.95.X was mostly the compiler of choice in the 68k platforms) that supports all of those when compiling with extensions enabled IIRC. (Maybe `inline` would need to be a `define`d as `__inline__` or something like that).

**Comment by GrayJack** [comment]
I agree that C99 is a better standard to be used, language-wise. I think supporting those super legacy systems is not worth it compared with with the niceties.

I also think that if anyone wants very-very much write Carp for those legacy systems, they can always do their version of the corelib ( they pretty much would just need to rewrite the `deftemplate` ones, right?)

**Comment by sdilts** [comment]
It might be worth the upgrade just for `stdbool.h`
There are a few things we probably shouldn't include in Carp such as variable-length arrays though.

**Comment by rkaippully** [comment]
Would it make sense to have a "freestanding" target that does not depend on any standard library? This would help in writing very low level code such as operating system, bootloaders etc in Carp. AFAIK, Rust and Nim support this.

**Comment by hellerve** [comment]
@rkaippully the way we currently support this is by doing `--no-core`, which will not load the standard library. You can then load the parts of it that you need/can load yourself.

This has been enough in the firmware/embedded experiments that are going on until now.

What do you think, does that fill the gap you’re describing?

**Comment by bjorn3** [comment]
In rust `#![no_std]` removes the dependency on the part of the standard library that requires OS support. It keeps the dependency on the parts of the standard library that don't need OS support though. For example all non-allocating string methods, math operations, memory operations and more are still allowed. If you use `extern crate alloc;` and define your own allocator, you can also use almost all data structures that allocate memory. Using `--no-core` for Carp disables all those things.

**Comment by eriksvedang** [comment]
@bjorn3 Right, I think it would make sense with a middle way – some kind of practical subset of Core that can be selected easily. `--no-core` is still useful, especially when developing the language or experimenting with weird use cases for it.

**Comment by rkaippully** [comment]
@hellerve `--no-core` looks promising indeed! Thank you. I'll try it on a small project.

**Comment by jacereda** [comment]
> I agree that C99 is a better standard to be used, language-wise. I think supporting those super legacy systems is not worth it compared with with the niceties.
> 
> I also think that if anyone wants very-very much write Carp for those legacy systems, they can always do their version of the corelib ( they pretty much would just need to rewrite the `deftemplate` ones, right?)

Unfortunately that's not the case. We emit a bunch of `//` for comments and that wasn't in C89.

**Comment by eriksvedang** [comment]
OK, I'm personally fine with C99 then. I think the syntactic niceties doesn't matter that much, but having access to some more headers and such seems reasonable. I could see the benefit of just using the working intersection of C89 and C99, since we're just emitting the code and don't have to read it all day. But someone has to voice a strong opinion for that to happen (and make the necessary changes to the emitter).

**Comment by eriksvedang** [comment]
I merged @jacereda:s fixes for compiling with `-std=c99` so this can be closed now.
