### ISSUE TITLE
[Proposal] Type union and of operators

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#877]
I'd like to propose adding type unions, or the *union type operator* to Carp. A type union is more specific than a generic type, but more general than singular concrete type--they'd let one designates a function as accepting more than one concrete type, for example, either a `String` or an `Int`. I propose a syntax similar to that of [typescript](https://www.typescriptlang.org/docs/handbook/advanced-types.html#union-types); taking a look at the proposed syntax will help illustrate the idea:

```
(sig string-or-int (Fn [(String | Int)] String))
```

The `string-or-int` function in the example above would typecheck so long as either `String` or `Int` values are passed as arguments.

## Rules of Use and Behavior

The union operator may be used in the following contexts:

- Function signature argument positions, as above:
`(sig string-or-int (Fn [(String | Int)] String))`
- `deftype` forms
`(deftype StringOrInt [x (String | Int)])`

The union operator may *not* be used in the following places:

- Ref types
- Pointer types

### Concretization

When concretized, union types must resolve to a concrete type `t` where `t` is a term of the union `(t | t')`

### Unification

Union types may be unified with:

- Base kind type variables `a` 
- Union types that are (not necessarily proper) supersets of the union type,  e,g, `(String | Int)` and `(String | Int | Float)`

The gist of this is that something like:

```
(sig add-one [Int] Int)
(sig inc-int-float [(Float | Int)] (Float | Int))
(defn inc-int-float [x]
  (add-one x)) ;; won't type check!

;; but this works since 
;; (inc [a] a) is the signature of inc
(defn inc-int-float [x]
  (inc x))
```

## The `of` operator (syntactic sugar)

Using union types can become quite verbose if they are used on multiple fields:

`(deftype ComplicatedThing [x (String | Int) y (String | Int) z (Int | Long | Float | Double)])`

The `of` operator enables programmers to bind complex type specifications to type variables, shortening the signature:

`(deftype (ComplicatedThing (a of (String | Int) b of (Int | Long | Float | Double))) [x a y a x b])`

**Comment by eriksvedang** [comment]
Interesting idea, I know I've reached for something like this a few times – but managed to work around it in the end. Do you have some great use cases for this where sumtypes are not up for the task? Also, how is it related to constraints ("typeclasses") on type variables?

**Comment by GrayJack** [comment]
Would be possible to be able to match on a type? Like, to create a function
```clojure
(sig func [Int | String] (Int | String))
(defn func [x]
  (match-type x
    (Int) (do-something-with-int)
    (String) (do-something-with-string)))
```

**Comment by sdilts** [comment]
@GrayJack Isn't that basically the same as using an interface, with slightly less steps?

**Comment by scolsen** [comment]
The more I've thought about this, the less I like it, so I'm going to kill my own proposal, if that's ok :)

**Comment by eriksvedang** [comment]
That's OK!
