### ISSUE TITLE
Lambdas need to capture from implicit environments

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#879]
After the work done by @Vertmo in #850 we can finally refer to variables inside nexted contexts in `fn`. Sadly, we forgot to add support for implicit environments, i.e. `let`s. This will lead to weird bugs.

Consider this (very silly) example:

```clojure
(defn make-cb []
  ((fn []
    (let [x "hi"]
      (fn [] (IO.println x))))))

(defn main [] ((make-cb)))
```

Here, we have two nested `fn`s, the inner of which depends on `x`, introduced in a let in the outer `fn`. This should be fine, except that `x` propagates into the lookup list of the outer `fn`, because implicit environments aren’t checked by the current code. This will lead to invalid C being emitted.

What needs to happen is that a check for implicit environments needs to be inserted into the lookup routine, so that we can short-circuit before bubbling those lookups up.

Cheers

**Comment by Vertmo** [comment]
Oh yeah, that's an issue for sure. Since I was the last one to touch this part of the code, I will be looking into it, if that's ok with you ^^

**Comment by hellerve** [comment]
That’s perfect, thank you! I looked very briefly yesterday, but since it wasn’t a quick fix I decided to defer until I find the time, but I think you’re even better suited than I am to work on this!

**Comment by Vertmo** [comment]
This issue was resolve by #883 and should probably be closed :)
