### ISSUE TITLE
The compiler allows main to return non-ints

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#89]
According to the compiler, this is a valid Carp program:

```
(defn main []
   @"Hi there!")
```

Compiling it will result in the following C code:

```
int main() {
    string _4 = "Hi there!";
    string *_4_ref = &_4;
    string _5 = String_copy(_4_ref);
    return _5;
}
```

The generated C code tries to return a `string`/`char *` from a function declared `int`. The C compiler will probably complain, although it might only be a warning.

A naive idea to fix this problem: introduce `main` as a fix point to the type checker (i.e. make it common knowledge that `main` is always of type `[] -> Int`. This way at least the type checker would fail, which is better than having the C compiler handle it.

Cheers

**Comment by eriksvedang** [comment]
Agreed, good suggestion.
