### ISSUE TITLE
Match lists with `:` instead of literals

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#911]
Currently, we mix different list pattern matching approaches throughout the codebase, in some places we use a literal style, `[x, _, _]`, while in others we match using the `:` constructor, `(Lst (x : rest))`.

I propose we try to switch to using the second style, matching using `:` exclusively. It is more flexible in the face of change than a literal match. `[x, _, _]` will lead to breakages if the list we're matching against adds or removes an element, whereas `(x:rest)` matches handle such changes without issue.

Of course, the trade-off is that we sometimes *want* to explicitly handle any alterations in the shape of a list--the breakages caused by `[x, _,...]` literal matches can make one aware of other parts of the codebase that may need to change as a result of other modifications, so any additive or subtractive changes to the list will cause us to account for all its touchpoints in the code. That said, `(x:rest)` will still break on subtractive changes, while continuing to work fine on additive changes *unless* the tail element is used in a non-generic way--which I think is satisfactory as certain additive changes are no-ops for parts of the codebase anyway.

**Comment by eriksvedang** [comment]
We did use a lot more matching using `:` before but the longer complained so we switched it out. I think a more fruitful change would be to start using pattern synonyms!

**Comment by scolsen** [comment]
sgtm!

**Comment by eriksvedang** [comment]
Great, then I'll close this. Looking forward to learning about that Haskell feature!
