### ISSUE TITLE
Awesome carp list

### ISSUE THREAD

**Issue by antonkatz** [carp-lang/Carp#913]
Is there a list of carp libraries? An "awesome" list like for many other languages.

I'm specifically wondering about a web library (http server), but would be curious to see the whole list

**Comment by TimDeve** [comment]
Yeah, there is [Koi](https://github.com/TimDeve/koi) as a toy web framework, [Sheriff](https://github.com/TimDeve/sheriff) works alright for Carp -> JSON and [Hoquet](https://github.com/TimDeve/hoquet/blob/master/example.carp) for an HTML DSL.

I wouldn't really expose any of these to a public IP thought. I think your best bet for web stuff would be something like NGINX + FastCGI but I never tried it.

**Comment by antonkatz** [comment]
Thanks folks!
