### ISSUE TITLE
Expose System_args in core/System.carp

### ISSUE THREAD

**Issue by Liorst4** [carp-lang/Carp#916]
Its annoying to parse command line arguments without accesses to `argv` (calling `getopt` for example).

```clojure
(register args (Array String) "System_args")
```

**Comment by hellerve** [comment]
There is `System.get-arg` and `System.get-arg-len`, is that perhaps enough?

**Comment by hellerve** [comment]
Thinking about this some more, to make the API nicer maybe we could make this a `StaticArray` instead (those weren’t around when we first added the functions). What do you think, @eriksvedang?

**Comment by eriksvedang** [comment]
@hellerve That sounds like a great idea!
