### ISSUE TITLE
Move tests from 'examples' to 'test'

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#92]
Since we have a new and shiny testing library it would be awesome if all the old "tests" in the example folder would be moved to the 'test' folder and converted to using the library instead of just dumping a bunch of text to stdout. I'll do this eventually but if anyone wants to start the job, please go ahead. I can assist with guidance.

**Comment by hellerve** [comment]
Which examples would you like to leave and which would you like to have moved?

**Comment by eriksvedang** [comment]
I think the "applications" like `game.carp`, `life.carp`, `reptile.carp`, `guessing.carp` are the only ones that should be kept.

**Comment by hellerve** [comment]
Alrigh, consider me on it.

**Comment by hellerve** [comment]
Can we close this now?

**Comment by eriksvedang** [comment]
Yes!
