### ISSUE TITLE
macOS CI is broken

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#920]
As we’ve seen in recent PRs, the CI for macOS seems to be broken (it fails when building Carp). This doesn’t seem to be an actual problem with Carp, since at least @eriksvedang and I primarily use macOS for development and have not had any trouble. It’s thus more likely to be a problem with CI setup.

Since the failure is somewhat sparse in information, this might be a bit frustrating to debug, but I encourage everyone who likes this kind of work to give it a go!

Cheers

**Comment by eriksvedang** [comment]
I actually think this is solved now, knock on wood!
