### ISSUE TITLE
Reduce binary sizes

### ISSUE THREAD

**Issue by Liorst4** [carp-lang/Carp#922]
Compiling the following code results in 390Kb file.
```clojure 
(defn main [] ())
```

That file contains lots of functions to initialize the carp runtime (`carp_init_globals`).

Moving these functions into external runtime (Like C has libc) can reduce the size of binaries.

**Comment by jacereda** [comment]
On which platform? Try compiling an optimised version with `--optimize` and adding something like:
```
(add-cflag "-Os")
(add-cflag "-flto")
```

Also make sure you check the size with `size <filename>`. Maybe you're looking at the size of the debug symbols.

**Comment by Liorst4** [comment]
I'm using linux.

output of `size`:
```
   text	   data	    bss	    dec	    hex	filename
 164578	   2568	     96	 167242	  28d4a	out/Untitled
```

Using `--optimize` actually makes the binary larger, making it 600K (using `ls` and `stat`).
The output of `size`:
```
   text	   data	    bss	    dec	    hex	filename
 114732	   1688	     96	 116516	  1c724	out/Untitled
```

Adding `-flto=full` decreased the size significantly, into 22k
The output of `size`:
```
   text	   data	    bss	    dec	    hex	filename
   1420	    544	     32	   1996	    7cc	out/Untitled
```  

Adding `-flto=full` and `-Os` caused this error message:
```
/usr/bin/ld: error: Optimization level must be between 0 and 3
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
carp: callCommand: clang -o out/Untitled -I $CARP_DIR/Carp//core/  -fPIC -g -std=c99 -D_DEFAULT_SOURCE -Wall -Werror -Wno-unused-variable -Wno-self-assign -flto=full -Os -lm out/main.c (exit 1): failed
```

Maybe `flto` should be included when the `--optimize` flag is used?

**Comment by jacereda** [comment]
You can try `-flto=full -O2 -fomit-frame-pointer -ffunction-sections -fdata-sections` also, although it will only make a difference in bigger programs.

I'm not sure if `-flto=full` implies `-ffunction-sections -fdata-sections`.

**Comment by jacereda** [comment]
BTW, `--optimize` didn't make it larger according to `size` (167242 vs 116516). The size on disk is probably due to the debug info. You can `strip` both binaries to see something closer to the real thing.

**Comment by jacereda** [comment]
Oh, you can also try adding `-Wl,--gc-sections` to the above options.
