### ISSUE TITLE
String: Fully abstract string memory layout

### ISSUE THREAD

**Issue by Liorst4** [carp-lang/Carp#923]
Some `String` method assume utf-8 encoding (like `String.slice`), even though you can edit the data to be utf-8 invalid.

This is an easy pitfall and might confuse newcomers.

The following code will crash:
```clojure
(defn main []
      (let [my-string (String.allocate 10 (Char.from-int 255))
	    my-other-string (String.slice &my-string 1 5)]
	(do
	  (println* (String.length &my-other-string)))))
```

`String.allocate`, `String.char-at`, `String.string-set!`, `String.index-of` and `String-index-of-from` should use unicode characters (`Char`) and not bytes (`char`).

`String.length` should return the amount of characters and not the amount of bytes

These 4 bytes represent a single unicode (utf-8) character (👏).
The result of `String.length` is 4 and not 1.
```clojure
(defn main[]
      (let [arr [(Byte.from-int 240)
		 (Byte.from-int 159)
		 (Byte.from-int 145)
		 (Byte.from-int 143)]
	    my-string (String.from-bytes &arr)]
	(do
	  (IO.println &my-string)
	  (println* (String.length &my-string)))))
```

**Comment by hellerve** [comment]
I agree with the goals set out in this issue: at the very least we should be  c onsistent about using bytes versus utf-8. I think the in-between state is the result of recent-ish changes to make Carp more multibyte-friendly, but I guess we missed a few spots. Since you lead the initial implementation, would you like to/have time to look into this, @jacereda? Otherwise I can take a stab at it!

**Comment by jacereda** [comment]
Let me think a bit about this, I would prefer keeping `String` as a C string and have a `unpack` function for extracting code points (perhaps an iterator over code points as well).

**Comment by jacereda** [comment]
Wait, isn't that exactly what `chars` does?

**Comment by eriksvedang** [comment]
Seems like it :)

**Comment by eriksvedang** [comment]
Can we close this now?

**Comment by jacereda** [comment]
I think so.
