### ISSUE TITLE
Philosophy of Carp? Or: is intended for this language to remain small and simple?

### ISSUE THREAD

**Issue by vitiral** [carp-lang/Carp#924]
I love the ideas in Carp. I love that it is focusing on a simple and clear syntax, has no GC, compiles transparently to C, and embraces macros and dynamic functions. In fact, I love these principles so much that I've decided to finally learn Haskell because I want to start hacking on it, instead of continuing to write [my own programming language](github.com/vitiral/wheat) which shared similar goals. Before I commit fully though, I had a couple of nagging questions that I couldn't find anywhere in `docs/`

* The `README` states that "Carp is a small programming language" -- is it intended to stay that way? One of the reasons I want to develop a language like carp is because I want a language that is simple and small and can be easily re-implemented. Is part of Carp's philosophy to remain as such a language?
  * Mainly: is carp more of a "C" type langage or a "C++/Rust" type language? Will it add language features to enable better performance? I assume the syntax will always remaining fairly small, considering it is lispy.

* Alternative backends: would merges to add emitting code to wasm be acceptable to the Carp maintainers (it seems like [yes](https://github.com/carp-lang/Carp/issues/178#issuecomment-361001593)?)? The way I envision it is that you choose either a C backend or a wasm backend, and libraries that export/import external functions can use a macro to export for the platform choose that -- although the specific design could be discussed as well, as there may be unification possible.

* Are there any plans for a bootstrapping compiler (writing Carp in Carp)? Any approximation on how difficult such a task might be :smile:?

**Comment by eriksvedang** [comment]
Hi, thanks for the questions! And awesome hearing that you want to contribute, we're always glad to have more people help out :)

1. I've been thinking about removing the word "small" already, it's too subjective. For some people Carp probably feels "big" already, while it's definitely small compared to a lot of mainstream languages (especially the compiler code base). Also, with macros and other powerful features it becomes hard to tell what is part of the language and what is just optional features.

2. There's definitely a willingness too add more backends. Right now the only thing we've played with is wasm (since it accepts C code) but I have been playing around privately with a more powerful way of doing code emission that would enable a wider range of languages. The main problem right now are the templates which only emit C code, so to support something completely different would require a bunch of work.

3. No plans for that at the moment. I think Haskell is still a better language to do compiler implementation in than Carp, so I think it would be a painful project at the moment. I won't try to stop any attempt though, it's surely an interesting topic and something that could become increasingly realistic later on.

Cheers!

**Comment by eriksvedang** [comment]
> Mainly: is carp more of a "C" type langage or a "C++/Rust" type language? Will it add language features to enable better performance? I assume the syntax will always remaining fairly small, considering it is lispy.

Good question. It definitely tries to be a lot smarter and more helpful than C. But also tries to not go crazy with complexity like C++ and Rust. So I guess it's in between both of them, if that makes sense.

**Comment by vitiral** [comment]
Hey, thanks for the responses

#1 is an area I would personally appreciate more clarity.

For me, a "small" systems language without a GC/RC should still have at least:

* RAII/ownership + lifetimes, Carp is working towards this
* Interop with a lower level language. This would be primarily C and wasm. In my limited opinion C/wasm is preferred, ASM interrop frequently introduces too much complexity. Carp looks to be on the right track here!
* A powerful and hygenic-ish macro system, which I think Carp has/is working towards. This allows libraries to enable complex workflows without increasing the complexity of the compiler/language itself. In other words, it is the ultimate "opt-in" form of complexity.

Not necessary but acceptable:
* A basic type system, specifically interfaces. This looks like where Carp is focusing. Personally, (with wheat) I thought of removing even this and instead allowing macros to _inject_ definitions of functions/macros into a module. So if you wanted a version of List that works for MyType you could do `MyTypeList = (List MyType)` which both generates the code and injects it into the `List` namespace (i.e. `List.List_mypkg_MyType`), preventing multiple versions of `MyTypeList` (also guarantees that all such attempts to generate would be identical). However, I was reasonably concerned that this would introduce other issues, so an interface system makes sense too :smile:
* A basic panic/stack trace system, like rust. However, catching panics is probably out of scope and has introduced tons of complexity in rust. IMO, simply being able to dump the trace (like in C) is probably the best for simple systems languages.

Probably out of scope:
* More complex types like Higher Kinded Types/etc. A macro system should be sufficient for filling in the gaps in _most_ cases, and any attempt to make a "perfect" language is going to run into ramping up the complexity of the language.
* Extensive std library: a reduced and _optional_ one (like rust has) is fine, but a stdlib is going to make assumptions about the host platform, increase complexity and make porting more difficult.
* APIs around async / processes / mutex / etc. It should be possible to implement some of these things in libraries (by calling into C / wasm / etc), but making requirements in the language is going to increase complexity. If possible however, a `Sync` type trait would be good, and some basic interfaces in the (optional) stdlib are healthy for the language.

#2 and #3 are great to hear.
Probably out of scope:
* More complex types like Higher Kinded Types/etc. A macro system should be sufficient for filling in the gaps in _most_ cases, and any attempt to make a "perfect" language is going to run into ramping up the complexity of the language.
* Extensive std library: a reduced and _optional_ one (like rust has) is fine, but a stdlib is going to make assumptions about the host platform, increase complexity and make porting more difficult.
* APIs around async / processes / mutex / etc. It should be possible to implement some of these things in libraries (by calling into C / wasm / etc), but making requirements in the language is going to increase complexity. If possible however, a `Sync` type trait would be good, and some basic interfaces in the (optional) stdlib are healthy for the language.

#2 and #3 are great to hear. I wouldn't need to bootstrap for several years, at a minimum. It's good to know there wouldn't be resistance in this area!

**Comment by vitiral** [comment]
Sidenote: for a bit of context, the reason I would like simplicity and to bootstrap is because I would like to be able to use a language like Carp as the basis for a [Civboot](civboot.org) software stack. This might help clarify why I require excessive simplicity in my choices :laughing:

**Comment by jacereda** [comment]
Not that I want to discourage you from using Carp, but if simplicity is at premium, Forth shines.

That's the path taken by https://collapseos.org

**Comment by vitiral** [comment]
@jacereda I just went down a small rabbit hole learning the basics of FORTH and reading CollapseOS. I think a CivbootOS doesn't take _reduced size_ at quite the premium as CollapseOS. Also, simplicity is a double-sided coin: It looks like FORTH achieves simplicity of several important metrics such as the language constructs and the compiler itself, but is often mocked as a "write-only" language because it's nearly impossible to build upon existing code. In particular, it appears to me that creating libraries and memory management would be _very difficult_ to do in FORTH. One of Civboot's core goals is that all the layers are understandable. It's great that FORTH is easy to learn and reimplement, but would software written in it be understandable? It seems like the answer is no, albeit from my limited understanding.

In all, I think FORTH is very similar in goals to WASM seeing that they are both ultra-simple stack-based languages that operate exclusively on numeric types. However, I cannot _imagine_ trying to write a programming language which compiles to FORTH, whereas doing so for WASM is entirely the point of the language. However, FORTH might very well be a good starting point for the bootstrapper. I will have to see how readable it is to have a WASM compiler in (transpiled) WASM. One of my goals is to have as few languages as possible in the tech stack.

**Comment by scolsen** [comment]
> More complex types like Higher Kinded Types/etc. A macro system should be sufficient for filling in the gaps in most cases, and any attempt to make a "perfect" language is going to run into ramping up the complexity of the language.

I *think* this is the only thing Carp currently supports that doesn't fit your 'small' requirements. I think it should be possible for us to tuck this behind some kind of compiler flag through, if that helps.

I guess we could get rid of higher kinded types for the sake of simplicity as well. I personally find them convenient, but it is possible to implement support for higher kinded type things entirely using macros as you suggest https://github.com/scolsen/typeclass/tree/master/legacy

And I guess you could argue carp's core lib is getting somewhat extensive, but you have the option to compile w/o it.

**Comment by vitiral** [comment]
I guess it all depends on how difficult it is to compile and understand the feature in question. I had assumed that HKT are difficult to implement, mostly because few languages have. If that is mistaken then by all means, they should be included. They certainly seem useful from what I understand (which is little, I need to learn moar Haskell).

**Comment by scolsen** [comment]
There's a chance full HKT support isn't implemented yet depending on what that entails, right now what we support in carp is polymorphism at the level of types and type constructors, so, one can use a type variable for a concrete type like `Int` (`a`) or a more complex type that itself takes a type as an argument, such as `Array Int` (`(f a)`) or even `(f s a)`--which will only match against a type that takes two arguments `(Vector Int Int)`

**Comment by eriksvedang** [comment]
I think some features might be hard to implement (and require a bunch of code) but make the language feel "smaller", or at least easy to reason about. Since we have HKT (more or less) I definitely don't want to remove them, they just make more code work without any additional burden on the programmer, imo. This discussion was interesting but I'll close the issue now since I think that we have answered the questions :)
