### ISSUE TITLE
"implements" missing from LanguageGuide.md

### ISSUE THREAD

**Issue by vitiral** [carp-lang/Carp#925]
It looks like the LanguageGuide.md is missing `implements`

It includes `definterface`, but doesn't state how to implement said interface. I believe `implements` is the way. Example from `Double.carp`

```
  (implements + Double.+)
  (implements - Double.-)
  (implements * Double.*)
  (implements / Double./)
  (implements < Double.<)
  (implements > Double.>)
  (implements = Double.=)
  (implements copy Double.copy)
  (implements neg Double.neg)
  (implements to-int Double.to-int)
  (implements from-int Double.from-int)
```

**Comment by eriksvedang** [comment]
Yeah that would be great to add to the LanguageGuide!

**Comment by scolsen** [comment]
Whoops, that's on me, I can add it.

**Comment by scolsen** [comment]
#926 adds docs around this!
