### ISSUE TITLE
Add all the math functions

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#93]
@hellerve has added a whole lot of math functions to the Double module. The Float module is way behind though, and there are also probably a few useful functions left to add for all the different math modules (Int / Long / Float / Double).

**Comment by eriksvedang** [comment]
I guess we can close this now?! (yay!!!)

**Comment by hellerve** [comment]
I’d like to add some more integral math functions, but in general we’re pretty ready. Give me a day to think this over.
