### ISSUE TITLE
Move macros into domain/semantic modules?

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#934]
`Macros.carp` has gotten pretty big and has a variety of macros for different purposes. Some of them might fit better into other modules that now exist, for example, control macros such as `for` and `doto` might make more sense in the newer `Control` module. Macros like `windows-only` might be better suited for the `System` module.

However, such a change is not totally negligible as it would probably result in breakages in downstream code (since macros will be defined in a module, instead of at the top level). We'd also have to change the load order of some modules in `Core.carp`. 

Since the change isn't functionally necessary and is a semantic/communication preference, I figured we can open it for discussion here.

**Comment by scolsen** [comment]
@hellerve @eriksvedang @jacereda

**Comment by hellerve** [comment]
I’m also in favor of this, with the caveat that I’d like to work through my libraries on carpentry and see what needs to change. I guess it would thus be best to do it iteratively, so as to limit breakage-at-a-time!

**Comment by scolsen** [comment]
> I’m also in favor of this, with the caveat that I’d like to work through my libraries on carpentry and see what needs to change. I guess it would thus be best to do it iteratively, so as to limit breakage-at-a-time!

Agreed--for once I actually anticipated a breaking change :) 

Iterative sounds good! Otherwise I can create a PR and leave it in draft mode until you've got PRs ready on the carpentry side, that way it should be "push-button"

We could also alias top-level names to the new module equivalents, e.g. `(def doto Control.doto)` or something similar until we determine a graceful way (release bounded?) to roll out the change completely.

**Comment by TimDeve** [comment]
A half-way solution would be to break the macros into domain specific files but keep them as root declarations. It would mean no breakage and it would be slightly easier to navigate when a change need to be made.

**Comment by eriksvedang** [comment]
@scolsen Do you want to do this one, or should I?

**Comment by scolsen** [comment]
I'm trying to tackle meta related stuff, right now, so if you want to start on this, go for it!
