### ISSUE TITLE
Conflict: New SDL defines overlapping types

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#943]
SDL defines `Uint<size>`, just like Carp does. This didn’t use to be the case, but now it is, preventing SDL-based programs to compile.

Conditional definition of these types doesn’t seem to be possible, since SDL will probably be loaded _after_ our `Uint<size>` types are defined.

How can we tackle this without having to ask SDL to conditionally define *their* types?

Cheers

**Comment by jacereda** [comment]
SDLHelper.h could do something like:

```
#define Uint8 SDLUint8
...
#include <SDL2/SDL.h>
...
#undef Uint8
```
