### ISSUE TITLE
Support implementing `drop` | `delete` interface (custom automatic resource management)

### ISSUE THREAD

**Issue by TimDeve** [carp-lang/Carp#954]
#737 is related but I wanted to make a clearer feature request.

It could be quite useful an equivalent to [Rust's drop trait](https://doc.rust-lang.org/rust-by-example/trait/drop.html) that would allow to write custom logic to be run before (or instead) `delete` is called. 

There are two use cases I specifically have in mind:
- freeing non-memory related resources, like socket or file handles (avoiding work-arounds like [this](https://github.com/carpentry-org/sockets/blob/edbb459fb909c51be907abca753a3ae8ea80f242/sockets.carp#L116))
- freeing memory for opaque type by calling custom destructor as seen in #737 

Ideally it would be as simple as calling `(implements MyType.drop drop)` but I don't think there is anyway at the moment to enforce the fact that `MyType.drop` takes MyType as an argument.

**Comment by TimDeve** [comment]
In particular it would make it much easier to use C as an escape hatch when writing nested data-structure as this is something that Carp does not support at the moment.

**Comment by hellerve** [comment]
I think this is great, and should be entirely possible! How would we facilitate both being able to run code before and instead of dropping? I guess that should be two different interfaces?

**Comment by TimDeve** [comment]
I meant it as "one or the other" rather than "both". My understanding is that `Drop` in rust is the mechanism that frees heap-allocated memory (like our `delete`) for built-in types like Vec or String however if you implement `Drop` on a type you don't have to manually call `drop` on other types it contains so it's not like it completely replacing `Drop`.

Instead of replacing the `delete` implementation it might just be easier to make `drop` a difference interface and say it gets called before `delete`.

**Comment by bjorn3** [comment]
Rust has a `drop_in_place` function that accepts a pointer to any type. The compiler replaces the function body with a call to `Drop::drop` (if implemented) followed by `drop_in_place` on each field. `drop_in_place` can be manually called to for example drop all the elements in a `Vec`. It is also automatically called when the scope of a value ends (RAII).

**Comment by TimDeve** [comment]
Ah that makes sense, thank you for the context.

**Comment by eriksvedang** [comment]
Yeah this should be possible to add pretty easily. We already kinda have the manual version of this with overriding `delete`, I think?! But if we want something that is called before the normal delete, that should be quite simple to add too. We just look up if the interface is implemented on the type and insert a call right before the call to delete is added.

Relevant code to look at is `Concretize.hs:718 (manageMemory)` and `Emit.hs:662 (delete)`.

**Comment by eriksvedang** [comment]
Also `createDeleter :: XObj -> Maybe Deleter` in `Concretize.hs`

**Comment by eriksvedang** [comment]
One concern about the potential to implement [RAII](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) if we implement this proposed `Drop` interface: What do we do about copying? Right now we just copy over the data in the struct (and malloc new heap memory for any members that require that). Perhaps we need a more advanced copying model before this feature even makes sense, or we will just start double-closing files, etc?

**Comment by TimDeve** [comment]
Hmm, that's a good point. Reading up on it, it seems this is why Rust has Copy and Clone which for us is one thing. I might be mistaken but it basically becomes the job of clone to make sure that the thing it's cloning is safe to drop later and if it's not possible then you shouldn't be able to clone it.

So I think you're right for managed type, however I still think there is value in letting people implement `delete` for opaque types, it doesn't have the problem we just discussed and it would basically allow people to get around some of Carp's limitation (Nested types, Boxed types...).

**Comment by eriksvedang** [comment]
Yes, we can start with that and then look into Copy/Clone.

**Comment by bjorn3** [comment]
In Rust Copy and Drop are mutually exclusive. Copy is for when a copy is equivalent to memcpy. Clone can run arbitrary code, but you must explicitly call it using .clone().

**Comment by eriksvedang** [comment]
@bjorn3 OK, that makes a lot of sense. Thanks for the clarification!
