### ISSUE TITLE
Very Small Example doesn't build on MacOS High Sierra (Pointer_prn__SDL_window & Pointer_prn_SDL_Renderer)

### ISSUE THREAD

**Issue by phillvancejr** [carp-lang/Carp#956]
When I try to build the very small sdl example on the front page, I get a few errors concerning the following functions:

Pointer_prn__SDL_window

Pointer_prn__SDL_Renderer

clang told me that there were some similar functions, and changing all references to the above functions to:

Pointer_copy_SDL_window
Pointer_copy_SDL_Render

fixed it and I was able to build successfully. I'm not sure if the prn versions are supposed to be there and are missing forward declarations or if the carp compiler is supposed to be generating the copy versions. Either the forward declarations for the prn variants should be added to the output c file or they should be changed to use the copy versions

**Comment by hellerve** [comment]
Oh interesting! I think this is related to my recent PR #948. Sorry about that! I'll look into how to fix it!

**Comment by eriksvedang** [comment]
Huh, I get this too:

```
/main.c:9474:10: error: implicit declaration of function 'Pointer_prn__SDL_Window' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  temp = Pointer_prn__SDL_Window(p->window); 
```

**Comment by TimDeve** [comment]
@eriksvedang Might be time to add the SDL stuff to the CI, I didn't do it at the time because I don't really know anything about it but it should just be a matter of installing the devel SDL package, no?

**Comment by hellerve** [comment]
It seems as if the fix is as simple as removing `Pointer.prn`. I would say that this is an error with function dependencies again, but since I don’t have the bandwidth to debug it, I’d suggest we just remove `Pointer.prn` for the time being?

**Comment by TimDeve** [comment]
Raised #959 so we don't miss the regression next time.
