### ISSUE TITLE
Building immediately after starting the repl gives error

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#957]
To reproduce:

1. Start the repl
2 Evaluate `(build)`

Error message:

```
main.c:14:10: fatal error: 'carp_stdbool.h' file not found
#include <carp_stdbool.h>
         ^~~~~~~~~~~~~~~~
```

**Comment by Kampouse** [comment]
I had similar problem dirty fix is to put the header file in compiler include folder

**Comment by scolsen** [comment]
seems to always fail unless you force evaluation of something resulting in an automatic definition of `main` or unless you define `main` yourself, that is, unless you get the repl to say `Compiled to 'out/Untitled' (executable)`.

```clojure
鲤 (defn foo [] 1)
鲤 (build)
out/main.c:14:10: fatal error: 'carp_stdbool.h' file not found
#include <carp_stdbool.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
carp: callCommand: clang out/main.c -shared -o "out/Untitled" -fPIC -g -std=c99 -D_DEFAULT_SOURCE -Wall -Werror -Wno-unused-variable -Wno-self-assign -lm (exit 1): failed
```

```clojure
鲤 (defn foo [] 1)
鲤 (foo)
Compiled to 'out/Untitled' (executable)
1
=> 0
鲤 (build)
Compiled to 'out/Untitled' (executable)
鲤 

```

```clojure
鲤 (defn main [] 0)
鲤 (build)
Compiled to 'out/Untitled' (executable)
```

**Comment by eriksvedang** [comment]
Huh! That's a great lead, at least. This must be somewhat recent (I actually thought we had a regression test for it, there was a similar bug way back.)

**Comment by eriksvedang** [comment]
Investigated a bit more, seems like it's the compiler command when compiling as a library that has broken. Makes sense, since we have no tests for that feature at all, iirc.

**Comment by eriksvedang** [comment]
Pushed some fixes for this.
