### ISSUE TITLE
Adding Carp to github linguist

### ISSUE THREAD

**Issue by wltsmrz** [carp-lang/Carp#972]
Gonna try to get Carp added to github's linguist. Not really sure if it will meet popularity minimums.

PR: https://github.com/github/linguist/pull/5093/

If it were to be accepted, I chose the color `#c63c24`. This is the dominant color from Carp image in README.md. Let me know if it should be something else. Also, I notice this color may well collide with HTML's color.

* `#c63c24` Carp (proposed)
* `#e34c26` HTML
* `#ba595e` D

**Comment by hellerve** [comment]
There is already a PR over at linguist: github/linguist#4530. It's still being monitored for popularity (github/linguist#4219)!

We also have an open issue here: #727.

**Comment by wltsmrz** [comment]
Oh! I thought I had searched for pre-existing PRs but probably didn't see it because it was closed. I'll close mine and maybe we can bump for updates in 4219.

In my script I arrived at 114 unique repos BTW, using https://github.com/feinoujc/gh-search-cli . The harvester script didn't work for me.

looping with,

```
npx ghs code --extension=carp defn >> out
sleep 2
cat <<< "o"
```

and ultimately,

```
cat out | cut -d " " -f1 | sort | uniq | wc -l
```

**Comment by eriksvedang** [comment]
Please create more public Carp repos :)

**Comment by scolsen** [comment]
I feel like we must have made some progress toward this? I was looking through the thread and here's something pchaigno said:

> That's going to depend on the extension. Hundreds of repositories is a rule of thumb; for a very specific extension with few chances of conflicts, such as .archimate, I'd be in favor of adding it now, with only 200-300 repositories; others will need a few hundreds more (think .m which we already have 7 languages associated to).

since `carp` is a pretty specific extension w/ low chance of conflict, maybe we can convince them to add lang support after a few more repos?

**Comment by wltsmrz** [comment]
I think their standards have changed a bit overtime, which might make sense as things become harder to maintain, more near-collisions with colors, etc..

As a reference I checked against MoonScript earlier, which was added to linguist in 2013 & despite the free marketing a github tag may provide tops out at 213 repos today (in my script anyway). We're probably not too far off.
