### ISSUE TITLE
Clarify version bumps

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#975]
Looks like the version in the .cabal file is out of date. Is this expected to be bumped manually? If so, maybe there should be a note with a checklist for the release process?

**Comment by eriksvedang** [comment]
Yeah that's a good idea!
Automating it would be even better but not sure how to do that either...

**Comment by jacereda** [comment]
Maybe we could get inspiration from: https://gist.github.com/bgamari/4e03ad3e4bb3530d285f

**Comment by jacereda** [comment]
At some point there must be some input or different scripts for deciding if it's going to be a major/minor/patch bump.

**Comment by eriksvedang** [comment]
I went the manual route for now.
